### ISSUE TITLE
Pin specific tools to start

### ISSUE THREAD

**Issue by Arlodotexe** [veler/DevToys#100]
**Is your feature request related to a problem? Please describe.**
Having to open the app, then select the tool is a bit cumbersome. 

**Describe the solution you'd like**
Pinning a tool to Start and launching right into it.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by veler** [comment]
Thank you for the suggestion :) That would be a nice addition to the following work item: #75

**Comment by Arlodotexe** [comment]
> Thank you for the suggestion :) That would be a nice addition to the following work item: #75

I agree, these two features would completement each other nicely. Might be a good idea to investigate doing the full-page view mentioned in #88 first, though.

**Comment by veler** [comment]
Thanks again @Arlodotexe ! It will be available in the next update :)
