### ISSUE TITLE
JSON 字符串格式化工具bug

### ISSUE THREAD

**Issue by vkviyu** [veler/DevToys#1008]
### Current behavior

![image](https://github.com/veler/DevToys/assets/90970572/1e4fb1c2-99c0-4f58-b541-220856a84af7)

### How to reproduce it (as minimally and precisely as possible)

当在 JSON 中输入相同的键，然后打上 {} 时，点击 enter 键，输入框会丢失，变成无响应状态。bug 可复现！

### Expected behavior

这个工具很好用，赶快修复！

### Screenshots

![image](https://github.com/veler/DevToys/assets/90970572/cafdd653-8f26-4385-b813-65cd4c0f397e)

### Workaround

在 JSON 中输入相同的键，然后打上 {} ，点击 enter 键

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

版本 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/13734418/logs.txt)

**Comment by veler** [comment]
Hi,
Thanks for this feedback. We can reproduce it in DevToys 1.0 but not 2.0. I will consider it resolved then. See #1013
