### ISSUE TITLE
Add a UTF-8 string length & byte counter

### ISSUE THREAD

**Issue by guidorobben** [veler/DevToys#1010]
### What feature or new tool do you think should be added to DevToys?

I needed to calculate the text for a HTTP call. I used the website https://mothereff.in/byte-counter for this to count the bytes.

Maybe add this as a tool?

### Why do you think this is needed?

I needed to calculate the text for a HTTP call. I used the website https://mothereff.in/byte-counter for this to count the bytes.

Maybe add this as a tool?

### Solution/Idea

Just use the same input & output that are on the website

![image](https://github.com/veler/DevToys/assets/11609736/0a835f60-16d4-4126-a850-c784a32c47c9)

**Comment by guidorobben** [comment]
Or the byte size could be added to the HTML Encoder/Decoder?

**Comment by veler** [comment]
Hello,

Unless I'm missing something, this tool already exists in DevToys :-)

![image](https://github.com/veler/DevToys/assets/3747805/05fa997b-1678-4c83-9f1d-f5052f0b0d2d)

![image](https://github.com/veler/DevToys/assets/3747805/cbad67f1-06f2-4d56-97f3-7c67c6378b95)

**Comment by guidorobben** [comment]
Sorry, my mistake. I couldn't find it. I had to use it for http encoding so this is the place I looked for it. But you are right, this is what I was looking for.
