### ISSUE TITLE
Go back / Go forward buttons

### ISSUE THREAD

**Issue by lkurzyniec** [veler/DevToys#1022]
### What feature or new tool do you think should be added to DevToys?

Would be nice to be able to navigate through opened windows/tools history with buttons.

VSCode inspiration: 
![image](https://github.com/veler/DevToys/assets/5943484/809c8024-c0f2-465f-984e-fb51997c8c9e)

### Why do you think this is needed?

Quicker go pack to previous opened window/tool.

**Comment by veler** [comment]
Hi,
This is already implemented in DevToys 2.0 (which will be release in preview in a few months).
