### ISSUE TITLE
Can it be adapted to docker? or can it be accessed and used in the web ui?

### ISSUE THREAD

**Issue by hurriedlu** [veler/DevToys#1026]
### What feature or new tool do you think should be added to DevToys?

Can it be adapted to docker? or can it be accessed and used in the web ui?

### Why do you think this is needed?

I think this tool is great, but I have a lot of devices, and quite a few that are non-Windows. I would like to deploy this tool on a server so that all devices can use it. This reply was translated into English via Deepl, please forgive me if some of the details may be wrong.

**Comment by veler** [comment]
Hi,
We have no plan to make it accessible from a web ui for now, but we do work at making it available on Windows Mac and Linux, fully usable with a UI and CLI. See #156 and the various pull request from the past year.
