### ISSUE TITLE
After paste a huge json sring in json parser, app become unusable

### ISSUE THREAD

**Issue by Alexis-Fayeulle** [veler/DevToys#1035]
### Current behavior

Like the title

I got a huge json and pasted it into the Json formatter.  
Now the application remembers this huge json and the Json formatter page every time I start the application.  
I can't get my cursor into the json entry to do cmd+A delete content.  
the only way to get out of this extremely laggy application is to force exit in the application monitor

### How to reproduce it (as minimally and precisely as possible)

1) find a huge json
2) paste it in JSON Formater

### Expected behavior

I suppose you could set a button for parsing if it's too slow, or if the json is very large  
or don't parse it, set a limit somewhere

### Workaround

kill the app and don't use it  
or find app cache and delete it

### Affected platforms

macOS (DevToys 2.0)

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

(unreachable)

### Relevant Assets/Logs

(unreachable)

**Comment by Alexis-Fayeulle** [comment]
ok i'm dumb
i just let app run a moment and this fixed the bug

**Comment by veler** [comment]
You're not dumb. It is a known issue of DevToys 1.0. It is slow. Good news is: it's faster in DevToys 2.0, which is coming soon :)
