### ISSUE TITLE
Improve search/tools filtering experience

### ISSUE THREAD

**Issue by ppo** [veler/DevToys#1036]
### What feature or new tool do you think should be added to DevToys?

Allow to search, filter tools using only the keyboard.

### Why do you think this is needed?

1. Shortcut to the search box (upper left). 
2. Focus on search results pane.
3. Results navigation with the keyboard.

### Solution/Idea

**Use case:** (on macOS)
1. `Cmd+F` [*]
2. Typing a query.
3. `Enter` or `Tab` => focus on the search pane.
4. Moving the selection with arrows.
5. `Enter` to go to the selected tool.

[*] _`Cmd+F` is currently assigned to the search in text boxes… so switch it to `Cmd+Shift+F`? I'll use more often search tools than search text box._

**Comment by veler** [comment]
Hi,

You mentioned being on MacOS, are you using DevToys 2.0 from our dev branch here?
Note that if you are using "DevToysMac", it is a different app that seems to be unmaintained.

**Comment by ppo** [comment]
Yes, sorry, wrong repo 😞
