### ISSUE TITLE
Converters and calculators

### ISSUE THREAD

**Issue by ppo** [veler/DevToys#1038]
### What feature or new tool do you think should be added to DevToys?

All the calculators and converters we can think of.

### Why do you think this is needed?

EV•RY•THING! 😂

### Solution/Idea

Similar to [GIGACalcultator](https://www.gigacalculator.com/), [Converter+](https://www.trancreative.com/) (iOS app) and [OnlineConversion.com](https://www.onlineconversion.com/)

**Comment by veler** [comment]
Duplicate with #833
