### ISSUE TITLE
Never smart detect "Escape / Unescape"

### ISSUE THREAD

**Issue by aaronliu0130** [veler/DevToys#1039]
### What improvement do you think would an existing feature or tool in DevToys?

Often, I copy some code to use text comparer with, and everytime I reopen the Window, DevToys thinks I want to use Text Escape and automatically pastes into it. This is very annoying.

### Solution/Idea

Remove "Escape / Unescape"'s smart detection.

### Comments

By the way, why is it "Text Diff" in the sidebar and "Text Comparer" everywhere else?

**Comment by veler** [comment]
Hello,

You can disable this behavior through this option:

![image](https://github.com/veler/DevToys/assets/3747805/655d05a6-afa9-4d41-bd5c-4cf39894b63e)

> By the way, why is it "Text Diff" in the sidebar and "Text Comparer" everywhere else?

We changed this in DevToys 2.0, which will be released soon.

**Comment by aaronliu0130** [comment]
That checkbox disables Smart detection as well, plus I want to be able to auto-paste JSON.

**Comment by aaronliu0130** [comment]
Hi @veler, please reconsider.
