### ISSUE TITLE
Password Generator Output, Multiple Click Consistency with UUID

### ISSUE THREAD

**Issue by devjt2** [veler/DevToys#1045]
### What improvement do you think would an existing feature or tool in DevToys?

Within the password generator feature, a user can choose how many passwords they want to generate and get the expected output. However, a user may want to more naturally grab one or more passwords just by mashing the "Generate Password" button. At present, multiple presses of the "Generate Password" button will clear the list of passwords generated in the text box.

### Solution/Idea

I propose that this password generator output is treated the same way the UUID generator is implemented. By mashing the "Generate UUID" button multiple times the list does not clear and the user will obtain multiple outputs in the text box.

**Comment by devjt2** [comment]
I volunteer to make this enhancement.

**Comment by veler** [comment]
Hello,
Thanks for the suggestion. This is actually already implemented in DevToys 2.0 😁
