### ISSUE TITLE
App crashes when go to Base64 Text in Encoders/Decoders menu

### ISSUE THREAD

**Issue by mythter** [veler/DevToys#1058]
### Current behavior

App crashes when I am trying to go to the "Encoders/Decoders" -> "Base64 Text" in menu.

![image](https://github.com/veler/DevToys/assets/60883514/c17d2439-4415-41b5-9896-2adc785faf11)

### How to reproduce it (as minimally and precisely as possible)

1. Open the app
2. Drop down "Encoders/Decoders" menu item
3. Click on "Base64 Text" menu item

### Expected behavior

Base64 Text encoder/decoder UI appears

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/14315887/logs.txt)

**Comment by veler** [comment]
Duplicate with #755
