### ISSUE TITLE
Time formatter

### ISSUE THREAD

**Issue by kid1412621** [veler/DevToys#106]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
support for time formatting and converting

**Describe alternatives you've considered**

**Additional context**

**Comment by veler** [comment]
Hi,
Thanks for suggesting this tool. @btiteux , didn't you mention me that we would need to support time formatting and conversion for improvement in the JWT Decoder #39 and that we could make it a tool?

**Comment by btiteux** [comment]
Hi, thank you for the suggestion.

Yes for the JWT Decode we will need support for time conversion. So if this tool is made before we will need to make a helper available for other tools.

**Comment by veler** [comment]
Thanks @btiteux . Therefore, perhaps a Time Formatting and Converting tool is a higher priority than JWT Decoder improvement, or should both be done at the same time. Thoughts?

**Comment by btiteux** [comment]
@veler yes we can work on this one before the improvement on JWT Decoder.

**Comment by beeradmoore** [comment]
@veler , I'd be happy to give this a shot if you want. Any idea of all the features you'd want it to have?

Personally I only ever use timestamp -> local + GMT timezones like what [EpochConverter](https://www.epochconverter.com) does.
![Screen Shot 2022-02-17 at 8 49 26 am](https://user-images.githubusercontent.com/904737/154363232-4e5b46c2-a9f1-4ae7-ba65-5dd0ec3f546d.png)

I assume the input box should be able to detect if the timestamp is seconds or milliseconds automatically. 

Is there any calendar component used elsewhere that could be used for going from time -> timestamp?

Is there any use case for rolling history of timestamps you've just entered to be displayed below?

**Comment by ThreeSevenths** [comment]
@beeradmoore I was going to ask for this yesterday. Can it just start with the current time if a timestamp isn't already on the clipboard? Maybe even live and inputs for seconds, millis, DateTime/DTO and perhaps UTC or an extra time zone a-la Windows?

**Comment by beeradmoore** [comment]
So essentially just all the same inputs that [EpochConverter](https://www.epochconverter.com/) does?

**Comment by beeradmoore** [comment]
> beeradmoore: I'd be happy to give this a shot if you want. 
> Narrator: He never gave it a shot.

Looks great @veler!
