### ISSUE TITLE
Converter for byte size values for different orders of magnitude (binary and/or decimal)

### ISSUE THREAD

**Issue by instilledbee** [veler/DevToys#1063]
### What feature or new tool do you think should be added to DevToys?

An interactive converter that shows numeric values for a given byte size, converted to [various orders of magnitude](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units). Optionally allow/display conversion between decimal multiples (`1000`) and binary multiples (`1024`) for a given byte size.

e.g. if I want to know how to convert `1073741824` bytes, the tool would show me:

| Unit | Binary     | Decimal   |
| ---- | ---------- | --------- |
| KB   | 1048576.00 | 107371.82 |
| MB   |    1024.00 |   1073.74 |
| GB   |       1.00 |      1.07 |

### Why do you think this is needed?

I typically find myself having to manually calculate how many bytes there are for a given kilobyte, megabyte, gigabyte etc. While I can easily pull up calculator to multiply values by `1000` or `1024`, I think it would be useful to have an interactive converter that visualizes how many KBs or MBs there are for a given numeric value.

### Solution/Idea

Possibly something similar to the existing **Number Base** converter, with multiple editable textboxes for the various orders of magnitude to be supported (thinking most common units are up to terabytes these days)

* Bytes
* KBs
* MBs
* GBs
* TBs

Inputting a number on one of the textboxes populates the others with the corresponding converted value.

Then an optional toggle to use decimal or binary unit multiples, that dynamically updates the values in the textboxes when clicked.

**Comment by veler** [comment]
Duplicate with #148
