### ISSUE TITLE
Crash when pressing copy in the JSON formatter when output is empty

### ISSUE THREAD

**Issue by winston-de** [veler/DevToys#11]
**Describe the bug**
Clicking copy in the json formatter output when the output is empty will cause the app to crash.

**To Reproduce**
1. go to json formatter
2. clear input, if there is any
3. press copy
4. app crashes

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS & Version: Windows 10 19043.1237
 - Theme: both
 - DevToys app version [e.g 0.5.0.0]

**Additional context**

**Comment by veler** [comment]
Hi,

Thank you for sharing this feedback! I've been able to reproduce it easily. I will try to fix it this weekend. :)
