### ISSUE TITLE
Icons on the All tools page look blurry

### ISSUE THREAD

**Issue by vladimirkosolapov** [veler/DevToys#123]
**Describe the bug**
Some icons on the All tools page look blurry. This applies to:
- Base 64
- HTML
- Json
- Json <> Yaml
- JWT Decoder
- Markdown Preview
- Regex Tester
- Text Diff
- UUID

**Screenshots**
<details>
  <summary>Click to expand</summary>
  <img src="https://user-images.githubusercontent.com/34649010/147385941-d01fd436-baf0-41e5-bbd4-c0cd0b9dbd82.png"/>
</details>

**Configuration:**
 - OS & Version: Windows 11 (22000.376)
 - Theme: Dark
 - DevToys app version 0.9.0.0

**Comment by veler** [comment]
Hello,

Thank you for sharing this. :)
A couple of follow up questions, please:
1. What is the resolution of your screen (in pixels) ?
2. What is the Scale of your screen, in Windows' settings (in %) ?

Thanks :)

**Comment by vladimirkosolapov** [comment]
> 1. What is the resolution of your screen (in pixels) ?

Resolution is 1920x1080 (14.0")

> 2. What is the Scale of your screen, in Windows' settings (in %) ?

Scale is 150%

**Comment by veler** [comment]
Thank you. I've been able to reproduce the issue. I will try to take a look at it 😊

**Comment by veler** [comment]
@vladimirkosolapov hi,
I made a PR here. It looks better on my screen now. :)
https://github.com/veler/DevToys/pull/124
