### ISSUE TITLE
Image converter

### ISSUE THREAD

**Issue by Arlodotexe** [veler/DevToys#125]
**Is your feature request related to a problem? Please describe.**
Sometimes as a dev, I have an image in one format, and quickly need it in another. The only way to do this is
- Using an online converter
- Open in MsPaint and re-save it.

Both of these options are cumbersome and overkill for such a simple thing.

**Describe the solution you'd like**
Similar to the Image Png / Jpeg compressor tool, I'd like a new tool under the "Graphic" category for converting images between types.

**Describe alternatives you've considered**
- Using an online converter
- Open in MsPaint and re-save it.
- Building my own tool (not everyone should have to)

**Comment by rlm96** [comment]
Hey, I would like to work on this improvement if possible 😁

**Comment by veler** [comment]
Hi,
I think @btiteux was about to start working on it. @btiteux , is that correct? If not, we can let @rlm96 giving it a try :)
