### ISSUE TITLE
Repetition of language setting options

### ISSUE THREAD

**Issue by Gaoyifei1011** [veler/DevToys#140]
[image](https://user-images.githubusercontent.com/49179966/149809259-e45c4628-13c3-4286-880c-48ff60a912da.png)

在这张图片中，我看见目前发布的0.9.3版本的语言选择中包含了“中文（中国）”和“中文（简体）”这两个选项，这两个选项发生了重复，通常使用”中文（简体）“和”中文（繁体）“这两个选项，“中文（中国）”中包含了”中文（简体）“和”中文（繁体）“这两个选项的所有内容，所以“中文（中国）”不应该出现在选项设置中。而且目前的选项设置中“中文（中国）”和“中文（简体）”设置显示的语言都是相同的，希望能解决一下这个问题。
我认为这些内容可以帮助您更好的理解简体中文与繁体中文的关系和区别。
In this picture, I can see that the language options for the current release of 0.9.3 include "中文（中国）" and "中文（简体）". The two options are duplicated, usually using "中文（简体）" and "中文（繁体）". "中文（中国）" contains all the contents of the "中文（简体）" and "中文（繁体）" options, so "中文（中国）" should not appear in the Settings. In addition, the current Settings of "中文（中国）" and "中文（简体）" are displayed in the same language. I hope to solve this problem.
I think these contents can help you better understand the relationship and difference between simplified Chinese and traditional Chinese.
https://zhuanlan.zhihu.com/p/96208556
https://zhidao.baidu.com/question/34801261.html

希望能够在1.0正式版发布前能够解决一下这个问题
Hopefully this will be resolved before the 1.0 release

**Comment by veler** [comment]
Hi,

Thank you for sharing this. I'm sorry that there's still some issue with Chinese support.

On my side, I'm not seeing this bug:

![image](https://user-images.githubusercontent.com/3747805/149822489-87d5a5b8-8af3-4bec-9ad5-79e4fbe789c0.png)

Question:
1. Do you have multiple Chinese languages installed on Windows?
2. Does uninstalling and re-installing the application fix the issue?

Thank you

**Comment by Gaoyifei1011** [comment]
关于第一个问题，我只是在我的电脑中安装了简体中文的语言包，系统也是简体中文版本，其他应用没有遇到这个问题。这个应用是我从应用商店里面下载的，您也可以在虚拟机里尝试安装简体中文版本的Devtoys检验一下这个问题。
Regarding the first question, I just installed the simplified Chinese language pack on my computer, and the system is also simplified Chinese version. Other applications do not encounter this problem. I downloaded this app from the app store. You can also try installing Devtoys in Simplified Chinese on the virtual machine to check this out. 
关于第二个问题，我在我的另外一台电脑上新安装这个软件也会有这样的情况
On the second question, I will have the same situation when I install this software on another computer

**Comment by veler** [comment]
Thank you very much for your answer. I will try to investigate it. :)
