### ISSUE TITLE
Checksum generator

### ISSUE THREAD

**Issue by veler** [veler/DevToys#141]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to be able to calculate the checksum of a file.

**Describe the solution you'd like**
Let's add a tool for generating Checksum.

**Comment by Joaolfelicio** [comment]
Hey @veler , this seems interesting and maybe I could help.
Can you give more information about this feature?

**Comment by veler** [comment]
Hello @Joaolfelicio , sure thing!
The workflow behind this tool would be:
1. User selects 1 file.
2. User choose whether an MD5, SHA-1, SHA-256...etc hash should be generated.
3. When computing the hash, ideally a progress bar would be displayed (or at minimum a UI indicating that a background process is in progress).
4. The resulted hash is displayed on screen.
5. Finally, perhaps an extra field would allow the user to compare the generated hash with a hash of his choice.

We already have a Hash Generator for text. What I'm not very sure is whether it would make sense to support both (text and file hash generation) in 1 tool, or if we should split it in 2 tools.

Regardless, you can find some guidance on the creation of a new tool here: https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md

You can also take some existing tool as a template. I'd recommend to look at the implementation of the existing Hash Generator tool and Color Blindness Simulator (freshly added to the app but not published yet: https://github.com/veler/DevToys/pull/138)

Let me know if this help or if you want to brainstorm it :)

**Comment by Joaolfelicio** [comment]
Sounds good to me!
If you want, you can assign this to me.

I think if we separate the tools, it would be a bit more clear of its purpose, even if the insides are pretty similar. `Checksum File Tool` would be pretty verbose about its intent.
Let me know what you think!

**Comment by veler** [comment]
Agreed! A separated tool is probably best. Go for it! 😁 😁 😁

**Comment by jwfxpr** [comment]
Bug report at #186 is relevant to this discussion. 😊
