### ISSUE TITLE
Any way to install without having to use appx/msix?

### ISSUE THREAD

**Issue by MarcelskyXD** [veler/DevToys#143]
On my system, i cant install any app packages (appx or msix)

is there any way to install devtoys without needing to use the msix installer?

**Comment by veler** [comment]
Hello,

Thanks for your feedback, I believe this article may help at making it possible to install the MSIX: https://yairai.medium.com/how-to-restore-windows-10-app-installer-99c15b7c3ec4

**Comment by veler** [comment]
Duplicated with #173
