### ISSUE TITLE
Windows shell preview for code files

### ISSUE THREAD

**Issue by MJRasicci** [veler/DevToys#144]
**Is your feature request related to a problem? Please describe.**

Windows explorer preview pane doesn't display text files with many file extensions.

**Describe the solution you'd like**

Adding previewers for code files with syntax highlighting. Integration with something like vscode themes or even just a DevToys settings menu to customize font (ligature support would be a plus), font size, and a dark/light mode would be amazing.

**Describe alternatives you've considered**

Existing workarounds with the registry to add file extensions to the plaintext previewer are hackish and aren't as pleasing to the eye as a proper previewer would be.

**Comment by veler** [comment]
Hello,

Thanks for your feedback. Have you look at the app Files yet? https://files.community/
I believe its preview pane does this. :)
