### ISSUE TITLE
Grammar mistake in Number Base Converter

### ISSUE THREAD

**Issue by doankimhuy-it** [veler/DevToys#150]
**Describe the bug**
Grammar mistake when exceeding number conversion limit.

**To Reproduce**
1. Go to 'Number Base Converter'
2. Enter some long number in Decimal input field.
3. A warning appears. See screenshot below.

**Expected behavior**
It should be changed to something like "The current value cannot be parsed because it exceeds the maximum value"

**Screenshots**
![image](https://user-images.githubusercontent.com/31150748/150240917-5f2b3417-2253-4a56-9909-ee25af9bbb4a.png)

**Configuration (please complete the following information):**
 - OS & Version: Windows 11 Dev build 22533
 - Theme: Dark
 - DevToys 1.0.0.0

**Comment by veler** [comment]
Thanks for reporting this, and sorry about that, the 2 main contributors to this repo aren't native English speaker ;-)
Will fix this soon :)
