### ISSUE TITLE
Replace original files in the PNG/JPEG compression

### ISSUE THREAD

**Issue by ckaiser** [veler/DevToys#151]
**Is your feature request related to a problem? Please describe.**
It's time-consuming to save-as every file (and save all doesn't seem to do anything for me?).

**Describe the solution you'd like**
When optimizing images it'd be nice to be able to drag and drop a few, click on a "Replace All" button and be done, or even have a checkbox to just do that automatically as they finish, I usually end up dragging multiple to an optipng executable to accomplish the same thing, but having everything in this tool would be nice.

**Comment by veler** [comment]
Hello,

Thanks for your feedback. The `Save All` button is supposed to prompt a Save Dialog that would allow you to select a folder where the files should be saved. Once selected, the compressed files should be moved in this target folder and replace existing files. See https://github.com/veler/DevToys/blob/0ebab4eeb28f8d94e7bc97738e1c9439ee892b67/src/dev/impl/DevToys/ViewModels/Tools/Graphic/PngJpgCompressor/PngJpgCompressorToolViewModel.cs#L226-L240

Does the `Save All` button does absolutely nothing for you?

**Comment by ckaiser** [comment]
Hi!

At the moment the `Save All` button does absolutely nothing, and the `Save` button for individual images opens up a save dialog box defaults to the desktop, which makes it a bit tedious to navigate to things individually.

**Comment by veler** [comment]
Hi,
That is interesting. It sounds like a bug. A save dialog definitely shows up for me when clicking `Save All`. I will try to reproduce it and fix it.

**Comment by ckaiser** [comment]
Thanks! I can attempt to see if I can make it work on other files/folders later today, because I only really attempted on the one screenshot folder that I had so maybe it's something to do with that particular file path or disk drive or something related to that (spaces on the filename? or folder?)

**Comment by ckaiser** [comment]
From what I can tell from a quick run of the code under a debugger, it's giving an "Unspecified error" from inside `PickSingleFolderAsync()`.

No error code or anything, it just fails. 

A quick google led me to this [StackOverflow question](https://stackoverflow.com/questions/49178567/uwp-folderpicker-picksinglefolderasync-fails-with-comexception-e-fail/49182049), and their solution actually worked! Adding `folderPicker.FileTypeFilter.Add("*");` after initializing the folder picker made it stop crashing.

**Comment by veler** [comment]
Oooooh, that's interesting :O 
I will have to give it a try. Also, it puzzles me that it only reproduce on some machine (at least yours and not mine). Thank you for sharing this!

**Comment by veler** [comment]
Alright, I just pushed the fix as part of this PR: https://github.com/veler/DevToys/pull/308
Thank you very much again for the help with it!
