### ISSUE TITLE
Output fields do not have fixed width font

### ISSUE THREAD

**Issue by JyeGuru** [veler/DevToys#153]
**Describe the bug**
Output fields are not respecting font choice in settings

**To Reproduce**
- Open the UUID tool
- Generate a few UUIDs
- Cry because they're not neatly aligned

**Expected behavior**
Fixed-width font outputs on fields where it makes sense:
- UUIDs
- Hashes

**Screenshots**
![image](https://user-images.githubusercontent.com/5215014/150282832-b9176a03-a1c8-42c7-beb6-e00bba8dc453.png)
![image](https://user-images.githubusercontent.com/5215014/150283061-58aa5c8f-a9ba-4c11-bbee-f11c4b284047.png)

**Configuration (please complete the following information):**
 - Win10 21H1 19043.1387
 - Theme: System (Dark)
 - Version 1.0.0.0 | X64 | RELEASE | ef783c8 | ef783c8

**Additional context**

**Comment by veler** [comment]
Hello,

> Cry because they're not neatly aligned

So sorry about that 🤣😁

The Font setting only applies to the code editor (the text field with line numbers and syntax colorization).
Perhaps every fields should have this font applied? Or perhaps "some" fields that make sense to use the font (like the Hash and Guid generators perhaps).

**What do you folks think?**

Ping @btiteux

**Comment by KillyMXI** [comment]
Fields should have a named style to reflect the nature of displayed values. Font will be a property of a style.
(I'm not sure about names though. The distinction is that some values are for human consumption, others are code-like, for machine consumption.)

Another place where monospace font is important - Regex Tester.
