### ISSUE TITLE
Suggestion: Toggle for Encode/Decode options

### ISSUE THREAD

**Issue by JyeGuru** [veler/DevToys#154]
**Is your feature request related to a problem? Please describe.**
It takes two clicks to change between encoding and decoding

**Describe the solution you'd like**
The dropdown replaced with a toggle switch similar to the other panels on/off switches

**Describe alternatives you've considered**
Wearing out my mouse by clicking twice as much

**Additional context**
Loving the tool so far, I can see it replacing quite a few bookmarks already!

**Comment by veler** [comment]
Hello,

That's a good suggestion! Thank you very much :)
