### ISSUE TITLE
Suggestion: GIF Frame Exporter

### ISSUE THREAD

**Issue by JyeGuru** [veler/DevToys#155]
**Is your feature request related to a problem? Please describe.**
Ability to split an animated gif into component frames would be useful

**Describe the solution you'd like**
A tool that allows selecting a gif and outputs a grid of thumbnails for each frame, allowing single frames to be saved or all to be exported at once to a folder/zip

**Describe alternatives you've considered**
Continuing to use https://ezgif.com/split/ezgif-3-b5246d096f.gif

**Additional context**
https://codingvision.net/c-get-frames-from-a-gif

**Comment by veler** [comment]
This can already be achieved using https://www.screentogif.com/ It has a GIF editor, without having to record something from the screen first.
