### ISSUE TITLE
SVG Compression/Optimizer

### ISSUE THREAD

**Issue by Nickztar** [veler/DevToys#158]
**Is your feature request related to a problem? Please describe.**
Would be super nice to be able to handle SVGs in DevToys. Kind of like with images, its a very common thing to do.

**Describe the solution you'd like**
Select the SVG och paste the SVG code and it optimizes it accordingly.

**Describe alternatives you've considered**
Something like this would be super nice, maybe a bit overkill. Having it do simple optimization would be enough:
https://jakearchibald.github.io/svgomg/

**Comment by veler** [comment]
Duplicate with #149
