### ISSUE TITLE
Add string escape converter

### ISSUE THREAD

**Issue by andyesys** [veler/DevToys#160]
Add a conversion between escaped and unescaped strings.

I often need to either escape strings (`Hello "World"!` to `"Hello \"World\"!"`) or unescape strings the other way around when working in C#.

This is painfull for large texts like XML markup with all its attributes in double quotes.

**Comment by veler** [comment]
Hi,
Thanks for this suggestion. I like this idea :) Sounds like something we can potentially add to the existing Text Inspector, or make a brand new tool for it.

**Comment by veler** [comment]
See also: https://www.freeformatter.com/json-escape.html

**Comment by ainslec** [comment]
I second string escaping. I came here precisely to ask for this. I'd like to see text escaping for Java literal strings, for C/C++ literal strings, for C# literal strings, for JSON, for HTML, for XML, and more.
