### ISSUE TITLE
Suggestion: Hide tools from menu or pin with a favorite function

### ISSUE THREAD

**Issue by trembon** [veler/DevToys#161]
**Is your feature request related to a problem? Please describe.**
If the number of tools grow over time the menu will risk become very cluttered.
Also, for each user which tools they use may vary and with time become more tedius to find the right tool directly.

**Describe the solution you'd like**
Add the option in settings to hide tools or groups from the menu if they are never used by the user.
Another solution might be to add a "Favorites" function to pin the tools you use the most.

**Describe alternatives you've considered**
Ignoring this and be happy to have a great tool

**Comment by veler** [comment]
Duplicated with #75
