### ISSUE TITLE
Portable version decoupled from Microsoft Store

### ISSUE THREAD

**Issue by MattFromGer** [veler/DevToys#162]
Some devs work at companies where IT blocks access to the Microsoft Store. Normally I install my apps over scoop, but I can use winget - no problem. Unfortunately I get this error:
`Failed to install or update Microsoft Store package because Microsoft Store client is blocked by policy`

Is it possible to add a portable version to the release files?

**Comment by Stan-C421** [comment]
I agree with this, if there is no portable version, I will not be able to use the application.

**Comment by veler** [comment]
Duplicated with #173
