### ISSUE TITLE
can we have a SQL / HTML / JS beautifier?

### ISSUE THREAD

**Issue by thdotnet** [veler/DevToys#167]
I think it would be a great feature for the DevToys. Many times people don't pay attention on code indentation, this feature would fix that in order to make sure code is properly formatted increasing readability.

**Comment by chall3ng3r** [comment]
This!

**Comment by veler** [comment]
Hi,
Thanks for your suggestion. Since your idea regards multiple languages, I split this issue into 3:
- #175 
- #176 
- #136
