### ISSUE TITLE
Rounding error in JSON to YML conversion

### ISSUE THREAD

**Issue by beatbrot** [veler/DevToys#168]
**Describe the bug**
In the JSON to YML converter, numbers are sometimes rounded wrongly.

**To Reproduce**

Convert the following JSON to YML:

```json
{
    "foo": 1.4
}
```

And you get:

```yml
foo: 1.3999999999999999
```

**Expected behavior**

```yml
foo: 1.4
```

**Configuration (please complete the following information):**
 - OS & Version: Windows 11 21H2
 - Theme: Dark
 - DevToys app version: 1.0.0.0 | X64 | RELEASE | ef783c8 | ef783c8

**Comment by veler** [comment]
Hi,
Thanks for reporting this. We will try to fix it when we get some time. This repository notoriety blew up yesterday and we're taking sometime looking at all the feedback and triaging them :)

**Comment by akarboush** [comment]
Is there really a need for a custom converter?
Why just not specify that floating point numbers should be parsed as `decimal` in the [JsonConvert.DeserializeObject](https://github.com/veler/DevToys/blob/3b612270587f89479e191fdddcab18ca4d08d501/src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs#L233)
```csharp
private readonly Newtonsoft.Json.JsonSerializerSettings _defaultJsonSerializerSettings = new () 
{
   FloatParseHandling = FloatParseHandling.Decimal 
};
..........
dynamic? jsonObject = JsonConvert.DeserializeObject<ExpandoObject>(input, _defaultJsonSerializerSettings );

```
Decimal would also handle a larger number than double
