### ISSUE TITLE
Validate XML Using XML Schema

### ISSUE THREAD

**Issue by NikolayEKolev** [veler/DevToys#171]
**Is your feature request related to a problem? Please describe.**
It would be very nice if you could add Validate XML Using XML Schema

**Comment by davidTigris** [comment]
Hi @NikolayEKolev!
Do you mean XSD validation?
Was thinking about maybe implementing something like that 😅

**Comment by NikolayEKolev** [comment]
> Hi @NikolayEKolev! Do you mean XSD validation? Was thinking about maybe implementing something like that 😅

Yes, @davidTigris, exactly XSD validation.
Like https://www.freeformatter.com/xml-validator-xsd.html

**Comment by davidTigris** [comment]
@NikolayEKolev
Will start working on this beginning of March, where I have some spare time!
Do you have experience with MEF?

**Comment by BroMarduk** [comment]
Json Schema validation would also be a great additional feature.

**Comment by davidTigris** [comment]
@BroMarduk sure, but think this should be covered in a seperat feature request/discussion 🙂
Feel free to create one!

**Comment by NikolayEKolev** [comment]
> @NikolayEKolev Will start working on this beginning of March, where I have some spare time! Do you have experience with MEF?

What does MEF mean?

**Comment by davidTigris** [comment]
Please have a look at the "contribution" instructions and let me know if you could somehow contribute to making this feature reality 🙂

**Comment by davidTigris** [comment]
Small update: was not able to really get started yet. But I think I will be able to have a first draft on the end of this month.
If anyone wants to join forces - feel free to DM me 😉🎉

**Comment by davidTigris** [comment]
Alright!
Was working on the feature this week so that I now have a first version of it.
It's still lacking test coverage and some refactoring. **Will create a PR next weekend!**

**Comment by davidTigris** [comment]
I now pushed the [first version of thetool](https://github.com/davidTigris/DevToys/tree/features/xml-validator).
Feel free to have a look.
Tests are still missing - that's why I will postpone my PR for another week.
General functionality is already there. Cheers!

**Comment by davidTigris** [comment]
Tests were added.
MR is open now 😃

**Comment by davidTigris** [comment]
Sure, in theory this could be added.
I personally would like to focus on the core functionality of the validator tool right now. Let's discuss this in a separate issue/feature request discussion after my initial PR is finally merged.
