### ISSUE TITLE
Feature: Streamline DevToys installation requirements and experience

### ISSUE THREAD

**Issue by aureq** [veler/DevToys#173]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm a developer who works mostly on remote Linux environments and I have very limited development knowledge on Windows. My work laptop (Win 10) is managed by my employer and I have very limited abilities to install libraries and apps via the Windows Store, Winget, NuGet, Choco, Scoop and so on.

Today, I tried to install DevToys for the first time and I have to admit, my experience has been quite difficult (nope, still not installed).
- Install the developer certificate as a trusted  root certificate (as admin? as User?)
- I was missing Microsoft UI Xaml, so I got help to get it installed.
- And now asking for Microsoft.NET Native Framework 2.2 (I've read .NET 6 was the way forward?)
- And I genuinely don't know what other dependencies will be required after.

## Solution / Idea details

Ideally, it would be great to have a single `.exe` like it's done for the Microsoft PowerToys, or eventually a `.msi` package where everything is self contained into a single installable package. This package would be published on the Github release page so people who watch for new releases get a notification when a new stable version is published.

During the installation, if the package requires elevated privilege, then the installer should prompt the user.

## Alternatives considered

At the moment, I haven't been able to find any alternative due to the restrictions on my laptop. I'll give it another go over the coming days/weeks to try to 

## Additional content

It seems like other folks have also had mixed experience or share similar views.

- #162 
- #143 

Thank you for considering this issue.

**Comment by veler** [comment]
Hello,

Thank you very much for sharing this feedback. I can understand the frustration.
The dependencies missing are puzzling to me. They should be included with the package.

Can you please what the following article suggest regarding getting App Installer on Windows? https://yairai.medium.com/how-to-restore-windows-10-app-installer-99c15b7c3ec4

App Installer is the component that allows to properly install the app.

As for providing an installer, I will need to do some researches for this. I'm wondering if Advanced Installer could help with that: https://www.advancedinstaller.com/msix-packaging.html

**Comment by aureq** [comment]
Thanks @veler for looking and considering the improvement.

Regarding the article mentioned, unfortunately the whole package seems to have been removed from the OS and it doesn't show in the list either. Furthermore, I looked into the _delete windows apps_ folder and nothing left there either.

I think the one key feature I really love about DevToys is that everything is offline unlike so many things these days.

**Comment by veler** [comment]
Ugh, I'm sorry this wasn't helpful. It sounds like the company policy makes it very painful. I don't have a solution from the top of my head but I will think about it. Unfortunately with UWP app, it's not as easy as just sharing a .exe in a ZIP.

**Comment by veler** [comment]
We made a PR here that should allow WinGet to install DevToys without requiring a Microsoft account: https://github.com/microsoft/winget-pkgs/pull/43996/files

**Comment by saturnw** [comment]
Would be great to have DevToys available through choclatey. Looking forward to hearing from you soon. 

Many thanks in advance

**Comment by veler** [comment]
Hello,
Thanks to @rlm96 , DevToys is now available on Chocolatey. Would you be able to give it a try, please?

See: https://github.com/veler/DevToys#chocolatey

Thank you !
