### ISSUE TITLE
Loosen requirements for base64 decoding

### ISSUE THREAD

**Issue by kimipsen** [veler/DevToys#178]
Vote on this issue by adding a 👍 reaction.
If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Is your feature request related to a problem? Please describe.**
When pasting base64 encoded strings, often it won't decode these, unless I manually pad the ending with '='.

**Describe the solution you'd like**
It would improve usability if the tool automatically tried padding until the string became a valid/strict base64 string.

**Describe alternatives you've considered**
Consider showing a warning when failing to decode a string, as it currently is rather difficult to see whats happening.

**Comment by Regenhardt** [comment]
I could imagine adding this real quick, seems like a good first issue?

**Comment by AHollowedHunter** [comment]
I have been playing around with this myself, I've added automatic padding conditions but was also looking at implementing an InfoBar below the input box which can be used to provide feedback to the user if the input is invalid or has been automatically padded.

**Comment by i3anaan** [comment]
Thought the decoding was simply broken, turns out it was missing the `=` padding. A warning would be much appreciated at the least.
