### ISSUE TITLE
negative number base conversation 

### ISSUE THREAD

**Issue by QuantinJohnes** [veler/DevToys#185]
**Describe the bug**
The wrong output when providing negative numbers.

**Expected behavior**
The wrong output when providing negative numbers.

**Screenshots**
![image](https://user-images.githubusercontent.com/97216776/150536183-0bf6a76b-071f-48a2-96b6-48fa334aaddd.png)

**Configuration (please complete the following information):**
 - OS & Version: [e.g. Windows 10 1903] yes
 - Theme: [e.g. Dark] Light
 - DevToys app version [e.g 1.0.0.0] yeah

**Comment by veler** [comment]
@btiteux ? 👀

**Comment by btiteux** [comment]
Yes I will look for this bug

**Comment by btiteux** [comment]
Hello,
This issue has been resolved in a pull request #213, so I'm closing this issue.
