### ISSUE TITLE
Hash Generator fails to open binary file

### ISSUE THREAD

**Issue by abaines-nextup** [veler/DevToys#186]
**Describe the bug**
When trying to open a **binary** file, Hash Generator fails:
![image](https://user-images.githubusercontent.com/91232270/150537082-a723aeb0-393d-433a-8d3f-0bc96b88a7de.png)

Logs
```
# - [01/21/2022 08:42:25]
Feature name: Failed to load a file into a code editor
Custom message: 
Exception message: No mapping for the Unicode character exists in the target multi-byte code page.

No mapping for the Unicode character exists in the target multi-byte code page.

Exception stack trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at DevToys.UI.Controls.CustomTextBox.<OpenFileButton_Click>d__83.MoveNext() + 0x2af
```

**To Reproduce**
1. Go to `Hash Generator`
2. Click on icon to load a file.
3. Select a **binary** file (like an .exe file)
3. See error message (see above)
4. Click `Open logs`
5. See log messages (see above)

**Expected behavior**
I expect to see a MD5, SH1, SHA256, SHA512 for the binary file. The `Input` field can be blank or disabled, or red or some text saying `Cannot display binary file but the hash values are below` or similar.

**Screenshots**
See above.

**Configuration (please complete the following information):**

- Version 1.0.0.0 | X64 | RELEASE | ef783c8 | ef783c8

Thank you! 🧡

**Comment by veler** [comment]
Hello,
Thanks for your feedback. I believe you just put the finger on a design issue on our part. This Hash Generator tool is made for getting hash out of a string or text file, not a binary file. But the tool isn't really explicit about it.

We have a #141 tool planned, and it should help addressing this confusion. :)
