### ISSUE TITLE
UNIX/Epoch time converter

### ISSUE THREAD

**Issue by thre3eye** [veler/DevToys#188]
Vote on this issue by adding a 👍 reaction.
If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

Great stuff. Thanks!

As a suggestion: A UNIX/Epoch time converter like this would be useful https://www.epochconverter.com/

Thanks!

**Comment by Osolemio44** [comment]
+1

**Comment by veler** [comment]
Duplicated with #106
