### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by Loeffeldude** [veler/DevToys#191]
Seeing the many requests for features I think it would be good idea to implement a plugin system. It would make it easy to ship new functionalities and let devs programm their own plugins if there isn't a big demand for a feature they want. 

Forking the repo and making my own systems would work too. But with a plugin system it makes it easy to share creations in a plugin marketplace. 

I don't know how hard this will be to implement as I am not that familiar with the projects structure. But if you would be able to pull it off it would resolve a lot of posted issues as people could just make and share their own solutions. 

Vote on this issue by adding a 👍 reaction.
If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by KillyMXI** [comment]
Seems related: #146

**Comment by veler** [comment]
Duplicated with #146
