### ISSUE TITLE
"Language - Same as Microsoft Windows" selects locale, not UI language

### ISSUE THREAD

**Issue by KillyMXI** [veler/DevToys#193]
**To Reproduce**

1. Have Windows 10 Pro with UI language different from locale (date/number formats etc);
2. Fresh-install the app or choose Language - Same as Microsoft Windows and restart the app;
3. The app chooses language based on locale, not UI language.

**Expected behavior**

The app should use the language that is consistent with the OS.
Locale is only used for region-specific things like date/number format.

**Configuration (please complete the following information):**

 - OS & Version: Windows 10 Pro 20H2
 - Theme: Dark
 - DevToys app version: 1.0.0.0

**Comment by HellGate94** [comment]
same issue here using these settings: ![settings](https://i.imgur.com/6efDasx.png)
