### ISSUE TITLE
Why Devtoys requires a microsoft account for installing?

### ISSUE THREAD

**Issue by pr4dy** [veler/DevToys#207]
### Description

Actually I am using a local account in my windows machine. When acquiring Devtoys with winget, it throws an error `Verifying/Requesting package acquisition failed: no store account found`.

### Steps To Reproduce

1. Use a local account
2. try winget install DevToys

### Expected behavior

Maybe packaging in the winget repo rather than msstore might help. 

### DevToys Version

-

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/92441536/150668391-e4760a18-8f9a-4875-b1c5-00b95824e0a7.png)

**Comment by oxygen-dioxide** [comment]
you can try https://github.com/oxygen-dioxide/Zhihu-UWP/releases/download/v1/DevToys_1.0.0.0.Msixbundle

**Comment by pr4dy** [comment]
Just found that I can install directly from microsoft store. I think its only issue with winget or maybe I'm wrong.

**Comment by jefftimlin** [comment]
+1 for a non-MS store version. Our IT dept doesn't allow using the MS store and it would be great if this was available in some other way.

**Comment by turkerdev** [comment]
MS is just a mess, there should be an alternative for non MS store. I tinkered the config files to disable downloading things from Microsoft network, especially automatic windows updates, and this makes me unable to download things MS store too

**Comment by veler** [comment]
We made a PR here that should allow WinGet to install DevToys without requiring a Microsoft account: https://github.com/microsoft/winget-pkgs/pull/43996/files

**Comment by veler** [comment]
Hello,
Thanks to @rlm96 , DevToys is now available on Chocolatey. This isn't WinGet (we're facing challenges with this one), but it may help unblocking you. Would you be able to give it a try, please?

See: https://github.com/veler/DevToys#chocolatey

Thank you !

**Comment by turkerdev** [comment]
Thank you, it does work!

**Comment by veler** [comment]
Hurray! Thanks for the feedback!
