### ISSUE TITLE
SMTP Settings tester

### ISSUE THREAD

**Issue by BrnPer** [veler/DevToys#209]
Hi @veler 

First of all thanks for this amazing project. It's really very useful!
I would like to suggest a feature... a SMTP settings tester.

Sometimes I need to see if a SMTP settings are valid. And to test that I create a simple console app and do the test. But I think that would be a awesome feature for this App.

What do you think?

I would enjoy to contribute to this project.

**Comment by veler** [comment]
Hello,

Thanks for sharing this suggestion.
As for now, DevToys is a fully offline app and we do not want to add any functionality that would require an internet connection.
We have an idea for countering this though: make the app extensible so the main app would work offline, and 3rd part extension could allow to use internet or else. But this won't be done before v2.0, for which we have no idea when we will work on it (perhaps in a year or two?...).
Thank you :)

**Comment by veler** [comment]
Note to myself: this issue depends on #146

**Comment by veler** [comment]
Not planned in DevToys 2.0
