### ISSUE TITLE
Add code snippets or file sharing tools

### ISSUE THREAD

**Issue by g5nius** [veler/DevToys#211]
### What's the Problem?

Sometimes we need to share some brief code snippets or transfer files with others, it will be very useful if there's a transfer tools.

### Solution/Idea

I used to use a [website](https://cowtransfer.com) to transfer files, but i have no idear how to embed it to DevToys.

### Alternatives

I have no idear.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by jwfxpr** [comment]
This feature would require the internet capability for the app, and is therefore probably out of scope for DevToys features.
