### ISSUE TITLE
Color Tools

### ISSUE THREAD

**Issue by arantawi** [veler/DevToys#212]
Hi and thanks for the nice and really useful tool.

I hope you can add Color tools such as:

1- Color picker tool.
2- Convert color values (RGB, HTML, CMYK, and HVS).
3- Choose color from palettes.
4- Gradient designer.

All the best,
Adeeb Rantawi

**Comment by xeonmc** [comment]
Would be a good idea to be included as a subset under functionality defined by #93

**Comment by ChristAsselin** [comment]
Verifying contrast ratio between 2 colors could be a nice addition. https://contrast-ratio.com/
