### ISSUE TITLE
You didn't use electron, I commend you!

### ISSUE THREAD

**Issue by jmorgannz** [veler/DevToys#220]
### What's the Problem?

Sorry for abusing the feature request system; but I really felt like this needed saying.  
You could have easily done with many other projects have done for this type of app, and use electron as a base.  
Instead, you have opted for a fast, trim, native experience - this is an excellent decision and I congratulate you for it.  

### Solution/Idea

-

### Alternatives

-

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
![image](https://user-images.githubusercontent.com/3747805/150705681-c1c7375b-8669-45b3-8ba1-b6c25feb1faf.png)

So much hate for native app nowadays 😊
