### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by guyguy2** [veler/DevToys#221]
### Solution/Idea

So nice! Thanks so much for making and releasing this

### Alternatives

So nice! Thanks so much for making and releasing this

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
You're welcome!
