### ISSUE TITLE
Tab and Line Break Character Cleanup Tool

### ISSUE THREAD

**Issue by xeonmc** [veler/DevToys#226]
Some code editors has an auto-cleanup feature when you save the file that does things like removing hanging whitespaces etc, but it would be nice to be able to use it in a standalone tool for snippets without having the save the entire file. 

Perhaps with dropdown options to choose how many whitespaces to convert a tab character into, rules for successive line breaks, whether to remove hanging whitespaces etc. it should be an input-output model with the text diff highlighted

**Comment by PatrickDRusk** [comment]
Resolving mixed Windows/Unix line breaks would fit in great with this!

**Comment by veler** [comment]
Duplicated with #160
