### ISSUE TITLE
Add a terminal where we can execute DevToys functions

### ISSUE THREAD

**Issue by adrianogpena** [veler/DevToys#227]
### Solution/Idea

I think it would be great if we could execute commands like Converters, Formatters and Text Diff on the terminal, using a text file insted of pasting the text. Something like this:

$ dtoy --convert --toJson file.yaml
$ dtoy --convert --toYaml file.json
$ dtoy --format --json file.json
$ dtoy --diff file_1.txt file_2.txt

And the output would be a new file.

This is not a necessity, but I like to execute this kind of commands on the terminal, and I think it is better to add the terminal now than when there is a lot of new funtions on DevToys.

### Alternatives

If the terminal commnands are not possible, I think at least we could use files on the input instead of only text by copy and paste.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers use files on the inputs | Must |
| This proposal will allow developers execute the commands on a terminal | Should |

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by AmiK2001** [comment]
In such cases, I think it would be better to use the DevToys tools both as a CLI and through the use of the internal DevToys API.

**Comment by veler** [comment]
Done in DevToys 2.0
