### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [veler/DevToys#228]
### What's the Problem?

It is not any type of problem.

### Solution/Idea

This project is currently missing the **Code of Conduct**. If you have any plan on adding that then I would be more than glad to do that for you by adding a PR for that. Please let me know what do you think about that.

### Alternatives

According to Google:

> A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

It would help you to define the exact standard you want to engage with the community regarding this project.

### Priorities

Low

### DevToys Version

Not necessary

### Comments

No additional comment is required for this issue.

**Comment by Vexxell** [comment]
Can we close this issue since it has already been resolved? Thanks!
