### ISSUE TITLE
[Suggestion or Feature Request or Question] Moving away from MS Visual Studio?

### ISSUE THREAD

**Issue by Andret2344** [veler/DevToys#229]
When I was about to start working on #195, I did the things I do every time. Opened the IDE, cloned repository to a new project and wait till it download everything, sync and do the initial checking. But It didn't. After opening the project, the sync initially failed. Then I went to the proper section of README to get the knowledge of setting the project up. That was really negative surprise, when I read the steps require me to use the Visual Studio. 

Just to clarify, Visual Studio is probably not as bad as I think, I just hate Micro$oft's products by default. 

The initial build failed for me, because I didn't use VS. I'm using full [JetBrains](https://jetbrains.com/) pack, so at my first try I cloned the repository to [JetBrains Rider](https://www.jetbrains.com/rider/), and it was unable to build the project. Ok, I installed the Tools via VS Installer and then the project was successfully built. Let's say it's my fault I didn't have them installed. I also imported config, as the instruction says, so no errors in IDE are present. But when I trued to run it, it spectacularly felt off the bike. Because I was working only on internationalization, I decided I will change texts in Rider, but will open the project via VS to check if everything is making sense. Committing and pushing was also done via Rider. But having 2 IDEs, one to code, the other one to run is not something good overall.

Java has gradle/maven, what makes it working the exactly same way in any IDE (JetBrains IntelliJ IDEA, eclipse, NetBeans) or in command line. 

JavaScript has the Node.js that is executed by any IDE or command line.

Is something analogical possible in this project? I'm not familiar with C# so cannot truly understand what's wrong with the build.
![image](https://user-images.githubusercontent.com/40674613/150794920-e2719473-98f8-44bf-ac60-dc1c79b71b17.png)

The reason why I prefer JetBrains Rider is something no other IDE have. The best code analysis: 
![image](https://user-images.githubusercontent.com/40674613/150795321-9040e9b1-c13a-421b-8d38-cbea6c3dc93a.png)
![image](https://user-images.githubusercontent.com/40674613/150795441-33279f48-710f-4a67-8aab-c60da4d72533.png)
![image](https://user-images.githubusercontent.com/40674613/150796210-aee4ebb4-cd74-4e6a-91ff-183ec319ed28.png)

Those makes the code even better and cleaner.

**Comment by celluj34** [comment]
Nobody's going to take you seriously if you keep using `Micro$oft`. This isn't the 90's.

**Comment by veler** [comment]
Hello,

Thank you for your feedback. I believe some of these issues you're facing is due to the fact that DevToys is a UWP app and that this platform isn't well supported by Rider. 🤔

**Comment by veler** [comment]
Rider is supported with DevToys 2.0. The issue was indeed Rider not supporting UWP.
