### ISSUE TITLE
Sort lines of text alphabetically

### ISSUE THREAD

**Issue by phytemit** [veler/DevToys#232]
### What's the Problem?

Sort lines of text alphabetically

### Solution/Idea

Sort lines of text alphabetically

### Alternatives

Sort lines of text alphabetically

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by RicardoNiepel** [comment]
I would love to see this - maybe we should make the Feature Request more general?

Just comes to my mind:
* Alphabetize + reverse order
* Alphabetize list by last word/name + reverse order
* Remove duplicates 
* Reverse list
* randomize

**Comment by celluj34** [comment]
I use some of these tools semi-regularly: https://alphabetizer.flap.tv/

**Comment by micahmo** [comment]
How would we feel about sticking this alongside the existing `StringUtiltiies`? 

https://github.com/veler/DevToys/assets/7417301/9e31476f-dd56-4e01-8edf-d6b150d4d3b1

**Comment by veler** [comment]
That's what I had in mind. I love this video by the way! :D Are you cooking anything you want to push to this repository?

**Comment by micahmo** [comment]
> That's what I had in mind. I love this video by the way! :D Are you cooking anything you want to push to this repository?

I'm glad you asked! 😉 #835
