### ISSUE TITLE
DevToys icon is too close to Windows Terminal icon

### ISSUE THREAD

**Issue by veler** [veler/DevToys#238]
### Description

We didn't realize it beforehand, but it appears that Windows Terminal's icon is under CC BY-ND 4.0 license. https://creativecommons.org/licenses/by-nd/4.0/

This license prevents us from "remixing" Windows Terminal icon. While we made the DevToys icon from scratch, we obviously got inspired by Windows Terminal's one, and apparently too much inspired.

We need to change the icon ASAP to avoid violating the license.

### Expected behavior

We need to change the icon ASAP to avoid violating the license.

### DevToys Version

1.0.0.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/3747805/150851601-f948a793-c694-4463-a8be-f038eb31c424.png)

**Comment by Yopler** [comment]
Hi 🖐
I was looking at this amazing repo. And see your issue. 
I got and idea concerning your logo.
![image](https://user-images.githubusercontent.com/45144437/150959476-075c1035-b71a-48e5-aeb3-9357f36641e0.png)
Of course it is not perfect and need some more work, but it can give you some ideas.

Hope it will help you

**Comment by vladimirkosolapov** [comment]
I played with the shape and color a bit, so that there was no overlap with the icons of Microsoft products. I haven't seen their apps use a similar design (elements placement) yet, so there shouldn't be a problem with the license.
![preview](https://user-images.githubusercontent.com/34649010/150966292-e5557566-4164-4389-8db0-7695a8dfab5c.png)

**Comment by KillyMXI** [comment]
DevToys in current shape have nothing to do with tabs though. And three stripes have a strong association with tabs, even if you move them down.
I think `</>` has a strong association with HTML, XML, while DevToys haven't.

I'd look for something that has an association with keywords "many", "tool", "toy".

**Comment by xeonmc** [comment]
A swiss army knife but the tools unfolding from it are code-associated symbols and icons

**Comment by xeonmc** [comment]
Or more simply just an open toolbox with symbolic tools inside

**Comment by veler** [comment]
Hi everyone,

Thank you for your suggestions.

We drafted some new icons and verified that they're not violating the license anymore. We tried to keep it as close as possible from the original one though.

We'd like to keep the `</>` since it's a universal symbol recognized by developers.

Can you please vote for your favorite?

![image](https://user-images.githubusercontent.com/3747805/151213890-5a040701-2a27-4928-bbdb-bfae43af6cfe.png)

# For A, react 🚀

# For B, react ❤️

Thank you !

**Comment by Yopler** [comment]
The circle (Top right on A and top left on B) that represent the "close window", "reduce window" , ... (not sure of the traduction here). I feel like this circle are looking more like MacOs (even if in macos it's on the left) than windows. In others issues (#156 ), you put forward the fact that this project is for Windows. 
I don't know if my point here make sense for you.

Sorry for my English 😅
