### ISSUE TITLE
Regex multiline bug

### ISSUE THREAD

**Issue by lsciarappa** [veler/DevToys#242]
### Description

The "multiline" option in the regex tester appears not to work.

### Steps To Reproduce

1. Go to "Regex Tester".
2. Select "Multliline" under options.
3. Enter the regex '^a' (sans single quotes).
4. Add these two lines to the "Text" box in either order, sans single quotes: 'a', 'b'.
5. It should match the 'a' in both cases, but in fact it only does when the 'a' is first.
6. It can also get confused after performing the above examples, but the way in which it does so is harder to describe. It seemingly starts accepting and rejecting things randomly. This is stateful, in that restarting the app seemingly fixes it. This is harder to explain how to reproduce though.

### Expected behavior

The ^ in a regex should match any beginning of a line, not just the beginning.

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

### Relevant Assets/Logs

![Screenshot 2022-01-24 173101](https://user-images.githubusercontent.com/4780221/150875985-901650c8-306e-49ae-b003-a030b5823ca1.png)

**Comment by mah-sim** [comment]
It's not only about '^', but also '$'
![image](https://github.com/veler/DevToys/assets/56928799/f87c595d-7c58-4e83-ad57-52869a3a8e7b)
Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2
