### ISSUE TITLE
JsonHelper.IsValid is not matching some JSON structures

### ISSUE THREAD

**Issue by youkai95** [veler/DevToys#243]
### Description

The conditional in JSON validation helper method is rejecting some strings that should be correct JSON structures. Besides objects and arrays, a single base value as a string, number or null, are also valid JSON serialized text.
The solution could be changing this conditional or maybe removing it. I am leaving this issue here to discuss a solution where every valid JSON is accepted.
```
            if ((input.StartsWith("{") && input.EndsWith("}")) //For object
                || (input.StartsWith("[") && input.EndsWith("]"))) //For array
```

### Expected behavior

Any of the following JSON should be accepted:
`"a json value"`
`6600`
`null`

### DevToys Version

Current dev version

### Relevant Assets/Logs

None

**Comment by gyurisc** [comment]
I would like to fix this one, please! Not sure what is the correct way of getting this assigned to me.

**Comment by youkai95** [comment]
> I would like to fix this one, please! Not sure what is the correct way of getting this assigned to me.

Just submmit a pull request with your fix to be reviewed. The project managers will accept it or leave some comments about how to improve it 😉
