### ISSUE TITLE
SOLID suggerence for tools

### ISSUE THREAD

**Issue by youkai95** [veler/DevToys#247]
## General idea
I would like to suggest a rewrite of some tools to improve the extensibility and re-usability of the features. I have never worked with UWP before, so I am not very sure about how could dependency injection be configured and used on the view models. I see there are some abstractions injected so i suppose that should be easy to configure for any custom class.

First of all keep into consideration that my suggest would bring some major changes at the view models. Also, at the moment I still have some abstract points without a clear solution.

## My current solution
I will use `JsonYamlToolViewModel` as example:

1. We will need to introduce the concept of 'Services' (or any other way to call it) as the layer where our business code runs. 
2. Move the code usually contained in `TreatQueueAsync` method into the 'services'.
3. It is possible that some changes in the view model could be needed.

For the current example we could use the following interface as the base for any generator-like service.
```
interface IGeneratorService
{
    object Read(string input);
    string Write(object _object);
}
```
Later, we could build other interfaces for different purposes as:
```
interface IIndentedOutput
{
    Indentation Indentation { get; set; }
    # ... here could be any other Indentation related feature
}
interface IConfigurableGenerator : IIndentedOutput # this is wrong, but I will use it as example
{
    void Configure(Action<IConfigurableGenerator> configAction); # here some type capable of collecting the possible configs is needed
}
```
Then we could start building our services once all interfaces are arranged. In example:
```
class JsonConverterService : IGeneratorService, IConfigurableGenerator , etc...
```
For this particular case of generation, the idea is the same used in the current code: transform the string from a defined format into a language object then transform it back to the output format. You could notice that I am not using any `JsonToYaml` like service, so to get this result we could use another service on top of the `Converters`. I will write all the snippet for your consideration:
```
    interface IServiceContainer<T>
    {
        Dictionary<T, IGeneratorService> Services { get; }

        bool TryConvert(string input, out string output, T inputLang, T outputLang);
    }
```
```
    class ServiceTypeAttribute : Attribute
    {
        public int ServiceId { get; set; }
        public ServiceTypeAttribute(int _name)
        {
            ServiceId = _name;
        }
    }
```
```
    class ConverterService : IServiceContainer<GeneratorLanguages>
    {
        private readonly Lazy<Dictionary<GeneratorLanguages, IGeneratorService>> _lazyServices;
        public Dictionary<GeneratorLanguages, IGeneratorService> Services => _lazyServices.Value;

        public ConverterService()
        {
            _lazyServices = new Lazy<Dictionary<GeneratorLanguages, IGeneratorService>>(Initialize);
        }


        public bool TryConvert(string input, out string output, GeneratorLanguages inputLang, GeneratorLanguages outputLang)
        {
            if(!(Services.ContainsKey(inputLang) && Services.ContainsKey(outputLang)) ||
                string.IsNullOrWhiteSpace(input))
            {
                output = string.Empty;
                return false;
            }
            var generic = Services[inputLang].Read(input);
            output = Services[outputLang].Write(generic);
            return true;
        }

        public Dictionary<GeneratorLanguages, IGeneratorService> Initialize()
        {
            var temp = new Dictionary<GeneratorLanguages, IGeneratorService>();
            foreach (var type in Assembly.GetExecutingAssembly().DefinedTypes.Where(t => t.GetCustomAttribute<ServiceTypeAttribute>() is not null && t.GetInterface(nameof(IGeneratorService)) is not null))
            {
                var serviceAttribute = type.GetCustomAttribute<ServiceTypeAttribute>();
                var service = Activator.CreateInstance(type) as IGeneratorService;
                if(Enum.TryParse<GeneratorLanguages>(serviceAttribute.ServiceId.ToString(), out var lang))
                {
                    temp.Add(lang, service);
                }
            }
            return temp;
        }
    }
```
It is not hard to see some holes in this design. It still need to be sharped, as I said at the begging there are some questions without answer. The `Attribute` could be worked out for a cleaner solution. I am using an `IGeneratorService` in the container but how could I configure services without casting? Could this design be generalized somehow to be used with others services (as Encoders)? And I am sure other fissures could be found... Also the classes and interfaces names could be better xD
## Pros 

- Easy incorporation of new serializers/generators/encoders without modifying the current code
- An easy pattern to follow for anyone who decide to add some features
- In general, a more SOLID code

## Conclusions
I will like to do this enhancement if you decide to take it. Before I forget, this would bring changes to the view models. It is possible that some properties/fields needs to be changed. Following with the previous example, these fields should be discarded:
```
        internal const string JsonToYaml = nameof(JsonToYaml);
        internal const string YamlToJson = nameof(YamlToJson);
        private const string TwoSpaceIndentation = "TwoSpaces";
        private const string FourSpaceIndentation = "FourSpaces";
```
Replaced with `GeneratorLanguages` (which I did not included lol) and `Indentation` enums.
Sorry for having to post everything like this here and not through a pull request but I still have not installed VS22, and I am using VS Code to somehow work with this project in net6.0.

**Comment by veler** [comment]
Thanks for the suggestion and sorry for the very late reply. 
While we looked at the suggestions a year ago and studied it, we decided to use a different approach in DevToys 2.0. Here is a [work in progress] sample: https://github.com/veler/DevToys/blob/dev/2.0/src/app/dev/DevToys.Tools/Settings/SettingsGuiTool.cs

Closing for now.
