### ISSUE TITLE
Cannot install on systems with Administrative restrictions

### ISSUE THREAD

**Issue by jmoleiro** [veler/DevToys#252]
### Description

Since my computer has administrative restrictions, I've been following the instructions and installed the certifcate under **Trusted Root Certification Authorities**, then i executed

`
Add-AppPackage -path "DevToys.Startup_1.0.1.0_x86_x64_arm64.msixbundle"
`

But i get this error

```
Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. 
error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
NOTE: For additional information, look for [ActivityId] 3a09a8c8-11fa-0002-5176-0a3afa11d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 3a09a8c8-11fa-0002-5176-0a3afa11d801
At line:1 char:1
+ Add-AppPackage -path "DevToys.Startup_1.0.1.0_x86_x64_arm64.msixbundl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\userr...rm64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

I've been trying to add the root certificate to **Third-Party Root Certification Authorities**, **Trusted Publishers** and to **Intermediate Certification Authorities** but i get the sme error.

There's any workaround for this problem?

Regards

J

### Expected behavior

I expected that the app woukld install after installing the certificate

### DevToys Version

1.0.1.0

### Relevant Assets/Logs

```
Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. 
error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
NOTE: For additional information, look for [ActivityId] 3a09a8c8-11fa-0002-5176-0a3afa11d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 3a09a8c8-11fa-0002-5176-0a3afa11d801
At line:1 char:1
+ Add-AppPackage -path "DevToys.Startup_1.0.1.0_x86_x64_arm64.msixbundl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\userr...rm64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by ABAG603** [comment]
Same thing when trying to install via AppInstaller
![image](https://user-images.githubusercontent.com/68913275/151321885-e2aa7f08-3b6d-4b3d-890e-0cd93dc1511a.png)

**Comment by veler** [comment]
Hello,
Thanks to @rlm96 , DevToys is now available on Chocolatey. Would you be able to give it a try and see if the app can be installed this way on your machine, please? :)

See: https://github.com/veler/DevToys#chocolatey

Thank you !
