### ISSUE TITLE
Allow editing numbers in the output fields of Number Base Converter

### ISSUE THREAD

**Issue by xeonmc** [veler/DevToys#256]
### What's the Problem?

the current input -> output UI layout is great for the use case of having an unknown string of numbers and wanting to find out in which number base does it have a special pattern, by going through each of the options in the dropdown

However, if I already know what base my number is in, it is much faster if I could just click on one of the output fields and enter it there and have the other fields update automatically, including the input field. 

This is also useful for if I want to alter the pattern of numbers after finding the right source base using the tool.

Example: 

1. I found a string "157255" somewhere representing a magic number. 
2. I put it into the converter and go through the options, and find that if "157255" is in octal, then it will say "DEAD" in hexadecimal. 
3. Now I'm wondering what "DEED" would look like in the original octal source, so naturally I click on the hexadecimal output field to change the "A" into an "E"
4. Oops, I can't edit the output field as the app is currently. So instead I have to do the following steps:
   1. note and remember that the magic number base is hexadecimal
   2. copy the string "DEAD" from the hex output field (the string could've been long and thus infeasible to re-type by hand
   3. recall from experience that I need to change the dropdown first before pasting, otherwise it gets messed up (this auto-converting behaviour is good, it only becomes awkward in an in-place reconversion workaround like this use case)
   4. change the dropdown to hex
   5. paste the copied string
   6. change the letter "A" into "E"
  
Contrast that with doing an in-place edit of highlighting "A" and then pressing E, this is quite cumbersome and the very user-friendly design of the dropdown-autoconvert behaviour ended up getting in the way.

### Solution/Idea

allow in-place edits in the output fields

**Comment by xeonmc** [comment]
Also other minor Number Base Converter improvements that doesn't really warrant their own issues individually:

* Add labels "(Base-16)", "(Base-2)" etc in the output field labels
* Add an "Other Number Bases" collapsible section for different big/little endian types (maybe in the future can include signed/unsigned, perhaps merge a subset of the suggestions in #182 or #223 ).
* Add a "Custom Base __ " Output field in the main section just below Binary, accepting only integers between 1 and 16 inclusive

**Comment by jwfxpr** [comment]
In the collapsible section it would be great to have the RFC 4648 Base16, Base32, and Base64 encodings. Since these don't use `0..9` for the bottom ten digits, they need separate fields to typical `0..Z` schemes.

Ref https://datatracker.ietf.org/doc/html/rfc4648
