### ISSUE TITLE
Offer DevToys as a Chocolatey Package

### ISSUE THREAD

**Issue by beholdenkey** [veler/DevToys#257]
### What's the Problem?

So first and for most awesome application, by the way, having everything in one place is super handy to have all of the tools that I tend to use in one place, and I know many others are in the same boat. So with winget being in preview and requiring the Windows StoreFront to download DevToys, would it be possible to offer DevToys as a Chocolatey package.

### Solution/Idea

Offer DevToys as a chocolatey package. I have some experience with this and would be more than happy to contribute.

**Comment by veler** [comment]
Thank you :)
This ticket is duplicated with #183
