### ISSUE TITLE
Cross-Platform Build for macOS?

### ISSUE THREAD

**Issue by floraxz** [veler/DevToys#262]
### Solution/Idea

Use it on macOS.

### Alternatives

No.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Duplicated with #156
