### ISSUE TITLE
Network/Subnet calculator similar to netmask in apt

### ISSUE THREAD

**Issue by empitesithum** [veler/DevToys#267]
My swiss army knife for subnet calculation is `apt install netmask`  
  
`netmask -c 192.0.0.0:193.0.0.0` will give the output 
```
      192.0.0.0/8
      193.0.0.0/32
```

Some of other features I expect:  

  -s, --standard Output address/netmask pairs  
  -c, --cidr         Output CIDR format address lists  
  -r, --range      Output ip address ranges  
  -b, --binary     Output address/netmask pairs in binary  

I'm on windows. I need this feature in a more convenient way through DevToys.

**Comment by veler** [comment]
Duplicate with #184
