### ISSUE TITLE
Spell Checker

### ISSUE THREAD

**Issue by MrJacquers** [veler/DevToys#268]
### What's the Problem?

Firstly, thanks for this utility, I can already see it's going to be quite handy :)

### Solution/Idea

My feature suggestion is a spell checker in the Text section. It would probably need to be able to load a dictionary and be able to add custom words.

### Alternatives

Use Google or Word?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by youkai95** [comment]
This would be great, however this feature would request more than a dictionary... To code a reliable solution, NLP knowledge will be needed.

**Comment by Jacques-eMediaIT** [comment]
> This would be great, however this feature would request more than a dictionary... To code a reliable solution, NLP knowledge will be needed.

For a grammar checker, sure, but not so much for just a basic spelling check.
