### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by MrJacquers** [veler/DevToys#269]
### What's the Problem?

None

### Solution/Idea

OCR from Image would be pretty cool :) Tesseract is an open source library from Google that could maybe be used for this.

### Alternatives

None

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Khaos66** [comment]
I was looking for this too...

I took a screenshot with Greenshot and want to extract the text now.
In this case I need the content of a Listbox control from which I can't copy the text.

It should be possible to use a screenshot from the clipboard for fast OCR runs

**Comment by MrJacquers** [comment]
> I was looking for this too...
> 
> I took a screenshot with Greenshot and want to extract the text now. In this case I need the content of a Listbox control from which I can't copy the text.
> 
> It should be possible to use a screenshot from the clipboard for fast OCR runs

Greenshot can do ocr, but you have to install some MS Office things to get it to work. https://getgreenshot.org/faq/how-can-i-use-greenshot-for-ocr/

**Comment by Khaos66** [comment]
@MrJacquers Good hit! Thank you <3

**Comment by veler** [comment]
HI,

Microsoft PowerToys can now do that. :) https://learn.microsoft.com/en-us/windows/powertoys/
