### ISSUE TITLE
Case сonverter

### ISSUE THREAD

**Issue by vladimirkosolapov** [veler/DevToys#27]
**Is your feature request related to a problem? Please describe.**
Quite often I have to change the case of text and for this I use online converters. But it's not as fast as using the installed app, and it's also not available when there is no connection.

**Describe the solution you'd like.**
Add a Case converter.

**Additional context.**
An example of such a converter and its features is shown below.
<details>
  <summary>Click to expand</summary>
  <img alt="Example of a converter" src="https://user-images.githubusercontent.com/34649010/136810345-ddb1e331-94e5-495c-a612-8d6d7142734d.png"/>
</details>

**Comment by veler** [comment]
Hi,
Thank you for suggesting this. I really like the idea. We have plan to add a tool that will help with basic strings. See #7 .
I added your ideas to this item and marked your issue as duplicated, therefore.
Thank you again for your suggestion :D
