### ISSUE TITLE
QR Code Generator & Reader

### ISSUE THREAD

**Issue by expikr** [veler/DevToys#270]
would be neat to have the functionality of generating QR codes based on inputs, whether in its own tool or included as part of another tool or as a common "export" widget for all tools.

**Comment by xeonmc** [comment]
Also, an even more urgent usecase need: converter from an image of QR code into content (and vice versa), whether via clipboard screenclip or image file

It's baffling that there is no easy way to read QR codes on windows other than through the actual camera. Putting this converter into the Swiss Army knife toolset is literally a lowhanging nobrainer.

**Comment by Akarinnnnn** [comment]
https://github.com/dlbeer/quirc might be a useful standalone library, and it's licensed under a MIT like license([ISC License](https://github.com/dlbeer/quirc/blob/master/LICENSE))

**Comment by Akarinnnnn** [comment]
And [ZXing.Net](https://github.com/micjahn/ZXing.Net)

**Comment by Joery** [comment]
Would be great to see a QR-code generator added that can generate a QR-code based on text input, and from there export the QR-code as an image.

An option to import a file from clipboard/file upload would be great too to get the contents of a QR-code, for example to get the code needed to setup TOTP 2FA for websites in Bitwarden.

Also see #499 & #527
