### ISSUE TITLE
Number of Characters, Words, Lines, Sentences, and paragraphs in text

### ISSUE THREAD

**Issue by RexRode** [veler/DevToys#273]
Please add a feature to count the number of characters with or without spaces, words, lines, sentences, and paragraphs in text.

**Comment by veler** [comment]
Hi,
It is already available here:

![image](https://user-images.githubusercontent.com/3747805/151279649-d0e1f5e9-cfb8-49b5-9a00-c93c435da7a1.png)

**Comment by RexRode** [comment]
maybe characters without spaces could be added?
Thank you very much,
Peter Burbery

**Comment by veler** [comment]
That could be an addition.
As a workaround for now, you can click "camelCase" or "PascalCase", and it will remove the whitespaces (but also change the case) allow you to see how many characters without space is there.
