### ISSUE TITLE
Make the limit of UUID creation 10000.

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#275]
### Description

While creating a large number of UUIDs, the application will stop responding.
In the output, if the number of UUIDs exceeds 12000, the output will be missing.
To be precise, the data itself can be retrieved, but the display will be blank from line 12109.

### Steps To Reproduce

1. Set value 12112
2. Generate UUIDs

### Expected behavior

Stop creating at 10000 lines of output.

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE / Version 0.0.0.0 | X64 | DEBUG | sqlformatter | e568f0a

### Relevant Assets/Logs

screen shot
![image](https://user-images.githubusercontent.com/2970321/151296947-2415bb97-070f-4f5d-a365-bddd21588192.png)

**Comment by veler** [comment]
Hello,
Thanks for reporting this issue.
Simple curiosity: is there a real scenario that requires to generation 10k+ UUIDs?

**Comment by niyari** [comment]
There are none at this time.
And when they need it, they will use other means.
