### ISSUE TITLE
empty alt="" attribute at Screenshots sections on main page

### ISSUE THREAD

**Issue by zmila** [veler/DevToys#278]
### Description

the Screenshots section display previews of different screenshots, but the img elements are without alt attribute. 
so the user can not hover mouse and understand what the screenshot is about. 

### Expected behavior

just put some short description or name of the screen for each screenshot image inside the alt="" attribute

### DevToys Version

main screen on devtoys.app

### Relevant Assets/Logs

no logs, just UI accessibility defect

**Comment by zmila** [comment]
thank you!

please check the documentation, which attribute is needed, alt= or title=. 
i'm long time away from html standards, didn't remember now.

**Comment by veler** [comment]
Fixed it yesterday :)
