### ISSUE TITLE
XML Formatter

### ISSUE THREAD

**Issue by jatocode** [veler/DevToys#279]
### Solution/Idea

XML Formatter. When debugging all xml is sometimes in one line, hard to read :)

### Alternatives

..

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by veler** [comment]
Duplicate with #74
