### ISSUE TITLE
Replace Text Feature

### ISSUE THREAD

**Issue by Michael2150** [veler/DevToys#280]
Sometimes when typing up some code, I need to replace a certain string with another to refactor the code. Some IDEs support this in some contexts but some I use don't and that has forced me to create a whole project to copy and paste around the text I want to replace etc. This should be easy to implement and it would be better to have it all in this one tool, the "DevToys" tool

**Comment by lgmorand** [comment]
Per pure curiosity, which IDE does not offer the replace feature ?

**Comment by Michael2150** [comment]
> Per pure curiosity, which IDE does not offer the replace feature ?

Not gonna lie it is a very edge case, I've been using an IDE called B4a and B4j to make some applications and they have a rename feature for some things but in some scenarios I've wanted to take a big piece of source code and replace some words with a phrase instead of another word and refactoring wont exactly do that. 

This feature suggestion is for very edge cases, and is not 100% necessary but it is a nice tool to have every now and then. When trying to edit a big piece of text in a certain way.

**Comment by lgmorand** [comment]
thanks for satisfying my curiosity :D

**Comment by xeonmc** [comment]
Would this fit as a sub feature of regex tool?

**Comment by Michael2150** [comment]
> Would this fit as a sub feature of regex tool?

Im not sure thought it could fit under the "Text" section as a "Find/Replace" feature

**Comment by veler** [comment]
Visual Studio, Visual Studio Code, and I believe Rider support complex find and replace through RegEx.
IDE can generally be trusted for not leaking your code base to internet (DevToys goal is exactly this, replacing online website, not providing IDE features). I'd suggest using another local text editor like VS Code if B4j can't do it.
