### ISSUE TITLE
Base64 <> Image Converter

### ISSUE THREAD

**Issue by AppeazeTheCheese** [veler/DevToys#285]
Features:
<ul>
  <li>Support for common image formats (png, jpg, webp, (potentially) gif)</li>
  <li>Display the image in the app immediately after converting from base64 or selecting an image file</li>
  <li>Ability to export the image to a file</li>
  <ul>
    <li>Automatically suggest extension using <code>System.Drawing.ImageFormat</code> or similar method</li>
  </ul>
</ul>

This could be added to the existing Base64 Encoder/Decoder or made into it's own tool. I personally like the idea of it being it's own tool just because it would be easier for the developers to implement, these two features could be developed separately (adding maybe an HTML img tag copy-pasting field that wouldn't make much sense in the other tool), and I think it's simply a more organized approach.

I may work on this myself in my free time or assist whoever starts on it first. Just putting this here as a starting point.

**Comment by xeonmc** [comment]
And PDFs

**Comment by yoshiask** [comment]
I think this should be added to the existing Base64 decoder/encoder. All you'd have to do is allow the decoded data to be saved to a file.

**Comment by kanelp** [comment]
I'd like to see this as well.  Just had a need to convert JPEG and PNG images to Base64 to insert into some JavaScript code.
