### ISSUE TITLE
Estimate Time to Read

### ISSUE THREAD

**Issue by PeterCullenBurbery** [veler/DevToys#287]
Please implement an app similar to WolframAlpha's Word Assistant Web App for Wolfram Alpha Pro Premium Users.
![image](https://user-images.githubusercontent.com/61255136/151451121-5e2b182c-86f1-4013-9eca-776eeb4cf28d.png)
![image](https://user-images.githubusercontent.com/61255136/151451197-35eb2144-b9da-44cf-81dc-9359dfe00339.png)
![image](https://user-images.githubusercontent.com/61255136/151451220-3afd84ed-ba44-4fed-bdc1-6e85c7caaaf3.png)
This would be helpful for estimating how long it will take to read a certain document.
WolframAlpha Pro Premium is a paid service around $12/month.
The assumptions could be changed based on number of words and characters per page.

**Comment by rlm96** [comment]
@veler I can take this one 😀

**Comment by veler** [comment]
Unless it requires to paste the actual text, I feel like it's not very valuable to DevToys.

Also, I think we can now do this for free using Chat GPT or Bing Chat http://bing.com/chat :D

![image](https://user-images.githubusercontent.com/3747805/226087248-95efe9b7-9536-43c0-8e1f-06846b134099.png)
