### ISSUE TITLE
Can set output with sepecified font ?

### ISSUE THREAD

**Issue by Ikki-Dai** [veler/DevToys#290]
### What's the Problem?

such as uuid generate, jwt decode, hash generate

### Solution/Idea

use `cascadia mono` or `cascadia code`

### Alternatives

 it will seems better, and have fixed length in the box

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by yoshiask** [comment]
To expand on this, ideally the user would be able to pick a custom font for all input/output fields.

**Comment by KillyMXI** [comment]
#153
