### ISSUE TITLE
Cron expression to human readable description and back

### ISSUE THREAD

**Issue by filipsky** [veler/DevToys#292]
### Solution/Idea

I would love to have some cron expression to human readable format convertor

something like [this page](https://www.freeformatter.com/cron-expression-generator-quartz.html) does

### Alternatives

nothing

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Cron expression show description | Must |
| Cron expression editor | Could |

**Comment by krynczak** [comment]
It would be great if we could chose between Unix like syntax (5 fields: minute, hour, day of the month, month, day of the week) and other implementation syntax (ie: [aws implementation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions) with 6 fields: minutes, hours, day-of-month, month, day-of-week, year)

**Comment by DotNetInAction** [comment]
> It would be great if we could choose between Unix like syntax (5 fields: minute, hour, day of the month, month, day of the week) and others implementation syntax (ie: [aws implementation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions) with 6 fields: minutes, hours, day-of-month, month, day-of-week, year). I'm not sure there are more implementations though

PR for this tool is now ready. I have built in a feature to switch between 5 and 6 segment Cron
