### ISSUE TITLE
Turn off question about pinning

### ISSUE THREAD

**Issue by Andret2344** [veler/DevToys#293]
### Solution/Idea

Add a possibility to turn off question about pinning to start

### Alternatives

n/a

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Be a switch in settings turning it on and off | Must |
| Add checkbox "Don't ask again" when pinning, what would change the setting | Could |

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by veler** [comment]
Hello,
Thanks for this feedback.
We don't show this dialog on purpose. It's a dialog that Windows prompts, not DevToys itself. We don't have control on it :(
Best I can recommend it to open a feedback on Windows Insider: https://insider.windows.com/en-us/
