### ISSUE TITLE
Regex: Provide better highlight contrast/color

### ISSUE THREAD

**Issue by riverar** [veler/DevToys#32]
It's a bit difficult to see yellow on textbox white, especially when you're trying to distinguish between matches between characters. Would be great if perhaps this was another color (green?) and/or had grid lines.

![image](https://user-images.githubusercontent.com/475132/137075234-54894017-edb6-49c6-a60f-0b44c8d0d034.png)

**Comment by veler** [comment]
Thanks for this feedback :) I will try to find a better color :D

**Comment by veler** [comment]
TODO: Actually, let's use the Accent Color :)
