### ISSUE TITLE
Add a javascript / typescript playground

### ISSUE THREAD

**Issue by jesusgmar** [veler/DevToys#321]
### What's the Problem?

There is no javascript playground

### Solution/Idea

It would be interesting if there was a javascript playground to be able to test expressions and small functions
It could be a screen with two columns, in one an editor to enter code and in the other the result of the execution of that code
More scripting languages could be added in the future

### Alternatives

RunJs, Playcode.io, JSFiddle, CodeSandbox

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Editor and result visualizer | Must |
| Allow to import npm modules | Could |
| Allow to select themes | Could |

### DevToys Version

Versión 1.0.1.0 | X64 | RELEASE | 3f367f1 | 3f367f1

**Comment by togetogejizou** [comment]
DevToys is built in C#. So I imagine the C# playground is the easiest to achieve.

**Comment by pedrohenriquebr** [comment]
> DevToys is built in C#. So I imagine the C# playground is the easiest to achieve.

I agree with you, but we could use an API integration to process the code in JavaScript or maybe TypeScript

**Comment by veler** [comment]
I feel like this should its own standalone app, not a tiny tool part of DevToys.
