### ISSUE TITLE
PNG / JPEG Compressor: Save all button doesn't work

### ISSUE THREAD

**Issue by ZalaPanda** [veler/DevToys#322]
### Description

Nothing happens if I press the **Save all** button. 
> NOTE: The **Save as** button works as expected.

### Steps To Reproduce

1. Go to PNG/JPEG Compressor
2.  Add image
3.  Press the **Save all** button

### Expected behavior

The original image files should be overwritten with the reduced version.

### DevToys Version

1.0.1.0

### Relevant Assets/Logs

Nothing relevant in the [logs.txt](https://github.com/veler/DevToys/files/7978309/logs.txt).  
BTW I can see the reduced version of the image in the `%localappdata%\...\LocalCache` folder.

**Comment by youkai95** [comment]
I am experiencing this issue in Windows 10. It seems related to a folder picker that should open to select where to save the pictures.

In my case that picker never opens and just steps out of the property setter.

**Comment by rlm96** [comment]
Can you give us information about Windows version?

**Comment by youkai95** [comment]
> Could you give us information about your Windows version?

Windows 10 v2004, Build 1904

> If you can, would you please be able to checkout the latest commit and try the app on your machine to see if it works?

I had not tried it in a recent code version and I did it now and it works correctly, I consider this issue is solved in main branch.

**Comment by veler** [comment]
Awesome! Thank you for checking :) I will close the issue.

**Comment by ZalaPanda** [comment]
Thank you very much! You guys are awesome! 😄
