### ISSUE TITLE
Eliminate dependency of a SetVersionTask.dll

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#326]
### Description

SetVersionTask, which is used to perform release builds, uses .NetFramework 3.5.

For this reason, restoring a project in an environment immediately after a clean installation of Windows will fail to restore it correctly and the build will fail.

.NetFramework 3.5 can be added or enabled manually to build correctly.

### Expected behavior

Run init.ps1 in a PowerShell command prompt to restore all the dependencies.

### DevToys Version

Version 1.0.1.0 | X64 | RELEASE | main | f5a0bc9

### Relevant Assets/Logs

Build started...
1>------ Build started: Project: DevToys.Shared, Configuration: Release Any CPU ------
1>DevToys.Shared -> C:\Users\glenda\source\repos\DevToys\bin\Release\AnyCPU\DevToys.Shared\netstandard2.0\DevToys.Shared.dll
2>------ Build started: Project: DevToys.MonacoEditor, Configuration: Release x64 ------
2>C:\Users\glenda\source\repos\DevToys\src\dev\impl\Directory.Build.targets(11,9): error MSB4062: The "SetVersion" task could not be loaded from the assembly C:\Users\glenda\source\repos\DevToys\tools\SetVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by youkai95** [comment]
@veler could that library be updated to a compatible version using netcore/netstandard? It is used just to write the app version before building, so it could be rewritten in case of we could not update it.

**Comment by veler** [comment]
Totally! I don't remember why it uses .Net Framework 3.5. While this dll is adapted for DevToys needs, it's not 100% original from me. Original repository was https://github.com/markheath/SetVersionTask, my version of this dll is here: https://github.com/veler/SetVersionTask

**Comment by youkai95** [comment]
> Totally! I don't remember why it uses .Net Framework 3.5. While this dll is adapted for DevToys needs, it's not 100% original from me. Original repository was https://github.com/markheath/SetVersionTask, my version of this dll is here: https://github.com/veler/SetVersionTask

I leaved a PR in your fork. I tested the lib compiled in netstandard and works fine (at least did its job).
