### ISSUE TITLE
Japanese Translations not showing in Image Converter feature

### ISSUE THREAD

**Issue by hizumiaoba** [veler/DevToys#327]
### Description

Hi, Thanks for adding Japanese translations to this wonderful tool.
But in "Image Converter" feature (maybe other newly added features too), The sentences aren't translated to Japanese yet.
I don't have a development environment, So I can only raise this issue.
Thanks

### Steps To Reproduce

1. Go to "Image Converter"
2. Confirm not showing translated sentences

### Expected behavior

program should show the Japanese translations.

### DevToys Version

Version : 1.0.2.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/56146205/152100823-f6e9c30b-fe41-4430-a901-f5ef921dd226.png)

**Comment by hizumiaoba** [comment]
Sorry for poor English skill :(

**Comment by niyari** [comment]
I'll do it.

**Comment by hizumiaoba** [comment]
Thanks a lot!
了解しました。ありがとうございます。
