### ISSUE TITLE
Exception using Browse Folders (PNG/JPEG Compressor and Image Converter)

### ISSUE THREAD

**Issue by rlm96** [veler/DevToys#336]
### Description

Exception using Browse Folders (**PNG/JPEG Compressor** and **Image Converter** tools) button, the application will break after that.

### Steps To Reproduce

1. Go to **PNG / JPEG Compressor** or **Image converter** tools
2. Click on Browse folders button
3. Close the Select Folder window using Cancel button
4. The app will break

### Expected behavior

The app shouldn´t break.

### DevToys Version

1.0.2.0

### Relevant Assets/Logs

logs.txt is empty

**Comment by veler** [comment]
Good catch, then you! I will investigate it!
