### ISSUE TITLE
Base64 Output Rendering Chokes on UTF-8 BOM

### ISSUE THREAD

**Issue by Silvenga** [veler/DevToys#342]
### Description

When attempting to render a UTF-8 string with a leading BOM encoded in Base64, the output is incorrect.

### Steps To Reproduce

Using the Base64 Decoder, attempt to decode:
```
77u/eyJzZXNzaW9uX2lkIjoiMCIsInZlcnNpb24iOjQsImFwcGxpY2F0aW9uTmFtZSI6IiIsImhhc2giOi0xOTg1MzA1Mjc1NTc2NDkyMTF9
```

Observe the output is corrupt:

![image](https://user-images.githubusercontent.com/2753330/152571944-ab776063-6f30-4c2e-8936-7fc5d25ebc0f.png)

Note that the output is correct when copied using the copy button.

### Expected behavior

The output should render as such:
```
{"session_id":"0","version":4,"applicationName":"","hash":-198530527557649211}
```

Bonus points if the BOM is rendered:

![image](https://user-images.githubusercontent.com/2753330/152572386-976d055a-9707-43e0-b892-31a0e40f27fa.png)

### DevToys Version

Version 1.0.2.0 | X64 | RELEASE | b972462 | b972462

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/8004967/logs.txt)

**Comment by btiteux** [comment]
Oh nice one didn't test with UTF8 with or without BOM 👍 
I will look tomorrow.
Thank you
