### ISSUE TITLE
Error installing MSIXbundle through PowerShell - Win10 20H2

### ISSUE THREAD

**Issue by therealderrickd** [veler/DevToys#344]
### Description

Main page states DevToys has a Prerequisite Windows 10 build 1903+ or later.
My computer has 20H2 (10.0.19042)  (Get-ComputerInfo | select OSVersion)

When running "Add-AppPackage" to install the MSIX manually, I get an error of Add-AppPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied. Windows cannot install package 64360VelerSoftware.DevToys_1.0.2.70_x64__j80j2txgjg9dj because this package is not compatible with the device. The package can only be installed on the following device families: Windows.Xbox

Searching on this reveals, this error is poorly created often by applications that require a newer version of Windows then the MSIXbundle is compatible.  However, while not the latest release, my corporate laptop has version 20H2 which is newer then 1903 which documentation states is required.

Any ideas?

### Steps To Reproduce

1. Install MSIXbundle manually as my corporate device doesn't have MS store
2. Add-AppPackage -path .\64360VelerSoftware.DevToys_1.0.2.70_neutral___j80j2txgjg9dj.Emsixbundle
2. Add-AppxPackage -Path .\64360VelerSoftware.DevToys_1.0.2.70_neutral___j80j2txgjg9dj.Emsixbundle

### Expected behavior

Application to install without failure

### DevToys Version

1.0.2.0

### Relevant Assets/Logs

**Add-AppPackage -path .\64360VelerSoftware.DevToys_1.0.2.70_neutral___j80j2txgjg9dj.Emsixbundle**

Add-AppPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.

Windows cannot install package 64360VelerSoftware.DevToys_1.0.2.70_x64__j80j2txgjg9dj because this package is not

compatible with the device. The package can only be installed on the following device families: Windows.Xbox

NOTE: For additional information, look for [ActivityId] 6f2a5a3d-112d-0002-d0e7-39702d11d801 in the Event Log or use

the command line Get-AppPackageLog -ActivityID 6f2a5a3d-112d-0002-d0e7-39702d11d801

At line:1 char:1

+ Add-AppPackage -path .\64360VelerSoftware.DevToys_1.0.2.70_neutral___ ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (C:\users\xxxxx...9dj.Emsixbundle:String) [Add-AppxPackage], Exception

    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

 

**Add-AppxPackage -Path .\64360VelerSoftware.DevToys_1.0.2.70_neutral___j80j2txgjg9dj.Emsixbundle**

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.

Windows cannot install package 64360VelerSoftware.DevToys_1.0.2.70_x64__j80j2txgjg9dj because this package is not

compatible with the device. The package can only be installed on the following device families: Windows.Xbox

NOTE: For additional information, look for [ActivityId] 6f2a5a3d-112d-0003-0549-e86f2d11d801 in the Event Log or use

the command line Get-AppPackageLog -ActivityID 6f2a5a3d-112d-0003-0549-e86f2d11d801

At line:1 char:1

+ Add-AppxPackage -Path .\64360VelerSoftware.DevToys_1.0.2.70_neutral__ ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (C:\users\xxxxx...9dj.Emsixbundle:String) [Add-AppxPackage], Exception

    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by veler** [comment]
Hello,

Thanks for sharing this. I see that you're using a `.emsixbundle` file. This has been uploaded by mistake (it's a package only compatible with Xbox). Since, we uploaded a new package for Windows that you can find here: https://github.com/veler/DevToys/releases/tag/v1.0.2.0
It's a `.msixbundle` file. Using `Add-AppxPackage` command like you did with this file should work.

Please let me know if it resolves the problem or not. :)
Thanks!

**Comment by therealderrickd** [comment]
Thanks @veler.  That solved the issue, installed without issue this morning.
