### ISSUE TITLE
What is Italian Chinese?

### ISSUE THREAD

**Issue by xeonmc** [veler/DevToys#347]
![image](https://user-images.githubusercontent.com/77922942/152628009-ad25f9f9-526b-4971-b761-957fe42d5f68.png)

**Comment by veler** [comment]
It's a typo 🤦

It won't be there in the next update, since this notification changes every time.

![image](https://user-images.githubusercontent.com/3747805/152629396-a71979b2-d9c4-44d2-928e-155e402a1203.png)
