### ISSUE TITLE
QR Code Reader

### ISSUE THREAD

**Issue by kotx** [veler/DevToys#349]
### Solution/Idea

Read QR codes from file or screen.

### Alternatives

ShareX has a utility for this. 

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Read QR codes from file/clipboard | Must |
| Read QR codes from screen | Should |

### Comments

Related #270

**Comment by EduardoDilena** [comment]
+1

**Comment by Andret2344** [comment]
How about additionally adding qr code creator?

**Comment by kotx** [comment]
> How about additionally adding qr code creator?

That's tracked in #270. We can merge them if you want, but they seem to be different enough to have in separate issues.

**Comment by xeonmc** [comment]
> > How about additionally adding qr code creator?
> 
> That's tracked in #270. We can merge them if you want, but they seem to be different enough to have in separate issues.

I think it's worth merging into the same title of "QR Code Generator/Reader" so that it's easier to keep track.

**Comment by xeonmc** [comment]
> @xeonmc Okay, we can merge the issues. Do you want to merge into this one or yours?

whichever one had more eyes on I suppose.

**Comment by kotx** [comment]
> 

Closing in favor of #270 - please add QR code reading in your issue @xeonmc

**Comment by Akarinnnnn** [comment]
https://github.com/dlbeer/quirc might be a useful standalone library, and it's licensed under a MIT like license([ISC License](https://github.com/dlbeer/quirc/blob/master/LICENSE))
