### ISSUE TITLE
Cron evaluator and editor

### ISSUE THREAD

**Issue by pada57** [veler/DevToys#356]
### What's the Problem?

I would like to have in this nice tool feature like crontab guru website
Translation from Cron expression to human readable format 

Another improvement would be to have even an editor to form a Cron expression with month day minutes selections ...

### Solution/Idea

Happy to propose idea and solutions if needed

### Alternatives

Use external libs

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by KillyMXI** [comment]
#292
