### ISSUE TITLE
Meta Shortcut KeyMap Help Feature

### ISSUE THREAD

**Issue by PeterCullenBurbery** [veler/DevToys#370]
I think DevToys or PowerToys would be a cool place to add a way to view shortcuts for applications.
I would like to request a meta shortcut key that displays all shortcut keys for the application that is the current active window and open at the moment.
For example, if I use the meta shortcut key Ctrl+WindowsKey+? (a suggestion because PowerToys maps Shift +WindowsKey+? to Windows Help menu) then if I'm in Chrome, the shortcuts at [https://shortcutworld.com/Chrome/win/Google-Chrome_Shortcuts](url) display.
I would like to request a meta shortcut key for the following applications:

1. File Explorer
2. Google Chrome

I realize this may not be possible but I am trying to determine if there is a way to do so.

**Comment by veler** [comment]
Actually working on a standalone software for that. :)
Invalid for DevToys however.
