### ISSUE TITLE
Regex wrong select

### ISSUE THREAD

**Issue by Morigun** [veler/DevToys#372]
### Description

![image](https://user-images.githubusercontent.com/11372913/153543074-0b916846-eea8-4c26-ae81-804a2ac5dca1.png)
- Default settings

### Steps To Reproduce

The bug repeats as follows:
1) Write a template
2) Write the text
3) Leave the program for some time (1-2 hours) minimized
4) Something is going wrong. Error repeated 2 times

### Expected behavior

![image](https://user-images.githubusercontent.com/11372913/153543048-31d6622d-1673-4955-97b8-39a877c731bb.png)

### DevToys Version

Версия 1.0.2.0 | X64 | RELEASE | b972462 | b972462

### Relevant Assets/Logs

log is empty

**Comment by veler** [comment]
Hello,

Thanks for reporting this. Would you please be able to share the text above from the screenshot? I'm having difficulties writing the Cyrillic characters. :)

Thank you !

**Comment by Morigun** [comment]
I repeated the mistake, for another template with similar text.

![image](https://user-images.githubusercontent.com/11372913/153805726-0a63bfe0-2866-4ed5-949a-f50cccd1fd9f.png)

[20.01.2022 00:00:00] - Test лдо дод
o990r9dasda
[20.01.2022 00:00:00] - Test
sa
[20.01.2022 00:00:00] - Test

[20.01.2022 00:00:00] - Test2
[20.01.2022 00:00:00] - Test32331321313131

[20.01.2022 00:00:00] - Testмвмв

мвыммы

[20.01.2022 00:00:00] - TestП

[20.01.2022 00:00:00] - Testgfndksgsdfjkgnjsdgfsd

123123123123131f4tsdfvjiosjdfi9jf

broken selected =(

**Comment by veler** [comment]
Fixed in #627
