### ISSUE TITLE
IP Calculator

### ISSUE THREAD

**Issue by EduardoDilena** [veler/DevToys#376]
### Solution/Idea

Wish list :

IP calculator...

### Alternatives

something like this:
https://www.iptp.net/es_ES/iptp-tools/ip-calculator/
https://www.iptp.net/en_US/iptp-tools/ip-calculator/

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by youkai95** [comment]
This issue was previously requested at #184
