### ISSUE TITLE
XML Formater error.

### ISSUE THREAD

**Issue by breakerqq** [veler/DevToys#390]
### Description

'wgs1' is an undeclared prefix. Line 4, position 10.

### Expected behavior

The XML format should be formatted normally.

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

### Relevant Assets/Logs
[testxml.txt](https://github.com/veler/DevToys/files/8067783/testxml.txt)

**Comment by jwfxpr** [comment]
Appears to be the same issue as #358.
