### ISSUE TITLE
YAML to JSON wrong error notification

### ISSUE THREAD

**Issue by aborruso** [veler/DevToys#393]
### Description

Hi,
I have error notification, but the input is right

![image](https://user-images.githubusercontent.com/30607/154107989-20b3d80b-eaed-4033-a754-6abc43f2f69c.png)

### Steps To Reproduce

Use this sample code

```
- name: andy
  age: 12
- name: anna
  age: 17
```

### Expected behavior

To have no error

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

### Relevant Assets/Logs

no log related

**Comment by aborruso** [comment]
> @aborruso, could you check this again? If you can reproduce this again, can you try to specify the precise conditions? 😊

I have recorded this video http://youtu.be/ujkXb2K5a0c?hd=1

I just opened devtoys and started writing

**Comment by jwfxpr** [comment]
Huh, I'm getting the same now... not sure what the conditions are 🤔

![image](https://user-images.githubusercontent.com/20788820/154455623-a3a44a7c-f17c-4ac2-8cfc-07dfcd218b1c.png)

**Comment by btiteux** [comment]
Hello,

I tested this issue and the root cause is simple, when you launch DevToys the Conversion Mode is retrieved from the settings, but the default input/output language remains the default one (input json & output yaml).

I will have a pull request to fix this behavior.

**Comment by aborruso** [comment]
> I will have a pull request to fix this behavior.

Thank you very much

**Comment by btiteux** [comment]
Hello,

I just created the pull request to fix this issue. 

Sorry it took me more times (found another bug when you try to convert a json with a root array)

**Comment by aborruso** [comment]
> I just created the pull request to fix this issue.

Thank you very much
