### ISSUE TITLE
Regex Tester - escaped expressions

### ISSUE THREAD

**Issue by KillyMXI** [veler/DevToys#409]
### What's the Problem?

Let's say I have a string containing a regular expression in an escaped form.
Very typical situation when regexes are stored in configuration files.
In order to test such an expression, I will have to manually unescape/escape it, which is very error-prone.

![image](https://user-images.githubusercontent.com/13851064/154490427-392a06cd-1706-4abd-a623-44a41456cfd5.png)

The expression on the screenshot - `a\\b` can mean different things depending on where I've pasted it from. If it came from a string and not a regex literal then I will have to fix it manually before it matches the right thing (`a\b` - `a` followed by a word boundary, as in the first line).

### Solution/Idea

Some way to escape/unescape the expression in place, so I don't have to do it manually.

It might be a pair of buttons near "Paste" button.

Or it might be a second input (edit one and the other is updated accordingly when valid). Although this might be complicated to do right.

### Alternatives

I'm not aware of any tools that do this. It is a common problem.

A separate toy for regex escape/unescape would be too cumbersome to use when I need to test the regex. Although it might make sense in different scenarios.

Some way to stack toys into simple pipelines may be handy to have down the line.

### Comments

Escaped expression may have to include quotes. Because it's important to know what quotes were used in order to unescape the expression.

Example: `"\\\""` and `'\\"'`.

**Comment by jwfxpr** [comment]
So just to clarify. For unescaping, you'd just like a button that collapses every `\\` down to `\`? Or is it something more complex than that?

**Comment by KillyMXI** [comment]
The more I think about it (without doing prototypes and extensive testing) - the more I am confused actually.
There are some things to take into account.

----

If we consider expressions copied from files in languages where strings use different quotes (`"`, `'` `` ` ``) then it can potentially cause issues on some expressions, but I can't come up with a valid example.

Regardless of quotes, it seems fine to unescape both `\\\"` and `\\"` to `\"`.
Just collapsing `\\` will lead to different results.
So it's important to unescape all found escape sequences at once, not just `\\`.

Existing .NET specific methods: [Regex.Escape](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.escape)/[Regex.Unescape](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape)
Some JS implementation (should also work for JSON): <https://github.com/nodef/extra-regexp/tree/master/src>
There are be some differences like syntax for Unicode code points/surrogate pairs.

----

I would be really intimidated to ship this feature myself, honestly. Or spending more time on the research and testing to avoid any corner cases and accidentally broken expressions. And leaving a note on unavoidable limitations.

**Comment by jwfxpr** [comment]
> So it's important to unescape all found escape sequences at once, not just `\\`.

Mmm, I think this is the problem though. There's two different escapes being used: there's the regex escapes, and the escapes from whatever encoding you copied the regex pattern string from. The regex escaping shouldn't be changed, and deconstructing all the various escapes in all the various regex implementations is not trivial... [Ref](https://blog.robertelder.org/regular-expression-character-escaping/), [ref](https://stackoverflow.com/questions/4644847/list-of-all-regex-implementations), [ref](https://www.regular-expressions.info/refflavors.html)

But then, as you've pointed out, it's impossible to predict where any given string was copied from. In many languages, you could escape both `\"` and `\'` regardless of the enclosing quotes, or it may be optional. Quote escapes may be `\'` or `''`, and `\\` may not be an escape at all. YAML, for example, escapes a double quote with `\"` and a single with `''`, but in a normal C/C++/C# string, `''` isn't an escape at all... In fact in C#, prefixing a string literal with `@` switches to an entirely different escaping scheme. And then, does `&quot;` count as an escape or not...?

Honestly, I'm not sure that unescaping strings like this can realistically be automated in a reliable way. 🤔 Like we have right now, each of these escaping schemes would need a dedicated tool, I think. 😊

**Comment by KillyMXI** [comment]
Yep.
So it must be a set of language-specific functions.
As it turns out to be quite complicated to be considered in the context of Regex Tester - I would prefer to see it as one separate toy - "Text - Escape/Unescape" with a dropdown to choose from supported languages.
Languages with multiple grammars can be represented with multiple entries like "C# regular" and "C# @-string".

Speaking of regex escapes vs string escapes: The goal is to remove the layer of string escapes without modifying the regex. So each implementation is only have to be aware of strings grammar of the language. Regex implementation doesn't seem to matter, except for whether it is compatible with the Regex Tester  toy after the unescape.

While there are languages with complicated grammars ("Yet Another Multi-Line"), this can be scaled down to one language and grow from there based on feedback.

Now this issue becomes very connected to
- #160

**Comment by KillyMXI** [comment]
What exactly #983 does about this request to grant the closure of this issue?
I can't see relevant changes from PR description and brief look through the diff.
