### ISSUE TITLE
Settings Group - UX Improvement

### ISSUE THREAD

**Issue by KillyMXI** [veler/DevToys#410]
### What's the Problem?

When options are folded - there is no way to be sure appropriate options are selected:

![image](https://user-images.githubusercontent.com/13851064/154492498-1a5c8c3d-ca54-4697-8fa7-613e5b04cf82.png)

### Solution/Idea

List selected options when the panel is folded, like this:

![image](https://user-images.githubusercontent.com/13851064/154493682-019c623d-cab0-4196-bea2-2097307cc21d.png)

### Alternatives

Typically, regex tester tools show flag letters inline with the regex.
Examples are:

- <https://regexr.com/>
- <https://jex.im/regulex/>

Some options of DevToys' regex tester don't map to regex flags, so that feature alone can't be a solution, something else is needed.

Flags outside of ECMA Script spec might be less known to list just by their characters.

### Comments

This may apply to other toys as well. I didn't check where there are similar folded options panels used.

**Comment by veler** [comment]
That's actually a great idea! I love that! :D Thank you for suggesting it!

**Comment by veler** [comment]
Done in DevToys 2.0 :)
