### ISSUE TITLE
Compressor

### ISSUE THREAD

**Issue by hunterlan** [veler/DevToys#411]
### What's the Problem?

Sometimes, I have to keep source code in JSON file, for the future injecting this code. For now, I have to find website and paste code to website. Also, I have to escape some character to make JSON valid.

### Solution/Idea

Method "Compressor" will compress any source code to one line. Also, it will be nice, if you add option "Escape character".

### Alternatives

[Made for HTML, but also works with CSS and JS](https://www.textfixer.com/html/compress-html-compression.php)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to to compress any code | Could |

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

### Comments

I know, this is non standard situation and probably it's not important to realize it, but I will be happy, if you do it. Thank you for DevToys.

**Comment by KillyMXI** [comment]
Perhaps more common name for tools like this is "Minifier".

**Comment by hunterlan** [comment]
> Perhaps more common name for tools like this is "Minifier".

Can be, final desicion will make developers :D

**Comment by veler** [comment]
Duplicate with #556
