### ISSUE TITLE
Project FontIcon glyph list

### ISSUE THREAD

**Issue by youkai95** [veler/DevToys#416]
I have spent a lot of time trying to find where the glyph codes used by FontIcon tag are. It would be great to include in the `CONTRIBUTING.md` or other place where could be a list to those icons. Please, at least write here where this list is... I am getting crazy trying to match Segoe MDL2 and Fluent System Icons with the ones used on the different views without success...

**Comment by jwfxpr** [comment]
I was looking into this as well, adding some information to `CONTRIBUTING.md` is a great idea. 😊

Segoe Fluent Icons information is here: https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font

The most common icons in the set are in the [Symbol enum](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol?view=winrt-22000). However, there are more symbols than are listed on the page or in the Enum. [Glyph Browser](https://www.microsoft.com/en-us/p/glyph-browser/9wzdncrdlxt7#activetab=pivot:overviewtab) is a handy tool to see the entire glyph set. The Segoe glyphs are in the private use area, starting with hex prefix E7.
