### ISSUE TITLE
UX Improvement Suggestion

### ISSUE THREAD

**Issue by doggy8088** [veler/DevToys#418]
### What's the Problem?

There are more and more tool in the DevToys. I'd like to suggest some UX improvement ideas.

## Search

- Keyboard usage 1: Find **JWT Decoder** tool quickly

    Current: `Ctrl+F`, I type `jwt`, I found only one result, hit `Enter`, I have to hit 3 `Tab` key, then hit `Enter` to open JWT Decoder tool.

    Suggestion: `Ctrl+F`, type `jwt`, hit `Enter`, open **JWT Decoder** tool.

- Keyboard usage 2: Find **Base 64** tool quickly

    Current: `Ctrl+F`, I type `base`, I found 3 results, hit `Arrow-Down`, the dropdown menu disappeared. I have to re-search again.

    > ![image](https://user-images.githubusercontent.com/88981/154847572-e9770a13-8baa-4596-8af2-80ea2aaedbac.png)

    > ![image](https://user-images.githubusercontent.com/88981/154847578-63ff1da6-57e5-456b-a1a7-096e2fcbe07f.png)

    Suggestion:  `Ctrl+F`, I type `base`, I found 3 results, hit `Arrow-Down` twice, hit `Enter` to open **Base 64** tool.

- Keyboard usage 3: Clear search term using Escape key

    Current: `Ctrl+F`, I type `base`, I'd like to clear all keywords in the search box, I have to hit `Ctrl+A` then `Delete`.

    Suggestion: `Ctrl+F`, I type `base`, I'd like to clear all keywords in the search box, I can to hit `Escape` to clear.

- Mouse usage 1: Redefine the `Paste` button

    If I want to press the `Paste` button on the screen, which mostly means I don't want to paste using Keyboard. So I think the best way to paste is **clear all on the textbox below and then paste clipboard text on it**.

    ![image](https://user-images.githubusercontent.com/88981/154847941-8730701a-f25a-49e0-958a-23d17ff0d29f.png)

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish better UX | Must |

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

**Comment by veler** [comment]
This issue is partially fixed in DevToys 2.0:
- [X] Keyboard usage 1: Find JWT Decoder tool quickly
- [X] Keyboard usage 2: Find Base 64 tool quickly
- [ ] Keyboard usage 3: Clear search term using Escape key
- [ ] Mouse usage 1: Redefine the Paste button

**Comment by veler** [comment]
Done in DevToys 2.0
