### ISSUE TITLE
I want the ability to convert between UNIX TIMESTAMP and dates.

### ISSUE THREAD

**Issue by yuma-jp** [veler/DevToys#426]
### What's the Problem?

I would like to have the ability to convert UNIX TIMESTAMP to date and time, and from date and time to UNIX TIMESTAMP.

### Solution/Idea

It is a Japanese service, but I am currently using it and would be very happy if I could do the same thing in a smarter way.

[https://url-c.com/tc/](url)

### Alternatives

None in particular

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Related to #106
