### ISSUE TITLE
text diff tool

### ISSUE THREAD

**Issue by imageslr** [veler/DevToys#432]
### What's the Problem?

Sometimes I need to compare diffs between two text strings.

### Solution/Idea

Feature: diff tool.

### Alternatives

https://tool.chinaz.com/tools/diff

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,

There's already a Text Diff tool :)

![image](https://user-images.githubusercontent.com/3747805/156114388-a134c261-45f4-4965-9223-b69aa90550b8.png)
