### ISSUE TITLE
Timestamp conversion

### ISSUE THREAD

**Issue by raptorsun** [veler/DevToys#435]
### What's the Problem?

It will be useful to have a converter from UNIX timestamp to a human readable date format and vice versa.

### Solution/Idea

We can add a panel to the application similar to [this website](https://www.unixtimestamp.com/). 

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to accomplish timestamp conversion | Should |

**Comment by veler** [comment]
Duplicate with #106
