### ISSUE TITLE
input by file drag and drop

### ISSUE THREAD

**Issue by togetogejizou** [veler/DevToys#438]
### Solution/Idea

The following locations would benefit from the ability to enter content by dragging and dropping files in addition to direct input and pasting.

e.g.

- Converters
  - JSON <> YAML Converter (Input)
- Encoders / Decoders
  - HTML (Input)
- Formatters
  - JSON (Input)
  - SQL (Input)
  - XML (Input)
- Text
  - Text Case Converter and Inspector (String)
  - Regex Tester (Text)
  - Text Diff (Old text, New text)
  - Markdown Preview (Markdown)

* () is an area that accepts drops

### Alternatives

-

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

**Comment by kieronlanning** [comment]
Drag and Drop would be excellent!

**Comment by veler** [comment]
Duplicate with #605
