### ISSUE TITLE
Cut does not work properly

### ISSUE THREAD

**Issue by morning4coffe-dev** [veler/DevToys#448]
### Description

When I was testing the localization update I discovered that the Cut feature in the text box does not work properly.

### Steps To Reproduce

1. Go to any tool with the text box.
2. Write some text to it.
3. Select some text.
4. Right-click it.
5. Hit Cut (or Ctrl+X)
6. Does not work.

### Expected behavior

The selected text should get removed and it should be added to the clipboard.

### DevToys Version

1.0.4.0 | X64 | RELEASE | OS: 22572.1

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/78549750/158082442-402c2d1c-b134-47ac-b961-8c891a8bfc84.png)

**Comment by niyari** [comment]
Would adding it here fix it?

https://github.com/veler/DevToys/blob/232b783ef245c39ed8a16c1bf401e41221a38225/src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs#L625

>         private void TextBox_CuttingToClipboard(TextBox sender, TextControlCuttingToClipboardEventArgs args)
>         {
>             CopyTextBoxSelectionToClipboard();
>             sender.SelectedText = string.Empty;           
>             args.Handled = true; 
>         }
> 

https://github.com/veler/DevToys/blob/232b783ef245c39ed8a16c1bf401e41221a38225/src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs#L642

>        private void RichEditBox_CuttingToClipboard(RichEditBox sender, TextControlCuttingToClipboardEventArgs args)
>         {
>             CopyRichEditBoxSelectionToClipboard();
>             sender.TextDocument.Selection.Cut(); // There has to be a better way.
>             args.Handled = true;
>         }
>
