### ISSUE TITLE
Chocolatey - Latest version not available

### ISSUE THREAD

**Issue by thomhurst** [veler/DevToys#452]
### Description

Despite v1.0.4.0 being out for a couple of days, chocolatey is still showing 1.0.3.0 as the latest version.

```
> choco upgrade devtoys

Chocolatey v0.12.1
Upgrading the following packages:
devtoys
By upgrading, you accept licenses for the packages.
DevToys v1.0.3.0 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
```

### Steps To Reproduce

Open powershell / cmd prompt

Run `choco upgrade devtoys`

### Expected behavior

Version 1.0.4.0 is installed

### DevToys Version

1.0.3.0

### Relevant Assets/Logs

N/A

**Comment by veler** [comment]
Hello,

Thanks for this feedback. We did push the version 1.0.4.0 to Chocolatey, but it's not approved yet by the moderators.
https://community.chocolatey.org/packages/devtoys/1.0.4.0

Hopefully it will be available in the next few hours / days.

**Comment by ludificorpayne** [comment]
Install failed for mine just now, depends on "microsoft.ui.xaml.2.6" which could not be found, ect. winget worked just fine although the version was listed as unknown.

**Comment by veler** [comment]
Hello @thomhurst , the last version (1.0.5.0) is now listed on Chocolatey :)
