### ISSUE TITLE
[feature request ]time convert

### ISSUE THREAD

**Issue by nealhuchn** [veler/DevToys#456]
### What's the Problem?

some times need to convert Unix time  from second or millisecond to calendar time (YYYY-MM-DD hh:mm:ss)  

### Solution/Idea

just add one component for time convert (optinonal format)

### Alternatives

![image](https://user-images.githubusercontent.com/46528545/159115346-de801dd2-2ebb-483a-80b8-1c9ad737c25f.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

version 1.0.4.0 | X64 | RELEASE | 232b783 | 232b783

### Comments

this dev toys help new coders a lot. Thank you author

**Comment by veler** [comment]
Duplicate with #106
