### ISSUE TITLE
Xpath tester

### ISSUE THREAD

**Issue by markaustinws** [veler/DevToys#460]
### What's the Problem?

Would be good to have some form of XPATH testing. 

### Solution/Idea

New tool?

### Alternatives

Online, but some data is sensitive and would prefer a local toolset.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Duplicate with #165
