### ISSUE TITLE
Run smart detection multiple times (i.e. chaining it)

### ISSUE THREAD

**Issue by MattFromGer** [veler/DevToys#462]
### What's the Problem?

For example my clipboard contains a Base64 string of JSON data. Right now, smart detection will decode the Base64, but not in a readable format. In order to get a readable format I have to copy it once again and paste it into the JSON formatter tool.

### Solution/Idea

Would it make sense to run the smart detection multiple times i.e. to post the output of the smart detection once again into the input?

### Alternatives

For this specific problem, an alternative includes a "Format/Beautify" button at the output pane on all en-/decoder tools

**Comment by veler** [comment]
Duplicate with #737
