### ISSUE TITLE
Lorem ipsum generator

### ISSUE THREAD

**Issue by mhsayan** [veler/DevToys#463]
### What's the Problem?

when I'm clearing the text box then it is working fine but after that, there is no such button to **re-generate** the text.

### Solution/Idea

I think a re-generate button will solve this issue

### Alternatives

I can re-generate the text by changing the **Type, Length, or Start** option.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.4.0 | X64 | RELEASE | 232b783 | 232b783

### Comments

This is a great tool for me.

**Comment by niyari** [comment]
Please wait for the next release.
https://github.com/veler/DevToys/pull/413
![image](https://user-images.githubusercontent.com/2970321/160250155-ba57c855-666a-4c5b-90fa-01143677f02b.png)
