### ISSUE TITLE
Checksum/Hash generator doesn't accept empty file/input

### ISSUE THREAD

**Issue by voidMike** [veler/DevToys#469]
### Description

Currently supported checksum algorithms return a valid hash for an empty file.
However, DevToys doesn't seem to accept an empty file and returns no result.

### Steps To Reproduce

1. Go to Checksum Generator
2. Attempt to open/drag/paste an empty file

### Expected behavior

Empty file hash is returned (e.g. MD5 - d41d8cd98f00b204e9800998ecf8427e)

### DevToys Version

Version 1.0.5.0 | X64 | RELEASE | 99757dc | 99757dc

### Relevant Assets/Logs

N/A

**Comment by L1nu5** [comment]
Hi, may I look into this issue?

**Comment by voidMike** [comment]
@L1nu5 I don't think there's anything stopping you from looking into it and making pull requests.

**Comment by L1nu5** [comment]
@voidMike  Thanks, I'll get started!
