### ISSUE TITLE
Add convert Timestamp

### ISSUE THREAD

**Issue by freekkk** [veler/DevToys#475]
### Solution/Idea

Hi guys:
    can you add convert timeStamp feature. Thanks

### Alternatives

use web contert tools

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
We just added a Timestamp converter in version 1.0.5.0, released this morning.
Enjoy :)
