### ISSUE TITLE
Windows Server 2022

### ISSUE THREAD

**Issue by PeterCullenBurbery** [veler/DevToys#486]
DevToys does not work on Windows Server. Please allow for users to install DevToys on Windows Servre on Virtual Machines, for example through Chrome REmote Desktop with Google CLoud.

**Comment by Carterpersall** [comment]
You might need to install the Microsoft VCLibs package beforehand to get the needed dependencies as WIndows Server and LTSC don't grab them automatically. I learned that because you must go through the same process to install winget on Windows server or LTSC

**Comment by masterflitzer** [comment]
@Carterpersall true, afaik winget and many other "modern" store apps work under win server 2022, 2019 not so much sadly

**Comment by Carterpersall** [comment]
I've installed Winget to Windows Server 2019 multiple times. You just need to install the necessary dependency (VCLibs 14) then Winget will install.
