### ISSUE TITLE
UX the result textbox cant expand to fullscreen

### ISSUE THREAD

**Issue by clfsoft** [veler/DevToys#489]
### Description

 I  cant resize the textbox .

### Steps To Reproduce

1. when you decode jwt token,  
1. the result header take the center part of the screen.   
1. and the most important payload part you have to scroll to copy to other tools .  
1.  bug is  I  cant resize the payload textbox .

### Expected behavior

resize any textbox to hilight my concern parts or minimize the others

### DevToys Version

ver 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

### Relevant Assets/Logs

nothing to say

**Comment by pureiboi** [comment]
I'm using the following version.

there is a middle scroll able to resize. i wonder if you're referring to that ?

**DevToys Version**

Version 1.0.11.0 | X64 | RELEASE | 2b57a920 | 2b57a920

![image](https://user-images.githubusercontent.com/17396188/236125967-28539a4d-4bb2-4cd2-a570-889b6e46fb01.png)

![image](https://user-images.githubusercontent.com/17396188/236126012-b348640c-fe31-46f4-a796-78ef0e167b46.png)

**Comment by veler** [comment]
Done in DevToys 2.0 :)
