### ISSUE TITLE
Check automatically for Driver Updates

### ISSUE THREAD

**Issue by PeterCullenBurbery** [veler/DevToys#490]
Please add for a way to check automatically for driver updates, instead of paying for a driver update software.

**Comment by michael-hawker** [comment]
What type of drivers? Isn't Windows doing this automatically?

Even then, this tool is all about offline helpers for dev tasks, checking online for a driver update seems out-of-scope?

**Comment by Carterpersall** [comment]
@RexRode what you are looking for is Snappy Driver Updater Origin([https://www.snappy-driver-installer.org/](url))
It does automatic checking, downloading, and installing, online or offline. All for free with no ads or paid version.
