### ISSUE TITLE
Request for QR code generator or encoder/decoder

### ISSUE THREAD

**Issue by darrylnoakes** [veler/DevToys#499]
### What's the Problem?

I would like a QR code generator. Nothing more.
There are plenty of tools floating around, but it would be nice to have one included in DevToys.

### Solution/Idea

A QR code generator that can generate various formats/versions of QR code. The "normal" type in various sizes with alphanumeric and binary encoding is enough for me. Micro QR Codes would be nice, though, as an additional goal.
A text input, and a copyable image output.
Configurable error-correction levels and such would be good.

A decoder would be great, as well.

There are many standards and other tools, so I will let you decide what you feel is best.

### Alternatives

There are various tools around, but it can be a pain to find one that can do what I want when I simply want to get it done.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to create "normal" QR codes of various sizes in binary encoding | Must |
| This proposal will allow end users to create Micro QR Codes | Should |
| This proposal will allow end users to decode common QR codes | Should |
| Allow configuration of error correction levels and such when generating a QR code | Could |
| Include the capability for generating QR codes in numeric and alphanumeric encodings | Could |

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

### Comments

[Zxing decoder webpage](https://zxing.org/w/decode.jspx) and [scanning library](https://github.com/zxing/zxing).

**Comment by veler** [comment]
#270
