### ISSUE TITLE
Image to Base 64

### ISSUE THREAD

**Issue by nunofilipecosta** [veler/DevToys#500]
### What's the Problem?

As a developer
I want to convert an image into a Base64 string
so that I can mimic the upload of an image into other tools ( Postman, Swagger UI, etc )

### Solution/Idea

Upload the image and convert it into a Base64 string . Copy the text

### Alternatives

Add an image url and converit into a Base64 string

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Duplicate with #285
