### ISSUE TITLE
NaviagtionView与Frame页面包含的内容发生了重叠

### ISSUE THREAD

**Issue by Gaoyifei1011** [veler/DevToys#502]
### Description

NaviagtionView与Frame页面包含的内容发生了重叠
NaviagtionView overlaps with what the Frame page contains

### Steps To Reproduce

1.拖动Devtoys的边界栏到手机屏幕的大小尺寸，也就是长短宽高
1. Drag the boundary bar of Devtoys to the size of the phone screen, that is, the length, shortness, width and height
2.自动地左上角发生了重叠
2. Automatically overlaps in the upper left corner
![image](https://user-images.githubusercontent.com/49179966/164968098-8c30ad7c-dd65-4f8a-a249-6d06aead3095.png)

### Expected behavior

正常情况下左上角不会发生重叠，文字“所有工具”在标题栏的下方
Normally, there is no overlap in the upper left corner, and the text "All Tools" is below the title bar
这个是在点击左侧导航后再关闭就成了期待的样式
This is the style that is expected to be turned off after clicking on the left navigation
![image](https://user-images.githubusercontent.com/49179966/164968122-8686271b-fb4d-4218-8f9a-bd721ac83489.png)

希望得到的修复：应该是和DisplayModeChanged这一事件有关
Hope for a fix: It should be related to the DisplayModeChanged
![image](https://user-images.githubusercontent.com/49179966/164968206-33bbbd85-b588-4b2a-9fd1-f5f74034afde.png)
这是一个参考案例，这个案例是设置标题栏图标和文字区域的位置
This is a reference case for setting the position of the title bar icon and text area
![image](https://user-images.githubusercontent.com/49179966/164968226-62e19aa6-3756-4780-a36f-d6df1ca12df5.png)

### DevToys Version

1.0.6

### Relevant Assets/Logs

我个人认为这只是前端界面的一个逻辑BUG，应该是不需要日志文件的，如果需要我会提供

**Comment by veler** [comment]
Duplicate with #487
