### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by Shak1990** [veler/DevToys#504]
### What's the Problem?

It is really a small thing but a back button will be really great especially when DevToy resizes to a small window/50% size.

I know we have the hamburger menu but in my point of view, it is more intuitive to use the back button especially when I use it with my mouse button shortcut.

### Solution/Idea

Similar to the Settings App back button:

![image](https://user-images.githubusercontent.com/50573759/165317507-10f11d2f-0881-4c1c-a3ae-3c949dff7892.png)

### Alternatives

The need for a back button stems from the need to navigate the app faster and easier, therefore, adding a favorite or most used app category will be a nice addition.

the most used app category can be displayed inside the hamburger menu or in the right space of the app screen.

![image](https://user-images.githubusercontent.com/50573759/165319110-50d14a19-7b3f-46ca-b2a4-ea8c63bf17bf.png)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

**Comment by veler** [comment]
Hello,
Thanks for your feedback.

Back button is something I could indeed add. :)

For the favorite, it is already available: 

![image](https://user-images.githubusercontent.com/3747805/178128821-d74b5a92-8dc8-433b-8c78-13c36c50a906.png)

![image](https://user-images.githubusercontent.com/3747805/178128826-5604b5ad-fd60-4b02-bb39-7224c983721c.png)

The tool then appears at the top of the list:

![image](https://user-images.githubusercontent.com/3747805/178128842-61a42360-0057-4181-bfb3-f1daf90c6f2b.png)

**Comment by Shak1990** [comment]
> Hello, Thanks for your feedback.
> 
> Back button is something I could indeed add. :)
> 
> For the favorite, it is already available:
> 
> ![image](https://user-images.githubusercontent.com/3747805/178128821-d74b5a92-8dc8-433b-8c78-13c36c50a906.png)
> 
> ![image](https://user-images.githubusercontent.com/3747805/178128826-5604b5ad-fd60-4b02-bb39-7224c983721c.png)
> 
> The tool then appears at the top of the list:
> 
> ![image](https://user-images.githubusercontent.com/3747805/178128842-61a42360-0057-4181-bfb3-f1daf90c6f2b.png)

Thanks but maybe you can make the Favorite Categorie clear and readable?
I mean it should have its own Label and all the tools should be tabbed inside it.

**Comment by veler** [comment]
Note to myself:

Non-file design decision:

Having the navigation menu like:

- All Tools
- ---------
- Recent tool 1
- Recent tool 2
- Recent tool 3
- ---------
- Favorites (expanded by default when the app starts)
  - Tool 1
  - Tool 2
- Converters
- Encoders / Decoders
- Formatters
- Generators
- Text
- Graphic
- ---------
- Settings

**Comment by veler** [comment]
Added in 2.0 https://github.com/veler/DevToys/commit/3967a029fe64761c5851cbb5a8a705339375da98
