### ISSUE TITLE
Beatiful screenshots of code

### ISSUE THREAD

**Issue by RodrigoTomeES** [veler/DevToys#506]
### What's the Problem?

Hi,

It would be awesome a functionality like [CodeSnap](https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap) extension of VSCode or [kod.so](kod.so),

Thanks!

### Solution/Idea

Here is an example: https://github.com/kufii/CodeSnap

### Alternatives

[CodeSnap](https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap)
[kod.so](kod.so)

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
I feel like this is out of scope of DevToys.
