### ISSUE TITLE
Issue: Bas64 Encoder/Decoder is not working for .zip files.

### ISSUE THREAD

**Issue by bhuwan1990** [veler/DevToys#508]
### Description

Please look Bas64 Encoder/Decoder is not working for .zip files.

### Steps To Reproduce

Choose .zip file 

### Expected behavior

should be convert like https://base64.guru/converter/encode/file

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

### Relevant Assets/Logs

It's showing this message.
![Screenshot_2](https://user-images.githubusercontent.com/37440900/165907743-5c30741a-1f0f-4c81-93b6-790cdc52d704.png)

**Comment by veler** [comment]
Hello,

Thanks for your feedback. As of today, this is by design. It can only encode / decode text. Only text documents can be opened in this tool.
I admit the UX isn't clear. I will try to improve that :)
