### ISSUE TITLE
Pomodoro (Tomato) Timer

### ISSUE THREAD

**Issue by mickelsonmichael** [veler/DevToys#510]
### What's the Problem?

The [Pomodoro Technique](https://en.wikipedia.org/wiki/Pomodoro_Technique) is a methodology for reducing eye strain and general health by instituting a series of short (generally five minutes) breaks at regular intervals (traditionally 25 minutes). This is often solved using a desk timer or a digital timer, with many websites available to accomplish the task as well.

### Solution/Idea

A simple timer with several features:

- A configurable work duration (default to 25 minutes)
- A configurable break duration (default to 5 minutes)
- A "Start Work" button that starts the timer with the work duration
- A "Start Break" button that starts the timer with the break duration
- An alarm that sounds and/or a notification that displays when a timer expires
  - Bonus points for being able to configure the sound that plays when a timer expires

Functionality should be similar to examples like <https://pomofocus.io/>.

### Alternatives

Web-based timers like <https://pomofocus.io/> and <https://www.toptal.com/project-managers/tomato-timer> are available for free. They are fine tools that have no Ads, but require a connection to the internet to load. It would be preferable to have this in a centralized tool like DevToys where notifications could be handled by the OS rather than the browser and could be operated offline.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Start a "work" timer | Must |
| Start a "break" timer | Must |
| Send an OS notification when a timer expires | Must |
| Starting a timer stops the other time (e.g. starting "work" stops "break") | Must |
| Play a sound when a timer expires | Should |
| Configure the work duration | Could |
| Configure the break duration | Could |
| Configure the sound that plays when a timer expires | Could |

**Comment by veler** [comment]
Seems to be out of scope of DevToys. There are many apps out there to do that.

**Comment by mickelsonmichael** [comment]
> Seems to be out of scope of DevToys. There are many apps out there to do that.

I can understand the scope creep. But "many apps out there that do that" describes most tools in DevToys, does it not? Is the point not to bring these common utities into a centralized location?

**Comment by veler** [comment]
It does. My point, as you seem to have understood, is that a pomodoro timer is something not only useful for developers but for pretty much anyone using a computer. DevToys tries to fit needs of developers mainly, and maybe a tiny dev ops but that's it. :)
