### ISSUE TITLE
.NET Ticks (timestamp) converter

### ISSUE THREAD

**Issue by epeshk** [veler/DevToys#512]
### What's the Problem?

Feature request: .NET Ticks (timestamp) converter, like https://tickstodatetime.azurewebsites.net/

### Solution/Idea

as stated above

### Alternatives

Use website, or C# interactive

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi @epeshk ,

Thanks for your feedback.
There's already a timestamp converter in DevToys. Does it not do what you are expecting?

**Comment by TonyLi2013** [comment]
Hi @veler ,

Current timestamp converter is UNIX timestamp like "1655263430", but what @epeshk expected is .NET timestamp  like "637908602300000000" which is also what I expected, please consider supporting it.

Thanks,

**Comment by veler** [comment]
Oh I see! Thanks for explaining this 😁

**Comment by niyari** [comment]
Difficult to place UI for settings.
![image](https://user-images.githubusercontent.com/2970321/178367098-d0ab35bb-691c-4afd-a4b9-d38eb512b482.png)
![image](https://user-images.githubusercontent.com/2970321/178366989-1535d453-149e-400f-bd4d-f036b61df2e7.png)
The UI is different from other tools, but I think this UI is easy to understand.

**Comment by XXXXXXzmm** [comment]
> Difficult to place UI for settings. ![image](https://user-images.githubusercontent.com/2970321/178367098-d0ab35bb-691c-4afd-a4b9-d38eb512b482.png) ![image](https://user-images.githubusercontent.com/2970321/178366989-1535d453-149e-400f-bd4d-f036b61df2e7.png) The UI is different from other tools, but I think this UI is easy to understand.

Hello, when can I use this new function? I still haven't found any options to switch in the latest version. I think this function is more important to me

**Comment by niyari** [comment]
The input part of Timestamp uses WinUI(muxc:NumberBox).
NumberBox uses Double.
It is unlikely to be changed from Double because it needs to work the same way in various environments.

Converting the NumberBox to ms as it is will result in incorrect calculation results.
For this reason, other methods must be provided.

For example, this is the way to do it.
Prepare a dedicated input field (window will be longer)
Create a dedicated component that "looks exactly the same" as the NumberBox.

**Comment by anthonyhardman** [comment]
I'd be interested in working on this. Would you like the input to be in UTC ticks, or calculated relative to the selected time zone?

**Comment by veler** [comment]
Hi,
@btiteux is currently working on it for DevToys 2.0

**Comment by btiteux** [comment]
Hello, I'm currently migrating the timestamp converter.
I plan to support milliseconds and will see about adding the ticks support.
