### ISSUE TITLE
JSON stringify/unstringify feature

### ISSUE THREAD

**Issue by binaryfog** [veler/DevToys#517]
### What's the Problem?

JSON stringify/unstringify feature

### Solution/Idea

See how they do it here : [Online JSON Tools](https://onlinejsontools.com/unstringify-json)

### Alternatives

Could have a convert the JSON text to a stringified  text and viceversa

### Comments

Thank you very much !

**Comment by veler** [comment]
Hello,

Thanks for your suggestion. There's more or less such a tool already:

![image](https://user-images.githubusercontent.com/3747805/167524660-cb63fd9c-ed34-4d25-9711-d7c36e94d4db.png)

![image](https://user-images.githubusercontent.com/3747805/167524716-fbefd6b2-a403-495d-9e4d-57c0f8773523.png)


Does this corresponds to what you're referring to?
It's not JSON specific, but it can unstringify and stringify something.
