### ISSUE TITLE
Compact mode does not allow changing the window area.

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#524]
### Description

Window size is changed and the The application exits with an exception.

### Steps To Reproduce

1. Launch one of the tools (e.g. Settings).
2. Click on the Keep on Top button.
3. Change the window size.

https://user-images.githubusercontent.com/2970321/169964909-7ac3a49f-06fd-4ba0-8f74-d60d1964bdcd.mp4

### Expected behavior

Even with Keep on Top enabled, the window size can be changed.

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb
Version 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

### Relevant Assets/Logs

no log

**Comment by veler** [comment]
Ugh, that looks like a bug in Windows (I think?). I encountered this issue multiple time with many apps at random times. :-/

**Comment by veler** [comment]
By design
