### ISSUE TITLE
Monaco Editor activation issue

### ISSUE THREAD

**Issue by rounk-ctrl** [veler/DevToys#54]
**Describe the bug**
Sometimes there's no way to activate the textbox.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app
2. Go to any tool without expanding the menu
3. Try to click on a textbox
4. See that it doesn't activate

**Expected behavior**
The textbox to activate

**Configuration (please complete the following information):**
 - OS & Version: Windows 10 21h2
 - Theme: Dark
 - DevToys app version: 0.6.6.0 | X64 | RELEASE | e3b574a | e3b574a

**Comment by veler** [comment]
Hi,
Thanks for reporting this bug.
To add more details to it, I can reproduce it when the app starts with the NavigationView is in Compact mode:
![image](https://user-images.githubusercontent.com/3747805/139594287-748d3d28-5ca6-4062-a030-ec21ff30c46f.png)

When this happens, we can't click the Monaco Editor.
Note that another issue happens (probably linked): when the app starts in this mode, the layout seems wrong. 
Current layout is:
![image](https://user-images.githubusercontent.com/3747805/139594320-f513684e-2210-4872-b98a-4123455a8ce0.png)
But it should be:
![image](https://user-images.githubusercontent.com/3747805/139594332-ad9910d1-e2a7-4810-98ec-969d935c01d9.png)
