### ISSUE TITLE
Can Text compare result area to be full windowed?

### ISSUE THREAD

**Issue by crazypeace** [veler/DevToys#554]
### What's the Problem?

The  Text compare result area is too small

### Solution/Idea

The  Text compare result area can be full windowed

### Alternatives

 full windowed Text compare result area

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

版本 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

### Comments

![ApplicationFrameHost_2022-06-02_07-08-22](https://user-images.githubusercontent.com/665889/171520505-1ec332a7-37ff-45f4-9e39-17e928152610.png)

**Comment by veler** [comment]
I feel like this is something needed in many tools, for example, JSON Formatter. :)
