### ISSUE TITLE
Hash Generator supports binary file

### ISSUE THREAD

**Issue by doggy8088** [veler/DevToys#557]
### What's the Problem?

Hash Generator unable to get hash for a binary file.

### Solution/Idea

Hash Generator should have a binary file support. It's support text file only right now.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

**Comment by veler** [comment]
Hello,
There's a Checksum Generator tool that allows to do this:
![image](https://user-images.githubusercontent.com/3747805/173730348-ce9ce4ed-0541-4629-a613-0daca0c8b219.png)
