### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by BlackRosePetals** [veler/DevToys#561]
### Description

应用安装失败，错误消息: 错误 0x80070005: 从位置 64360VelerSoftware.DevToys_1.0.8.0_neutral_._j80j2txgjg9dj.msixbundle 中打开程序包失败。 (0x80070005)

### Expected behavior

正确安装

### DevToys Version

64360VelerSoftware.DevToys_1.0.8.0_neutral_._j80j2txgjg9dj

### Relevant Assets/Logs

应用安装失败，错误消息: 错误 0x80070005: 从位置 64360VelerSoftware.DevToys_1.0.8.0_neutral_._j80j2txgjg9dj.msixbundle 中打开程序包失败。 (0x80070005)

**Comment by Akarinnnnn** [comment]
> 0x80070005 | E _ ACCESSDENIED | 常规访问被拒绝错误
