### ISSUE TITLE
Add "Clear and paste" button (or change paste to clear by default)

### ISSUE THREAD

**Issue by soumya92** [veler/DevToys#562]
### What's the Problem?

Common workflow when using something like number base converter is to try several values in succession. When pressing "paste", the clipboard contents are added next to existing contents, causing issues. Extra work is necessary to first clear the text box and then paste.

### Solution/Idea

Add a button to "clear and paste", or change paste button to clear text box by default

### Alternatives

Add a setting for "paste clears text box first"

### DevToys Version

Version 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

**Comment by veler** [comment]
Hello,

Thanks for this suggestion.
I like better the alternative idea you suggested: `Add a setting for "paste clears text box first"`.
I think I can do that. :)

**Comment by veler** [comment]
Hi @soumya92 ,

I added an option to the settings :D 
Here is the PR: https://github.com/veler/DevToys/pull/580

It will be shipped in the next update.
Cheers :)
