### ISSUE TITLE
url编码这里对于回车的处理在linux下会变成一行，希望修复！

### ISSUE THREAD

**Issue by fu7100** [veler/DevToys#572]
### Description

![图片](https://user-images.githubusercontent.com/59348973/177687219-6c57b833-1abc-4cfe-af5b-fcbf5be9f25e.png)

### Expected behavior

能在linux下正常使用

### DevToys Version

版本 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

### Relevant Assets/Logs

none

**Comment by fu7100** [comment]
不是在linux里面跑这个程序，是在我linux程序中使用你的工具的编码输出结果出现的问题。


***@***.***
 
发件人： Fa鸽
发送时间： 2022-07-08 03:16
收件人： veler/DevToys
抄送： fu7100; Author
主题： Re: [veler/DevToys] url编码这里对于回车的处理在linux下会变成一行，希望修复！ (Issue #572)
等一下你是怎么在linux里跑起来的？

**Comment by Akarinnnnn** [comment]
看了一下，是因为文本框的行尾是CR导致的。可以把标题改成“\[Suggestion\] Allow user to select line ending(CR LF or LF) in `CustomTextBox`”看看有没有更多人来做这个功能。

**Comment by veler** [comment]
Duplicate with #614
