### ISSUE TITLE
Json formatter changes the datetime to local datetime 

### ISSUE THREAD

**Issue by Meister1977** [veler/DevToys#573]
### Description

"Date": "2012-04-21T18:25:43-05:00" will be "Date": "2012-04-22T01:25:43+02:00" here in Hungary.

I think, a formatter tool should not change any content.

![image](https://user-images.githubusercontent.com/10465690/177780317-cec54f0a-22e9-468b-9731-90ad3eb92c93.png)

### Expected behavior

1. Go to Json formatter
2. Enter to input:
`{
  "Date": "2012-04-21T18:25:43-05:00"
}`

3. The output in Hugary (UTC+2):
`{
  "Date": "2012-04-22T01:25:43+02:00"
}`

### DevToys Version

1.0.8.0 verzió | X64 | RELEASE | db9b428 | db9b428

### Relevant Assets/Logs

No logs for this

**Comment by veler** [comment]
Hello,
Thanks for the feedback. I fixed the issue and opened a pull request for it. :)
