### ISSUE TITLE
YAML to JSON incorrect boolean conversion

### ISSUE THREAD

**Issue by JeromeDeLeon** [veler/DevToys#576]
### Description

I am expecting to convert boolean as boolean and not a string.

### Steps To Reproduce

Use this sample:

```yaml
isBoolean: false
```

### Expected behavior

```json
{
  "isBoolean": false
}
```

### DevToys Version

Version 1.0.8.0 | X64 | RELEASE | db9b428 | db9b428

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/32805276/177939092-1c518bc9-a270-4fbf-a473-e1b8686d5748.png)

**Comment by veler** [comment]
Hello, thanks for your feedback. I made a PR here that address this issue: https://github.com/veler/DevToys/pull/579
