### ISSUE TITLE
Norwegian is displayed as unknown locale

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#586]
### Description

"no-NO" region tag is displayed as an unknown locale because the region tag does not match the region tag supported by Windows.

The documentation seems to have multiple tags used in the region. (nb-NO nn-NO)
Also, although not listed, no-NO seems to be used in some cases.

### Expected behavior

Displayed as Norwegian.

### DevToys Version

Version 0.0.0.0 | X64 | DEBUG | main | 80bb4f02

### Relevant Assets/Logs

Microsoft Docs : [Available languages for Windows](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows?view=windows-11)

![image](https://user-images.githubusercontent.com/2970321/178611166-4a6ce4df-6921-4a86-95b2-723e9763fa17.png)

**Comment by veler** [comment]
Thanks for the feedback! I just updated Crowdin and fixed it :)
