### ISSUE TITLE
Leverage Favorites for Smart Detection

### ISSUE THREAD

**Issue by C1rdec** [veler/DevToys#600]
### What's the Problem?

The `Smart Detection` only open the corresponding tool when there's only 1 tool compatible with the clipboard.
More than 98% of the time I know the tool I want to use but there's a other tool that is compatible and this result in additional clicks.

### Lets take JSON as example: 
For my use case I would never need JSON <> YAML but the tool selection is blocked.

![image](https://user-images.githubusercontent.com/5436436/180134040-74c4ef9d-5504-4ee2-bc55-52a808b181d1.png)

### Solution/Idea

I would leverage the `Favorites System`.

Even if there's multiple match for the `Smart Detection` I would trigger the tool selection if there's one in my favorites.

### Alternatives

An alternative would be to add a way to disable `Smart Detection` manually for some tools

### DevToys Version

Version: 1.0.9.0

(On peut parler en Français si tu préfères)

**Comment by veler** [comment]
Hello,

Thanks for the suggestion. This is a great idea actually! I will try to implement this soon.

**Comment by C1rdec** [comment]
I can help out is there any steps to run DevToys with vs?

**Comment by C1rdec** [comment]
https://github.com/veler/DevToys/pull/626

**Comment by C1rdec** [comment]
Here is a simple PR:  https://github.com/veler/DevToys/pull/626
