### ISSUE TITLE
SQL Formatter doesn't handle brackets well

### ISSUE THREAD

**Issue by Freddie-H** [veler/DevToys#601]
### Description

If you input an SQL query that contains brackets around tablename, columnname or anything else, the formatter puts spaces after the starting bracket and before the end bracket. This results in an invalid SQL statement.

### Steps To Reproduce

Go to the SQL Formatter
Input the SQL statement: SELECT * FROM [TableName]
The result will be: 

SELECT
	*
FROM
	[ TableName ]

### Expected behavior

The result should be:

SELECT
	*
FROM
	[TableName]

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/105806458/180202893-652b4cf8-e451-4ff7-9dcd-13271645f2a2.png)

**Comment by araujofrancisco** [comment]
This happens with Standard Sql formatter, but if you try Transac-Sql formatter it works fine. It seems to me that StandardSqlFormatter.cs is missing the brackets in line 381, it should be something like:

stringTypes: new[] { "\"\"", "''", "N''", "[]" },

Not sure but my guess is that standard sql requires strings for nvarchar too.
