### ISSUE TITLE
JSON Formatter does not sort properties of objects in arrays

### ISSUE THREAD

**Issue by msevilgenius** [veler/DevToys#603]
### Example
Input the following JSON:
`{"a": "asdf", "c" : 545, "b": 33, "array": [{"a": "asdf", "c" : 545, "b": 33, "array": []}]}`
with sorting of properties enabled, it gets formatted like so: 
```JSON
{
  "a": "asdf",
  "array": [
    {
      "a": "asdf",
      "c": 545,
      "b": 33,
      "array": []
    }
  ],
  "b": 33,
  "c": 545
}
```
The object in the array has the same properties as the root object so they should be in the same order
Expected Result:
```JSON
{
  "a": "asdf",
  "array": [
    {
      "a": "asdf",
      "array": [],
      "b": 33,
      "c": 545
    }
  ],
  "b": 33,
  "c": 545
}
```

### Suggested fix
Adding something like this to the sort method seems to work:

```csharp
if (property.Value is JArray array)
{
    foreach (JToken? arrayItem in array)
    {
        if (arrayItem is JObject arrayObj)
        {
            SortJsonPropertiesAlphabetically(arrayObj);
        }
    }
}
```
Can make a PR for this change when I have some time

**Comment by veler** [comment]
Hi,
Thanks for the feedback and suggestion. I just fixed the issue :D
