### ISSUE TITLE
Drag and drop in tools

### ISSUE THREAD

**Issue by NEKolev** [veler/DevToys#605]
### What's the Problem?

Dragging and dropping files into fields doesn't work.

### Solution/Idea

Don't need to open the files. To work by dragging and dropping the files into the appropriate fields.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Comments

![image](https://user-images.githubusercontent.com/70388317/180515513-02abb269-f670-4f96-af0c-4abfd3856656.png)

**Comment by NikolayEKolev** [comment]
@JustAGabriel FYI

**Comment by NikolayEKolev** [comment]
@veler this is standard behavior in most functionality. If it doesn't move (deliberately disabled) should I close the issue?

**Comment by veler** [comment]
Done in DevToys 2.0

![image](https://github.com/veler/DevToys/assets/3747805/054f27fb-0fc8-42a7-91c6-07c14a4678ac)
