### ISSUE TITLE
Explain claims of JWT token like jwt.ms

### ISSUE THREAD

**Issue by cnshenj** [veler/DevToys#607]
### What's the Problem?

The JWT Token Decoder only decodes property raw values. It would be much more helpful if each claim is explained in detail.
For example, both DevToys and jwt.ms show this:
```json
"iat": 1658523177,
```
But jwt.ms shows more if you switch to "Claims" tab:
<html>
<body>

iat | Fri Jul 22 2022 13:52:57 GMT-0700 (Pacific Daylight Time) | "Issued At" indicates when the authentication for this token occurred.
-- | -- | --

</body>
</html>

### Solution/Idea

Explain claims like jwt.ms.

### Alternatives

None.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow devs to understand JWT token claims | Should |

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

**Comment by Christian-Oleson** [comment]
I am not sure how to see the "claims tab" but if someone wants to assign this one to me I am glad to take a look.

**Comment by veler** [comment]
@btiteux , didn't you address that work your recent change? Should we close this issue then?

**Comment by btiteux** [comment]
Hello, no I didn't resolve this issue but we discussed about it and how to do it.

I was going to take it but if @Christian-Oleson you want to take it go ahead.

We were thinking about adding a question icon or like a more information icon and we the user click this icon he will have a popin with the claims informations.

**Comment by Christian-Oleson** [comment]
> Hello, no I didn't resolve this issue but we discussed about it and how to do it.
> 
> I was going to take it but if @Christian-Oleson you want to take it go ahead.
> 
> We were thinking about adding a question icon or like a more information icon and we the user click this icon he will have a popin with the claims informations.

A few thoughts then:
Here was something I did quickly, which only renders the found fields. If a field in the payload were sub, it would also include that information, for example:
![image](https://user-images.githubusercontent.com/54334220/190949203-05aa834c-9f33-430e-93b9-ca7cfcecc1ae.png)
This may not be what y'all want, and if so, that is fine. Just wanted to throw that out since I was getting familiar with the code.
As if you wish it to be an icon. Do we always want to show this icon? Or perhaps only when one of those payload fields is found? Also, where are you thinking about having it?

**Comment by cnshenj** [comment]
> > Hello, no I didn't resolve this issue but we discussed about it and how to do it.
> > I was going to take it but if @Christian-Oleson you want to take it go ahead.
> > We were thinking about adding a question icon or like a more information icon and we the user click this icon he will have a popin with the claims informations.
> 
> A few thoughts then: Here was something I did quickly, which only renders the found fields. If a field in the payload were sub, it would also include that information, for example: ![image](https://user-images.githubusercontent.com/54334220/190949203-05aa834c-9f33-430e-93b9-ca7cfcecc1ae.png) This may not be what y'all want, and if so, that is fine. Just wanted to throw that out since I was getting familiar with the code. As if you wish it to be an icon. Do we always want to show this icon? Or perhaps only when one of those payload fields is found? Also, where are you thinking about having it?

Thanks for the screenshot. Two things I noticed:
- [https://jwt.ms/](https://jwt.ms/) not only explains the meaning, but *also explains* the value. For example, the value `nbf` will be shown in human readable time format.
- If it is going to be *comments*, then why not just show it next to the raw value? For example:
  ```jsonc
  {
    "nbf": 1663560975, // 2022-09-19T04:16:15Z, Not valid before
  }
  ```

**Comment by Christian-Oleson** [comment]
That is a good point. I can add value explanation!
As for the comments, I tried not to put them in the payload JSON as I wasn't sure how folks expect to interact with that payload, and thus if you want to copy, you can get just the payload and not the comments when doing so.
