### ISSUE TITLE
Timestamp convertor support millisecond and fix time zone

### ISSUE THREAD

**Issue by kid1412621** [veler/DevToys#612]
### What's the Problem?

1. millisecond support;
2. fix time zone(even switched between window, sometime the app detected the clipboard and changed the time zone).

### Solution/Idea

1. add the support
2. add setting to chose default time zone and fix it.

### Alternatives

nope

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

**Comment by niyari** [comment]
By default, it is set to your computer's time zone.
Would you like to change it to keep the last selected?

**Comment by veler** [comment]
Duplicate with #683
