### ISSUE TITLE
[Suggestion] Allow user to select line ending(CR LF or LF) in CustomTextBox

### ISSUE THREAD

**Issue by fu7100** [veler/DevToys#614]
### Solution/Idea

Allow user to select line ending(CR LF or LF) in CustomTextBox

### Alternatives

Allow user to select line ending(CR LF or LF) in CustomTextBox

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by heribertolugo** [comment]
[this](https://github.com/microsoft/monaco-editor/issues/3440#issuecomment-1346933980) might help:
![image](https://github.com/veler/DevToys/assets/26213368/52953066-779b-4458-9bec-649cbec0314e)

can maybe propagate the setting across all monaco boxes. default to user OS, but changeable in settings?
