### ISSUE TITLE
[Feature Request] Video converter (MP4, MOV, GIF, etc.)

### ISSUE THREAD

**Issue by bbnnzzyy** [veler/DevToys#615]
### Issue
Many websites like these:

- https://cloudconvert.com/video-converter
- https://video-converter.com/
- https://www.freeconvert.com/video-converter

Make it difficult to easily convert videos to other formats, such as `.mp4` to `.mov` or the like. The issue is that many of these have certain limitations, such as file size limits or a maximum amount of uses per day.
While a lot of software can convert files like this, it would make sense for something like DevToys to implement it into their own collection of tools, so that everyday users don't have to download a single program to do a simple task.

### Implementation
The general layout would be similar to the PNG / JPEG compressor. You upload a file, it converts it, and now you have a couple options:

- You can rename the video (the default would be identical to the name of the input file)
- You can watch the video using the video player described above
- Finally, you can download the final result.

Also similarly to the PNG / JPEG compressor, it would be cool to queue videos, so that you can convert the same video to multiple different file formats at the same time. Then you could `Save All` or `Delete All`.

**Comment by KillyMXI** [comment]
There are good free and open-source FFMPEG GUI options:

- https://alternativeto.net/software/shutter-encoder/about/
- https://alternativeto.net/software/ffqueue/about/
- https://alternativeto.net/software/qwinff/about/
- https://alternativeto.net/software/handbrake/about/
- (You can look around on the AlternativeTo website for more alternatives.)

I think this feature is too big both in dependencies size and in scope to bring it into DevToys.
Such toy can become a feature creep and get a life of it's own.
Few users won't need to download a separate application by the cost of everyone downloading extra 100MB *every time*.

**Comment by ape-manque** [comment]
Ditto on what the previous poster said. I don't think fits into the scope of the program or development, and most converters being standalone programs is probably a sign why. Here's what I use personally I use both of these more than the Adobe suite:

VLC is alright for conversions with the Libavcodec library, I don't think many people realize it can convert/download/stream besides just playback. The program/GUI is dated but entirely functional:

- https://www.videolan.org/vlc/

Even though FFmpeg gets a 1/10 in the UX department it's absolutely worth getting into, personally I don't think any of the GUI builds are worth using over just learning it in PowerShell. It'll pretty much do anything related to video/audio/images/media/streaming/etc that you need it to, not just encoding/decoding. Here's an installer for Windows:

- https://ffmpeg.org/download.html#build-windows

**Comment by veler** [comment]
Agreed, doesn't really fit the scope of DevToys. This could be a nice dedicated app, and I even wonder if there are already existing apps for this.
