### ISSUE TITLE
JSON格式识别不出来

### ISSUE THREAD

**Issue by xinhaiyang** [veler/DevToys#621]
### Description

JSON字符串 格式识别不出来

[{"enquiryorderdetailid":17233,"name":"柴油滤清器","list":[{"quotationdetailid":11174,"mid":2228,"refiorder":17233,"refdecode":0,"prodid":3569244,"code":"1000335797","name":"柴油滤清器","brandname":"板東","defaultimage":"","finalprice":12.000000,"qty":1.000000,"fqtys":0.0,"customremark":"","fitcarname":"AC Schnitzer X5 2011款 3.0T AT ACS5 35i(N55B30,8AT)","addressname":"NGK","spec":"","featurecodes":"","oenumber":"","drawingno":"4F0254800G","typename":"","prodkey":"4986625F84290FE1"}]},{"enquiryorderdetailid":17234,"name":"滤清器","list":[{"quotationdetailid":11175,"mid":2228,"refiorder":17234,"refdecode":0,"prodid":3569244,"code":"1000335797","name":"柴油滤清器","brandname":"板東","defaultimage":"","finalprice":12.000000,"qty":1.000000,"fqtys":0.0,"customremark":"","fitcarname":"AC Schnitzer X5 2011款 3.0T AT ACS5 35i(N55B30,8AT)","addressname":"NGK","spec":"","featurecodes":"","oenumber":"","drawingno":"4F0254800G","typename":"","prodkey":"4986625F84290FE1"}]}]

### Steps To Reproduce

![Uploading image.png…]()

### Expected behavior

[
    {
        "enquiryorderdetailid":17233,
        "name":"柴油滤清器",
        "list":[
            {
                "quotationdetailid":11174,
                "mid":2228,
                "refiorder":17233,
                "refdecode":0,
                "prodid":3569244,
                "code":"1000335797",
                "name":"柴油滤清器",
                "brandname":"板東",
                "defaultimage":"",
                "finalprice":12,
                "qty":1,
                "fqtys":0,
                "customremark":"",
                "fitcarname":"AC Schnitzer X5 2011款 3.0T AT ACS5 35i(N55B30,8AT)",
                "addressname":"NGK",
                "spec":"",
                "featurecodes":"",
                "oenumber":"",
                "drawingno":"4F0254800G",
                "typename":"",
                "prodkey":"4986625F84290FE1"
            }
        ]
    },
    {
        "enquiryorderdetailid":17234,
        "name":"滤清器",
        "list":[
            {
                "quotationdetailid":11175,
                "mid":2228,
                "refiorder":17234,
                "refdecode":0,
                "prodid":3569244,
                "code":"1000335797",
                "name":"柴油滤清器",
                "brandname":"板東",
                "defaultimage":"",
                "finalprice":12,
                "qty":1,
                "fqtys":0,
                "customremark":"",
                "fitcarname":"AC Schnitzer X5 2011款 3.0T AT ACS5 35i(N55B30,8AT)",
                "addressname":"NGK",
                "spec":"",
                "featurecodes":"",
                "oenumber":"",
                "drawingno":"4F0254800G",
                "typename":"",
                "prodkey":"4986625F84290FE1"
            }
        ]
    }
]

### DevToys Version

版本 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Relevant Assets/Logs

Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.

**Comment by hinnuryuu** [comment]
已经解决了，更新到1.0.10.0
