### ISSUE TITLE
ignore comments in Text diff

### ISSUE THREAD

**Issue by lmncaj** [veler/DevToys#629]
### What's the Problem?

Please support ignoring comment out in Text Comparer(Text Diff).
I'm very confusing, and its hard to see what is difference when the different comments are same line as codes.

### Solution/Idea

add igonoring comment toggle in Confuguration section 

### Alternatives

no alternatives

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal must allow users to identify easily different texts in Text Comparer  | Must |

### DevToys Version

Version: 1.0.9.0

**Comment by veler** [comment]
Would require to make the editor aware of too many programming languages at once. I don't think it worth the pain.
