### ISSUE TITLE
Better Favorites

### ISSUE THREAD

**Issue by itayasaf1990xd** [veler/DevToys#632]
### What's the Problem?

I feel like it is a better approach to make Favorites tools inside a tab like all other tools categories and maybe add commonly used or latest used title to the current favorite approach and by the title to separate it from the All Tools tab.

### Solution/Idea

I am not sure how to draw/describe it

### Alternatives

none

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by michael-hawker** [comment]
I didn't even realize there was a favorite system until seeing this issue and thinking of right-clicking on the navigation view...

Was expecting to see a ⭐ to fill-in or something in the top-right of the tool page to mark something as a favorite, would be a lot more discoverable:

![image](https://user-images.githubusercontent.com/24302614/205165183-b276eb58-9108-4c9b-8cd2-0a8182f69a8b.png)

I would also expect to see a favorites group at the top of the home page as well when on the 'All tools' page.

**Comment by veler** [comment]
Done in 2.0 https://github.com/veler/DevToys/commit/9a9eab5e29c4a494bd1e52248c2163a105da3d84
