### ISSUE TITLE
Mermaid Diagram Generator (PNG, SVG,MD)

### ISSUE THREAD

**Issue by olejsc** [veler/DevToys#633]
### What's the Problem?

A generator for mermaid diagrams, allowing you to export it as PNG, SVG, Markdown or copy the markdown text. 
Mermaid diagrams can be used to make a huge variete of different diagrams - such as flowcharts, class-, state-  and sequence diagrams and many more and is supported to be viewed in most markdown editors out there. 

### Solution/Idea

A generator for mermaid diagrams, allowing you to export it as PNG, SVG, Markdown or copy the markdown text. 

A example of possible features and live editor can be found at [Mermaid Live](https://mermaid.live)

### Alternatives

There's no alternatives as I'm aware of.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Enter mermaid syntax  | Must |
| Preview diagram (through markdown rendering) | Must |
| Export Diagram as PNG | Should |
| Export Diagram as SVG | Should |
| Export Diagram as Markdown file | Should |
| Provide helper link to mermaid syntax documentation | Should |
| Set size of exported PNG | Could |
| Set size of exported SVG | Could |

### Comments

Any thoughts? 
It would also be beneficial if the included markdown renderer in in DevToys also support rendering mermaid.

**Comment by jai-dewani** [comment]
I second this feature, 
I have been using mermaid for our documentation but sometimes I just need to generate a quick flow diagram, though I have found a web alternative to it, https://excalidraw.com/

**Comment by veler** [comment]
Great idea but I feel like this deserves to be its own app, not just a tool in DevToys.
