### ISSUE TITLE
QR code generator / decoder

### ISSUE THREAD

**Issue by thomassth** [veler/DevToys#636]
### What's the Problem?

It's easy to find one online, but I feel uneasy sending data into untrusted servers

### Solution/Idea

Do it locally!

Encoder: easier part, just generate an image from text

Decoder: harder part, needs code reader, reading from image/camera, then parse data (Not that useful at the moment tbh)

### Alternatives

Sending data to online generator. Just problematic.

Using mobile app. And then I need to send data to/from my mobile devices to my workstation, also a hassle.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to encode text into QR codes | Must |
| This proposal will allow end users to decode QR from image / camera source | Could |

**Comment by Palkiaa** [comment]
Hi!

@Rethabile06 and I are going to take a look at this :)

**Comment by veler** [comment]
#270
