### ISSUE TITLE
Feature Request: password generator with options

### ISSUE THREAD

**Issue by pascal456** [veler/DevToys#638]
### What's the Problem?

Sometimes when implementing authentication methods, I feel like I would like to have a generator (separated from the one in my firefox browser) in one neat place with all my other tools (devToys ❤) to do checks

### Solution/Idea

Add a password generator.

The password generator should allow to set options like:
- length of the password
- include lower / upper case letters
- include special characters

### Alternatives

Alternative would be to use the browser built-in generator on a random site. Other than that there are websites with password generators.

Still other than that there are the hashing tools here in DevToys, but then I would have to make amendmends like lengths, special characters etc. by myself, which is not 100% convenient.

**Comment by jamescurran** [comment]
Here's an algorithm I came up with to handle this:

`
```
	var rnd = new Random();

	// these will be user entered parameters. 
	int totalChars = 10;
	
	// minimum number of each character type.  if 0, that type not used at all.
	int minUpper = 2;
	int minLower = 2;
	int minDigit = 4;
	int minSpec = 1;

	// Do we have an option for non-English characters?
	const string Upper = "ABCDEFGHIJKLMNOPQSRTUVWXYZ";
	const string Lower = "abcdefghijklmnopqrstuvwxyz";
	const string Digits = "0123456789";
	
	// Do we let the user select which special characters to use?
	const string Special = "!@#$%^&*()_{}-[]:;.";
	
	var extras = new List<string>();
	if (minUpper > 0) extras.Add(Upper);
	if (minLower > 0) extras.Add(Lower);
	if (minDigit > 0) extras.Add(Digits);
	if (minSpec > 0) extras.Add(Special);
	
	var sb = new StringBuilder(totalChars);

	AddRandomCharacters(rnd, sb, Upper, minUpper);
	AddRandomCharacters(rnd, sb, Lower, minLower);
	AddRandomCharacters(rnd, sb, Digits, minDigit);
	AddRandomCharacters(rnd, sb, Special, minSpec);

	while(sb.Length < totalChars)
	{
		AddRandomCharacters(rnd, sb, extras[rnd.Next(extras.Count)], 1);
	}


	Shuffle(rnd, sb);

	sb.Dump();`

void Shuffle(Random rnd, StringBuilder sb)
{
	for(int i = sb.Length-1; i >0; --i)
	{
		var r = rnd.Next(i);
		var t = sb[r];
		sb[r] = sb[i];
		sb[i] = t;
	}
}

void AddRandomCharacters(Random rnd, StringBuilder sb, string charSet, int cnt)
{
	while(cnt-- > 0)
		sb.Append(charSet[rnd.Next(charSet.Length)]);
}

```

**Comment by Vexxell** [comment]
Can I work on this issue?

**Comment by Christian-Oleson** [comment]
> Can I work on this Feature Request?

If for some reason you cannot, I'm glad to take a look at doing this one.

**Comment by pascal456** [comment]
Actually I was not planning to work on this because I am full with other work currently. Also I have not worked on this project yet at all, so ramp up time would be longer for me 😅
Means if you want to, start it, there is no assignee yet.

**Comment by Christian-Oleson** [comment]
![PW Generator](https://user-images.githubusercontent.com/54334220/190960057-423e5120-12e7-475b-b78f-338166d7545e.PNG)
If you would like to assign this one to me, that would be great. I have a minor bug in the menu and the PW quantity, but otherwise have a working solution.

**Comment by Christian-Oleson** [comment]
https://github.com/veler/DevToys/pull/664

**Comment by Vexxell** [comment]
Hey that looks good to me!

**Comment by pascal456** [comment]
@Christian-Oleson seems like I cannot assign someone to this issue. Should I be able to do it as the issue creator?

**Comment by Christian-Oleson** [comment]
> @Christian-Oleson seems like I cannot assign someone to this issue. Should I be able to do it as the issue creator?

I don't believe so, but I do not know. Personally, this is my first time contributing here. I believe it requires a maintainer to assign an issue.
