### ISSUE TITLE
Add Crypto functions or others like 'cyberchef' ? 

### ISSUE THREAD

**Issue by joydo** [veler/DevToys#64]
* Hi,veler, I want to contribute to this project
 wanna add crypto(AES,DES,entropy related)functions for this project.
 wanna add compression/decompression functions for this project.
etc...
* but my programming language background is c++/python, I haven't touched c# before
   if I want to add new function, which section will I need to modify?(including UI, logic module).
   Is there possible one detail design document for this project ?

**Comment by veler** [comment]
Hello,
Thanks for reaching out and wanting to contribute.

DevToys relies on Injection Dependency using MEF https://docs.microsoft.com/en-us/dotnet/framework/mef/
In DevToys, each tools are dynamically loaded through injection dependency. The entry point of a tool is a class that implements `IToolProvider`.

I realized that the [Contributing](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md#main-architecture) file was missing some information. I added some useful explanation at how tools work in DevToys.

Let me know if I can help further more :)
