### ISSUE TITLE
Feature : add SSL cert decoder

### ISSUE THREAD

**Issue by bobbyben** [veler/DevToys#646]
### What's the Problem?

Decode ssl pem encoded certificate content.
Allow to show info that's is returned by openssl. `openssl x509 -in certificate.crt -text -noout`
An exemple of result 
https://www.sslshopper.com/certificate-decoder.html

- SSL cert decoder
- SSL csr decoder
- SSL certificate-key-matcher

### Solution/Idea

Integrate openssl lib and allow to decode pem encoded cert file.
If a cert file is in clipboard, redirect automatically to this new devtoy.

### Alternatives

no idea

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to decode ssl encoded cert in PEM format | Must |
| This proposal will allow developers to decode ssl encoded csr  | Should |
| This proposal will allow developers to check if public and private key are matching | Should |

**Comment by Christian-Oleson** [comment]
That link does not work for me. Any chance you could provide a rough mockup of what you are thinking?

**Comment by bobbyben** [comment]
Same service exists on https://www.sslchecker.com/certdecoder
An example of restitution with the pem certificate in example on the site

![image](https://user-images.githubusercontent.com/21336289/192117702-3fdd7e40-2b42-4287-bc02-0755872321b4.png)
