### ISSUE TITLE
End of line sequence selector in Base64 Text Encoder / Decoder

### ISSUE THREAD

**Issue by sylvain1811** [veler/DevToys#647]
### What's the Problem?

Encoding text with DevToys and decoding it with another tool (base64 cli) does not work if end of line sequence matter.

Example : OpenSSH keys

### Solution/Idea

Add a drop-down below "Encoding" to let user select either CRLF (Windows) or LF (Linux) as end of line sequence of their input.

### Alternatives

Use another base64 encoder / decoder.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hello,

This is a great idea, but I wonder if some other tools could also take advantage of this, which makes me wonder whether a global option in the Settings page would be better. I'm not 100% sure to be honest. Thoughts?

**Comment by jonasspecht** [comment]
That would probably be the most robust and future-proof solution. 
I can't off the top of my head think of other scenarios where the end of line sequence is important but I'm sure there are/could be some.

Having the global option would solve this issue and prevent future, similar issues.

**Comment by sylvain1811** [comment]
I think that users switching frequently between LF / CRLF would appreciate having this dropdown in the Base64 encoder / decoder  and other tools using this option, but not in the Settings page.

I like the screenshots in the Pull request a lot !

Having this option in the Settings page would be useful as a default value.

**Comment by veler** [comment]
Duplicate with #468
