### ISSUE TITLE
JSON <> Class generator

### ISSUE THREAD

**Issue by hunterlan** [veler/DevToys#648]
### Solution/Idea

There's a lot of service, which suggests convert JSON data to a class for defined language programming. However, It would be great, if DevToys had this instrument. 

How I see it:

1. User open this converter.
2. Paste JSON
3. If it's possible, convert it to defined language (for start it would be great to see TypeScript and C#, in future implement it for most popular languages.)
4. Give a result to user.

### Alternatives

[JSON2CSharp](https://json2csharp.com/)

**Comment by veler** [comment]
Duplicated with #648
