### ISSUE TITLE
Random stuff

### ISSUE THREAD

**Issue by vpratfr** [veler/DevToys#656]
### What's the Problem?

Would be nice to get a generator for random strings (passwords, keys, etc.)

### Solution/Idea

input could be a list of allowed characters (with some presets 

- digits
- hex
- alphanum
- user input (a text edit where you input all the characters you want to allow)

### Alternatives

https://www.random.org/strings/

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

**Comment by jamescurran** [comment]
Largely similar to #638 and #643.  I guess the time is just right for this, as we've gotten three requests for this functionality in less than 3 weeks.

**Comment by vpratfr** [comment]
Whoops. Sorry about the duplicates.

Indeed would be useful sometimes :)

Le mar. 6 sept. 2022 à 19:06, James Curran ***@***.***> a
écrit :

**Comment by 3kh0** [comment]
@vpratfr Close this issue since it is a duplicate
