### ISSUE TITLE
json array is not valid

### ISSUE THREAD

**Issue by Xamage** [veler/DevToys#660]
### Description

When typing a json array in the JSON formatter I have the following error:
`Error reading JObject from JsonReader. Current JsonReader item is not an object:`

Since array is a valid JSON object, we should be able to type anything like `["dog", "cat"]` or simply `[]` and have it formatted

### Steps To Reproduce

1. Go Formatters > JSON
2. Type `[]` or `["dog", "cat"]` in the input field
3. An error appears in the output pane

### Expected behavior

A formatted array, with no error

### DevToys Version

Windows 10 / Version 1.0.9.0 | X64 | RELEASE

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/5774255/190103532-b7520f53-2d56-4fb4-acb3-b152ed6a7382.png)

**Comment by Christian-Oleson** [comment]
I can take a look at this if someone will assign it to me.

**Comment by veler** [comment]
Duplicated with #650
