### ISSUE TITLE
API/Documentation Browser

### ISSUE THREAD

**Issue by juliomenendez** [veler/DevToys#669]
### What's the Problem?

Would it make sense to include a feature that allows to browser API documentation like Dash for Mac OS, Velocity for Windows, and Zeal (https://github.com/zealdocs/zeal)?

### Solution/Idea

A new tool that allows to add/download, search and explore Docsets.

### Alternatives

I've been using Velocity and reading the source code of Zeal. Either solution works but would be nice to have the feature integrated in DevToys.

**Comment by veler** [comment]
Hi,
Didn't know that such a tool existed! It looks nice! But to be honest, I'd imagine this as its own app instead of just another tool in DevToys, mainly because I feel like it would deserve so many features and work that it could be a whole project of its own.
