### ISSUE TITLE
JWT Decoder show timestamp as a DateTime tooltip

### ISSUE THREAD

**Issue by sergiomontesa** [veler/DevToys#670]

**Comment by jlevier** [comment]
I tried looking into this but I could not get the hover to show on the Monaco editor.  I see we have this: https://github.com/veler/DevToys/blob/main/src/dev/impl/DevToys.MonacoEditor/ts-helpermethods/otherScriptsToBeOrganized.ts#L11 and just as a preliminary test I hardcoded a call in `CodeEditorCore.html`:

```javascript
monaco.languages.registerHoverProvider("json", {
    provideHover: function (model, position) {
        Debug.log("5555555555");
        return {
            range: new monaco.Range(
                1,
                1,
                2,
                5
                // model.getLineCount(),
                // model.getLineMaxColumn(model.getLineCount())
            ),
            contents: [
                { value: "**SOURCE**" },
                { value: "test test 1234"},
            ],
        };
    },
});
```

I also added "json" as the language type explicitly via 
```javascript
opt["language"] = 'json';
```

and then checked if `monaco.languages.registerHoverProvider` exists via
```javascript
Debug.log(typeof monaco.languages.registerHoverProvider);
Debug.log(monaco.languages.registerHoverProvider.toString());
```

and indeed it is there.  However, nothing I do will produce a hover state.  The [example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAJRBQAAAAAAAABBqQkHQ5NjdMpUO-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWS9TrQEnwCr9oHSnXiOatgv2xWlM88rnDU7n-jKpJKRkAypzWiMuh2msBFZQq8QqE6i1_oBZhyzFUqnqXMOX_7FsorCq1jppuZCiDiKQahUanuieBhOXKD4l6AiodBsJbXMY9LUp3cUzC301dHltXZEy_c0SaRuLAkwoa0OUAM_i8mcKf1xSI9FO-LRY9NiKY4JKQd5Tc6_bneMVKHT8zG41WXBc8XdMzfJdkOfMaJ3iKgUhguT11SzeKYCcdg2qpVJZ83LdjPPf8ktOhv_Ts6PBtuyaTXGTbqxp3iT5PIksFA9KHk5zKISHekZk-sodLhU9qwGJyCITUZ75N4ZVSYg2HbU1zjJKRT2yzVxUW67zlbqSEuCAlD390kAjRhUwgec3H2kfE8s6I_Js18VgaJl--u2UKHoCfEJq_Nem1Rpyr0lirc1CPKf3-diTxVSLzzxIIARR68_BFo4O8oVHKuNBF2i0qWgXW6XqKJGXA08jlF2ZRyAKNFbp79cP9CNhQALwVdDSmWAdDKrW_0xF52iEOwFuWR04ety0itEY3de3qVulSp620Uo8JrPw3CoSB_3Id8ePFjfVbdRSC70BH1c3N_K26hN24tFr3C-X4l9SeVKuM3O5qs2oLU-AstV_PgBmXCQX6pcx5MFNT1HqIqCwFvK1TUzh37Nf4DBDSpdETCAzcDmA9eTVKeGAuaH_C4n_b9HS6e0c8k3GPVhj7QEgM_bWvNFwVyHt90ZN2Loxk5m3hGNN6z_Hwbi48eohdOGw4nWDL9uPXMpTHuoXwDpOOQtCFhd-Y2i6cQWTxdJiTbQ___C8P6A) they provide is straightforward enough.

I am much less familiar with UWP so I might be missing something obvious.  Not sure if you have got this working before, @veler?

**Comment by micahmo** [comment]
+1000 to this idea. Decoding tokens to look at the dates is such a common operation, and reading the raw timestamp is nearly impossible. This is something [jwt.io](https://jwt.io/) does, for example.

P.S. It might not be as "pure", but even putting the human-readable date inline in the JSON (maybe a comment?) would help! Could be behind a toggle if most people don't want it.

**Comment by veler** [comment]
> I tried looking into this but I could not get the hover to show on the Monaco editor. I see we have this: https://github.com/veler/DevToys/blob/main/src/dev/impl/DevToys.MonacoEditor/ts-helpermethods/otherScriptsToBeOrganized.ts#L11 and just as a preliminary test I hardcoded a call in `CodeEditorCore.html`:
> 
> ```js
> monaco.languages.registerHoverProvider("json", {
>     provideHover: function (model, position) {
>         Debug.log("5555555555");
>         return {
>             range: new monaco.Range(
>                 1,
>                 1,
>                 2,
>                 5
>                 // model.getLineCount(),
>                 // model.getLineMaxColumn(model.getLineCount())
>             ),
>             contents: [
>                 { value: "**SOURCE**" },
>                 { value: "test test 1234"},
>             ],
>         };
>     },
> });
> ```
> 
> I also added "json" as the language type explicitly via
> 
> ```js
> opt["language"] = 'json';
> ```
> 
> and then checked if `monaco.languages.registerHoverProvider` exists via
> 
> ```js
> Debug.log(typeof monaco.languages.registerHoverProvider);
> Debug.log(monaco.languages.registerHoverProvider.toString());
> ```
> 
> and indeed it is there. However, nothing I do will produce a hover state. The [example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAJRBQAAAAAAAABBqQkHQ5NjdMpUO-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWS9TrQEnwCr9oHSnXiOatgv2xWlM88rnDU7n-jKpJKRkAypzWiMuh2msBFZQq8QqE6i1_oBZhyzFUqnqXMOX_7FsorCq1jppuZCiDiKQahUanuieBhOXKD4l6AiodBsJbXMY9LUp3cUzC301dHltXZEy_c0SaRuLAkwoa0OUAM_i8mcKf1xSI9FO-LRY9NiKY4JKQd5Tc6_bneMVKHT8zG41WXBc8XdMzfJdkOfMaJ3iKgUhguT11SzeKYCcdg2qpVJZ83LdjPPf8ktOhv_Ts6PBtuyaTXGTbqxp3iT5PIksFA9KHk5zKISHekZk-sodLhU9qwGJyCITUZ75N4ZVSYg2HbU1zjJKRT2yzVxUW67zlbqSEuCAlD390kAjRhUwgec3H2kfE8s6I_Js18VgaJl--u2UKHoCfEJq_Nem1Rpyr0lirc1CPKf3-diTxVSLzzxIIARR68_BFo4O8oVHKuNBF2i0qWgXW6XqKJGXA08jlF2ZRyAKNFbp79cP9CNhQALwVdDSmWAdDKrW_0xF52iEOwFuWR04ety0itEY3de3qVulSp620Uo8JrPw3CoSB_3Id8ePFjfVbdRSC70BH1c3N_K26hN24tFr3C-X4l9SeVKuM3O5qs2oLU-AstV_PgBmXCQX6pcx5MFNT1HqIqCwFvK1TUzh37Nf4DBDSpdETCAzcDmA9eTVKeGAuaH_C4n_b9HS6e0c8k3GPVhj7QEgM_bWvNFwVyHt90ZN2Loxk5m3hGNN6z_Hwbi48eohdOGw4nWDL9uPXMpTHuoXwDpOOQtCFhd-Y2i6cQWTxdJiTbQ___C8P6A) they provide is straightforward enough.
> 
> I am much less familiar with UWP so I might be missing something obvious. Not sure if you have got this working before, @veler?

This will likely be easier with DevToys 2.0 because:
1. We're using a more recent version of Monaco (although, not the last one for now).
2. The whole app runs locally in a web-browser, so we have less limitation than in UWP.

Let's wait for DevToys 2.0 to do this?

**Comment by jlevier** [comment]
Yes, I think that makes sense and was hoping is the case! Thank you - will revisit.

**Comment by micahmo** [comment]
> It might not be as "pure", but even putting the human-readable date inline in the JSON (maybe a comment?) would help!

In the short-term, would a PR that does this be accepted? It's very hacky -- I'm crudely "parsing" the JSON after it's been formatted (since I couldn't find a nice way to insert comments through the standard libraries). But it works and is formatted nicely by Monaco! 😊

https://github.com/micahmo/DevToys/compare/main...feature/jwt-datetimes

![image](https://github.com/veler/DevToys/assets/7417301/5c828b8e-e181-4193-a97e-4429e0eb1455)

**Comment by veler** [comment]
@btiteux , what do you think of the above?

**Comment by micahmo** [comment]
Hey all, quick update (and hopeful improvement) over my previous hacky solution. I did find how to enable hovers, and it came down to these lines (which currently disable it).

https://github.com/veler/DevToys/blob/e9528b1193bda1e3f44365e50d2a0c473a5d45dc/src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs#L252-L255

I put together a solution that "works". However, my understanding of the architecture (especially when it gets into Monaco/WebView/JavaScript) is pretty bad. Would @veler or @jlevier be willing to peek at my branch before I formally open a PR?

https://github.com/micahmo/DevToys/compare/main...feature/jwt-datetimes2

| ![image](https://github.com/veler/DevToys/assets/7417301/63c10095-4fc5-4db6-ae81-17ef1e0909ff) |
| - |
