### ISSUE TITLE
CSV / XML / Excel to JSON

### ISSUE THREAD

**Issue by dmoKruso** [veler/DevToys#671]
### What's the Problem?

Its very common to need to convert an excel file to JSON. So if we had an way to convert an excel file or at least an csv (since we can convert easily from excel to csv) to a JSON file would be great.

### Solution/Idea

There are many convertors online but it would be great to have locally to not rely on internet connection on do it locally.

### Alternatives

Nothing.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by KarimKanounGit** [comment]
That will be a very useful feature.
I suggest to add YAML as an option for the output

**Comment by jdivis** [comment]
@KarimKanounGit I see that JSON to Yaml is already possible:

![image](https://user-images.githubusercontent.com/7316918/207069615-a35ccd47-e286-45e9-a70c-12e35e5a114e.png)

+1 for JSON to CSV though!

**Comment by veler** [comment]
Duplicated with #200
