### ISSUE TITLE
Error opening xml file

### ISSUE THREAD

**Issue by NEKolev** [veler/DevToys#672]
### Description

When trying to open an xml file through the program (XML Formatter, XML Validator, Text Comparer), this message appears.
![pbN4eQ19PV](https://user-images.githubusercontent.com/70388317/192001268-d376667e-7028-4c7c-855f-b8ab07b86497.jpg)

### Steps To Reproduce

1. You open the XML Formatter.
2. You press the Load file button.
3. Select file test.xml.
4. The error appears.

### Expected behavior

File to be loaded on opening.

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

### Relevant Assets/Logs

# 
[09/23/2022 18:44:56]
Feature name: Failed to load a file into a code editor
Custom message: 
Exception message: No mapping for the Unicode character exists in the target multi-byte code page.

No mapping for the Unicode character exists in the target multi-byte code page.

Exception stack trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at DevToys.UI.Controls.CodeEditor.<OpenFileButton_Click>d__63.MoveNext() + 0x3c6

**Comment by NikolayEKolev** [comment]
@veler The problem, in my opinion, is global, not in specific functionalities - XML Formatter, XML Validator, Text Comparer.

**Comment by veler** [comment]
`No mapping for the Unicode character exists in the target multi-byte code page.`
That is an interesting error message. Would you be able to share a minimal XML _**file**_ that reproduces this error?

**Comment by NikolayEKolev** [comment]
> `No mapping for the Unicode character exists in the target multi-byte code page.` That is an interesting error message. Would you be able to share a minimal XML _**file**_ that reproduces this error?
Of course
[test.zip](https://github.com/veler/DevToys/files/9635244/test.zip)

**Comment by veler** [comment]
Thank you! I will try to look into it this weekend :)

**Comment by veler** [comment]
Fixed in DevToys 2.0 (sorry it took so long).
![image](https://github.com/veler/DevToys/assets/3747805/9c2ea9e3-7ce0-4ea2-905e-93b9bcd73d83)
