### ISSUE TITLE
Add additional filter file extensions when opening from the "Load a file" button

### ISSUE THREAD

**Issue by NEKolev** [veler/DevToys#673]
### What's the Problem?

There is no one of the possible file extensions that are loaded into the program - *.html, *.xsd (there may be others).### 

### Solution/Idea

It will be very useful to add these extensions - *.html, *.xsd (there may be others). 

For example, on the XML Validator screen, when selecting a *.xsd file, a default file is a filter for this type of file.
![jdSl44xyeT](https://user-images.githubusercontent.com/70388317/192063504-d7accc3f-e16b-43f0-8cb9-bf9b45de78a7.jpg)

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by veler** [comment]
Done in DevToys 2.0

![image](https://github.com/veler/DevToys/assets/3747805/e30f1fb3-ffe5-4611-9ae3-7dd50c338d7a)
