### ISSUE TITLE
Wasted screen space

### ISSUE THREAD

**Issue by valhristov** [veler/DevToys#678]
### What's the Problem?

First and foremost: thanks for working on this tool!

The problem: I think there is a lot of wasted screen space on the application window. See screenshot below.

The Windows OS is trying to work well on both touch and non-touch screens and forces UI guidelines with a lot of empty space. It looks nice on the OS itself, but when I develop, I prefer to see more of my own content and minimize the tools' GUI. In addition I doubt there are that many developers who tap the screen while they are programming, and having such wide borders that are supposed to work well with fingers seems very wasteful.

Generally the application looks really nice, I don't want to suggest entirely changing the UI.

![image](https://user-images.githubusercontent.com/23195959/192980875-c0f9d26e-c507-407f-8ce1-d4fb1e89bc9e.png)

### Solution/Idea

On the tools that convert or format text, I would prefer to see more from the text itself than the application margins or configuration GUI.

### Alternatives

Have different margin size depending on whether tablet mode is enabled or not.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to see more from their content and less from the application UI | Must |
| The developers can work both in tablet and desktop mode | Could |

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by veler** [comment]
How about something like this? (early development of DevToys 2.0)

![compactmode](https://user-images.githubusercontent.com/3747805/224606675-1685d38c-14c6-4d2f-bdca-d50ce9777434.gif)

**Comment by veler** [comment]
Added in 2.0 https://github.com/veler/DevToys/commit/71fdb24ca8ef374adeb27cbf1e53f0e4698e4555
