### ISSUE TITLE
Regex Tester: Windows 10 Dark Mode's color scheme causes the matched text to not be visible when out of focus

### ISSUE THREAD

**Issue by kennypu** [veler/DevToys#681]
### Description

On Windows 10, when using Dark theme with the RegEx Tester, the matched text highlight under Text is not visible due to the highlight color being the same as the "not focused" color for Text. Light theme works as expected.

### Steps To Reproduce

1. Set the App Theme to Dark
2. Use the Regex Tester and match some text

NOTE: I noticed that on certain reloads, the highlight text is different/lighter, causing it to be fine/visible. I would assume that is a separate issue.

### Expected behavior

Either: 

1. Adjust the matching text highlight color to be something with clear contrast for dark theme;
2. Add setting to adjust highlight colors through-out the app so we can adjust it ourselves.

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

### Relevant Assets/Logs

**Light Theme Example**
![image](https://user-images.githubusercontent.com/1253814/193365610-44c8db1f-9686-4888-b875-a250f0d24903.png)

**Dark Theme Example when Text is out of focus, eg. when the cursor is in "Regular Expressions"**
![image](https://user-images.githubusercontent.com/1253814/193365759-a8a11352-a886-46ed-9d34-16b75af717fb.png)

**Dark Theme Example when Text is in focus (here highlight is visible, but contrast is very low)**
![image](https://user-images.githubusercontent.com/1253814/193365796-88119695-5989-4beb-94b0-8d732b51add0.png)

**Comment by veler** [comment]
Hi,
Here is a preview of what I'm working on for DevToys 2.0. The colors won't follow the system's accent color and are better adapted to the dark/light theme.

![image](https://github.com/veler/DevToys/assets/3747805/6cecbbf1-493c-45c6-b33f-a0f3326b0350)
