### ISSUE TITLE
Theme Creator with filters

### ISSUE THREAD

**Issue by Tetrax-10** [veler/DevToys#689]
### Solution/Idea

It will be good to add custom filters to a image like hue, saturation, and more like photoshop so we can create theme colors easly.

I got this idea from `color blindness filter`
![image](https://user-images.githubusercontent.com/75513645/195431382-3d76d240-421b-4575-9960-14995935c937.png)

# Original Theme
![image](https://user-images.githubusercontent.com/75513645/195431617-1af19b9d-2a1d-4119-a6e3-c66fd47894fe.png)

# After some filters got Mint Colors
![1c6cbfb1-1964-411e-9eeb-895abad0245b-Tritanopia](https://user-images.githubusercontent.com/75513645/195431766-36b248b2-129c-4feb-b844-f891bdb0c1d7.png)

 If anyone know any method to extract different colors from a theme like Nord to Mint, Strawberry please share.

### Alternatives

Changing a set of hex code to a different hex code so it results in different theme color.

**Comment by veler** [comment]
Can't Figma, Gimps, Paint.NET do this for free?
