### ISSUE TITLE
cannot build DevToys in my dev environment

### ISSUE THREAD

**Issue by x0341** [veler/DevToys#695]
### Description

cannot build DevToys in my dev environment.

cloned the repo and when trying to run locally on my dev machine with Win11 and VStudio 2022 it states that some ts (type script ?) files are missing.

### Steps To Reproduce

1. clone repo into your local machine
2. run locally
3. 

### Expected behavior

1. app locally running

### DevToys Version

repo src code (current version)

### Relevant Assets/Logs

Build started...
1>------ Build started: Project: DevToys.Shared, Configuration: Release Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>DevToys.Shared -> D:\DevToys\bin\Release\AnyCPU\DevToys.Shared\netstandard2.0\DevToys.Shared.dll
2>------ Build started: Project: DevToys.OutOfProcService, Configuration: Release x64 ------
3>------ Build started: Project: DevToys.MonacoEditor, Configuration: Release x64 ------
2>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(12,12): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(23,35): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(55,43): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(80,31): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(95,35): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(110,36): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(116,40): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(117,45): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(124,5): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(141,5): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(147,5): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(164,5): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(5,12): error TS2304: Build:Cannot find name 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
3>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(17,25): error TS2304: Build:Cannot find name 'monaco'.
4>------ Build started: Project: DevToys, Configuration: Release x64 ------
2>Failed to resolve WinRT.Runtime.dll.
2>DevToys.OutOfProcService -> D:\DevToys\bin\Release\x64\DevToys.OutOfProcService\net6.0-windows10.0.19041.0\DevToys.OutOfProcService.dll
4>  Transforming template LanguageManager.tt...
4>D:\DevToys\src\dev\impl\DevToys\DevToys.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'D:\DevToys\bin\Release\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd'
4>CSC : error CS0006: Metadata file 'D:\DevToys\bin\Release\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd' could not be found
4>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
5>------ Build started: Project: DevToys.Startup, Configuration: Release x64 ------
5>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1805,5): warning NU1702: ProjectReference 'D:\DevToys\src\dev\impl\DevToys.OutOfProcService\DevToys.OutOfProcService.csproj' was resolved using '.NETCoreApp,Version=v7.0' instead of the project target framework '.NETFramework,Version=v4.5.1'. This project may not be fully compatible with your project.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(848,5): warning : Package signing is enabled but no thumbprint or certificate path is specified.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(12,12): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(23,35): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(55,43): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(80,31): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(95,35): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(110,36): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(116,40): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(117,45): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(124,5): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(141,5): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(147,5): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(164,5): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\registerCompletionItemProvider.ts(5,12): error TS2304: Build:Cannot find name 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(5,21): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(6,20): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(7,42): error TS2503: Build:Cannot find namespace 'monaco'.
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\updateSelectedContent.ts(17,25): error TS2304: Build:Cannot find name 'monaco'.
5>Done building project "DevToys.MonacoEditor.csproj" -- FAILED.
5>Transforming template LanguageManager.tt...
5>D:\DevToys\src\dev\impl\DevToys\DevToys.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'D:\DevToys\bin\Release\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd'
5>CSC : error CS0006: Metadata file 'D:\DevToys\bin\Release\x64\DevToys.MonacoEditor\DevToys.MonacoEditor.winmd' could not be found
5>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
5>Done building project "DevToys.csproj" -- FAILED.
5>Done building project "DevToys.Startup.wapproj" -- FAILED.
========== Build: 2 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by x0341** [comment]
5>D:\DevToys\src\dev\impl\DevToys.MonacoEditor\ts-helpermethods\otherScriptsToBeOrganized.ts(1,21): error TS6053: Build:File 'D:/DevToys/src/dev/impl/DevToys.MonacoEditor/monaco-editor/monaco.d.ts' not found.

**Comment by veler** [comment]
Hi,
You may have missed an important step in the process. Please refer to the documentation here: https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md#how-to-build-and-run-devtoys-from-source
