### ISSUE TITLE
bcrypt generator

### ISSUE THREAD

**Issue by Tinipik** [veler/DevToys#707]
### What's the Problem?

Hi!

Use bcrypt.

DevToys is truly lacking a bcrypt generator tool, among the other hash generators. Offering a good variety of hashing functions has become critical. General purposes hashing functions are not sufficient anymore, and because DevToys seems to be popular, you need to encourage use of bcrypt.
Why bcrypt is so important: [Provos & Mazières paper](http://www.usenix.org/events/usenix99/provos.html)
C#/.NET bcrypt package with good support: https://github.com/BcryptNet/bcrypt.net

Use bcrypt.
Sinon très beau travail :)

### Solution/Idea

A new list item "bcrypt" is required among generators.
I thought it could be implemented directly into "Hash" subitem, alongside the other hash functions. However, bcrypt is known for introducing a **variable work factor** (the algorithm will proceed to 2^numberOfRounds iterations) This leads to introducing a "number of rounds" UI element which is not present on the other hash functions.

That's why a "standalone" bcrypt item is needed among generators. Plus there is no such HMAC or base64 encoding through bcrypt, because it's inevitably meant to protect passwords.

### Alternatives

There is no alternative.
Use bcrypt.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allowing end users to generate bcrypt hash | Must |
| Allowing end users to manipulate a "cost factor" integer parameter | Must |
| "Bcrypt" item will be found among generators | Should |
| Allowing users to switch between encrypt/decrypt | Should |
| Decrypt mode will allow users to test a Bcrypt hash against some text | Should |

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by veler** [comment]
Duplicate with #542
