### ISSUE TITLE
Copying not working

### ISSUE THREAD

**Issue by steveny9911** [veler/DevToys#709]
### Description

Copying any text does not actually copy the text

### Steps To Reproduce

https://user-images.githubusercontent.com/8460976/201259351-cab8f358-fac1-4504-b1ce-7395b9a58756.mp4

1. Use any tools
2. Attempt to copy any text in the text box
3. Use either the in-app "Copy" button
4. Or, use right click context menu "Copy" button
5. Text not actually copied

### Expected behavior

Copied text

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18; OS: 19045.2251 (can't copy from the about page)

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/9986316/logs.txt)

**Comment by itayweb** [comment]
I tried to reproduce but got it working, can you check again please? tried both latest commit and mentioned commit

**Comment by veler** [comment]
I can't reproduce it either :-/
