### ISSUE TITLE
Whitespace visualizer

### ISSUE THREAD

**Issue by Hugh1001** [veler/DevToys#719]
Hi, DevToys team. I am enjoying using your product and it would be very useful to add whitespaces visualizer for any content that can be simply copy pasted or downloaded by file. For example: green for tabs, red for whitespaces or customizable.

**Comment by veler** [comment]
This option in the settings can likely help.
It is also present in most IDEs and code editor like Visual Studio, Rider or Visual Studio Code.

![image](https://user-images.githubusercontent.com/3747805/226088521-e90aed54-b716-4f9d-b8d6-7905e3e7b5df.png)
