### ISSUE TITLE
[Feature Request] ASCII Table

### ISSUE THREAD

**Issue by gre99ory** [veler/DevToys#720]
Hello,

One thing I use from time to time is an ASCII lookup table when I have weird chararcters in my code or logs. 
Also ASCII => UTF-8 is of great use. I don't know how this can be implemented

See for example on https://www.asciitable.com/

Keep up the great work !

**Comment by jamescurran** [comment]
As late as Windows 10 (and maybe Windows 11, I haven't checked), Microsoft still includes the "Character Map" app, which handles much of that.

**Comment by veler** [comment]
Duplicate with #388
