### ISSUE TITLE
Update to CommunityToolkit.Mvvm Package

### ISSUE THREAD

**Issue by michael-hawker** [veler/DevToys#721]
### Description

Notice you're using the old `Microsoft.Toolkit.Mvvm` package. Should update and use the Source Generator goodness in the latest 8.1 version of the `CommunityToolkit.Mvvm` package, should cut down on a bunch of boilerplate too.

Also has better VS performance that old package's prior source generator implementation.

### Expected behavior

Use latest package.

### DevToys Version

N/A

### Relevant Assets/Logs

N/A

**Comment by veler** [comment]
Planning to do it at the occasion! :)

**Comment by veler** [comment]
Done in 2.0
