### ISSUE TITLE
Recently Used/Most Frequently Used Tool List

### ISSUE THREAD

**Issue by michael-hawker** [veler/DevToys#722]
### What's the Problem?

More often than not there's a set of tools that I use more often than others.

### Solution/Idea

Would be great to have a 'recently used' section at the top of the 'All tools' page which keeps track of the top X number of tools I've used last (or most frequently).

### Alternatives

https://github.com/veler/DevToys/issues/632

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to accomplish common tasks more easily | Must |
| This proposal will allow users to choose between recently used or most frequently used | Could |

### DevToys Version

1.0.10.0

### Comments

Related to https://github.com/veler/DevToys/issues/632 (improvements to All tools page)

**Comment by veler** [comment]
Done in 2.0 https://github.com/veler/DevToys/commit/1529311d7c8e6acce26a2756b3f8d173c4e62960
