### ISSUE TITLE
A timestamp in milliseconds

### ISSUE THREAD

**Issue by babyblue2** [veler/DevToys#725]
### What's the Problem?

The current timestamp function can only be accurate to the second.
I need a timestamp conversion that is accurate to milliseconds.

Thanks a lot.

### Solution/Idea

none

### Alternatives

none

### Priorities

none.

### DevToys Version

ver 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by vvshuai** [comment]
I always need this.

**Comment by veler** [comment]
Duplicate with #683
