### ISSUE TITLE
Favorite tools in the taskbar jump list

### ISSUE THREAD

**Issue by valhristov** [veler/DevToys#727]
### What's the Problem?

To use tools in DevToys I need to start the application, figure out the category, find the tool, then use it. Or type the tool name then use it... Generally OK, but can be better.

### Solution/Idea

Put configurable menu items in the taskbar jump list that when clicked open the GUI and directly navigate to the tool. This way the tools that I use the most will be two clicks away (right click DevToys, choose tool). Alternative would be to use MRU list, but configuration for favorites sounds better.

MS Teams has similar menu items in its jump list:
![image](https://user-images.githubusercontent.com/23195959/206665992-8bbf8cc3-1569-4b94-9d80-1403a051df98.png)

### Alternatives

Probably #722 or #632, but still somewhat different.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Configurable jump list items will allow end users to quickly open the tools they use most often | Must |

**Comment by veler** [comment]
Added to DevToys 2.0 :)

![image](https://github.com/veler/DevToys/assets/3747805/32b245c8-64dc-4162-9046-bf8a05fdd94c)
