### ISSUE TITLE
Add a Lorem Ipsum Generator tool

### ISSUE THREAD

**Issue by veler** [veler/DevToys#73]
**Is your feature request related to a problem? Please describe.**
As a web designer, I often need to show off some UI with some dummy text inside.

**Describe the solution you'd like**
Lorem Ipsum are usually used for this purpose. Let's add a Lorem Ipsum generator. it could have the following options:
- Choose between Words, Sentences, Paragraphs
- Choose the amount of Words/Sentences/Paragraphs

**Comment by ivankahl** [comment]
Hi @veler, can I take a look at implementing this feature?

**Comment by veler** [comment]
@ivankahl ,with pleasure! Feel free to go ahead.
FYI, we will release Devtoys version 1.0 mid January. We're bug bashing it at the moment and try to fix all the bugs. Meanwhile, if you develop this tool, we will publish it after 1.0. 😊

**Comment by ivankahl** [comment]
Great thanks! I've completed the work and created a PR (#130). I hope that is fine? Then we can merge the PR after version 1.0?

**Comment by veler** [comment]
Hi @ivankahl  and happy new year!
Thank you so much for this! :D I will take a look at it
