### ISSUE TITLE
Make Markdown Preview render Front matters

### ISSUE THREAD

**Issue by GarytheNoob** [veler/DevToys#733]
### What's the Problem?

The *Markdown Preview* Module is described as a *GitHub-like render*, but it goes wrong when rendering Front matters.
Front matters in GitHub will be rendered as tables. You can see what it is like [here](https://github.com/GarytheNoob/testFileLab/blob/main/markdown/GitHub-style_render.md).

### Solution/Idea

Let the Module render Front matters properly - just like GitHub.

### Alternatives

Convert Front matter to table when rendering. Or even preserve it as code block in yaml.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| The renderer will be able to render Front matters correctly | Must |
| There will be a option to let the users decide whether to render the front matters | Should |
| Preserve the Front matters and render them as code blocks | Could |

### DevToys Version

Version 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by veler** [comment]
Hi,

Thanks for reporting this!

Note to myself:
Check out https://github.com/xoofx/markdig/issues/579
It seems like updating MarkDig NuGet package and adding `UseYamlFrontMatter` may address the issue.
