### ISSUE TITLE
DevToys CLI

### ISSUE THREAD

**Issue by veler** [veler/DevToys#739]
### What's the Problem?

As a developer, I often use command line prompt. Sometimes, I need to do a quick conversion and grip it to another command in a CLI.

### Solution/Idea

Make a command line version of DevToys. This can be useful for:
1. A first Linux and MacOS version
2. DevOps (when making a CLI, perhaps I could use DevToys CLI to automatically decode some Base64, minimize a JSON...etc)
3. Simply users who are more used to command prompt
4. Delivering a DevToys build that doesn't require the MS Store.

### Alternatives

N/A

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Compatible Linux, MacOS and Windows | Must |
| Extensible | Could |

### Comments

There's already a prototype here: https://github.com/veler/DevToys/tree/dev/2.0/src/app/dev/platforms/DevToys.CLI

**Comment by PurplProto** [comment]
It would be awesome if there was some `jq` like functionality with this.

**Comment by PurplProto** [comment]
On second thought, it's actually probably a bit overkill for a small dev utils app. A terrible suggestion on my part 😅 

But to answer your question, [jq](https://stedolan.github.io/jq/) is a CLI tool for parsing and selecting data out of JSON strings. Rather useful on occasion!

**Comment by veler** [comment]
Oh I see! Thanks for explaining this 😁 
Indeed, it might be a bit overkill.

**Comment by Antebios** [comment]
> On second thought, it's actually probably a bit overkill for a small dev utils app. A terrible suggestion on my part 😅
> 
> But to answer your question, [jq](https://stedolan.github.io/jq/) is a CLI tool for parsing and selecting data out of JSON strings. Rather useful on occasion!

It would be GREAT to have a 'jq' utility to have a text area to paste in JSON, then have another text box to enter your 'jq' expression and see if it works.
