### ISSUE TITLE
Add an XML Formatter tool

### ISSUE THREAD

**Issue by veler** [veler/DevToys#74]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm dealing with some XML text that isn't formatted.

**Describe the solution you'd like**
Add an XML Formatter, like JSON Formatter.

**Comment by jwfxpr** [comment]
> Yes please. With an option for indenting or not indenting multi-line inner text. Eg,

```xml
<Element>
    <Element>This is an
Inner text with
Several lines
    </Element>
<Element>
```

Vs:

```xml
<Element>
    <Element>This is an
        Inner text with
        Several lines
    </Element>
<Element>
```

**Comment by rdeveen** [comment]
Hi @veler, I started creating a XML Formatter for this toy, https://github.com/rdeveen/DevToys/commit/4a4303c8ca712bb8409ced585f4fbf387759799f

**Comment by veler** [comment]
That looks awesome!
