### ISSUE TITLE
Timestamp does not support milliseconds.

### ISSUE THREAD

**Issue by lololololkl** [veler/DevToys#740]
### What's the Problem?

When a 13-digit timestamp is entered, you are prompted to enter an invalid value. If you want to use it normally, you should delete the last three digits.

### Solution/Idea

Adapt to the 13-bit timestamp, accurate to milliseconds.

### Alternatives

The time stamp is obtained by Java program, but it is 13 bits.

### DevToys Version

1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

**Comment by hawkerm** [comment]
Duplicate #725

**Comment by dzienki** [comment]
also need that!

**Comment by veler** [comment]
Duplicate with #683
