### ISSUE TITLE
flash back when open Encoders/Decoders

### ISSUE THREAD

**Issue by 414613398** [veler/DevToys#742]
### Description

open Encoders/Decoders class **base64 text**, the program immediately crash back.
(Although I have rarely to use this, but seeing this is bug all the time display。）

### Steps To Reproduce

go to Encoders/Decoders

### Expected behavior

fix it and thank you.

### DevToys Version

版本 1.0.10.0 | X64 | RELEASE | b949a18 | b949a18

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/10383827/logs.txt)

**Comment by dawoe** [comment]
I have the same issue

**Comment by veler** [comment]
Duplicate with #757
