### ISSUE TITLE
JSON path test

### ISSUE THREAD

**Issue by Haingue** [veler/DevToys#749]
Could you please add a window to test/find a JSON path ?
One bloc to import/copy a JSON content, one bloc to write a JSON path and one bloc to show the result.
Something like that: https://jsonpath.com/

**Comment by almostSouji** [comment]
Was just about to suggest that after playing around with [insomnia](https://insomnia.rest/)'s jsonpath explorer (they use <https://github.com/JSONPath-Plus/JSONPath>) for a project. It's so useful! Being able to quickly stuff my json data into devtoys (potentially with parsing from raw js objects to proper json syntax, for added coolness points) and querying/exploring them with JSONpath would be amazing!

**Comment by veler** [comment]
Added to DevToys 2.0
