### ISSUE TITLE
Add the possibility to Favorite / Unfavorite a specific tool

### ISSUE THREAD

**Issue by veler** [veler/DevToys#75]
**Is your feature request related to a problem? Please describe.**
We're adding more and more tools and at some point it might become difficult to find them in the menu as the list grow.

**Describe the solution you'd like**
Add a way to hide / show a tool. For this, we could:
- Add a "Hide this tool" context menu to each tool item in the menu.
- When one or more tools are hidden, a new item "More tools" would appear just above the "Settings" menu. 
- Clicking on it would show a flyout allowing to
  - Navigate to one of the hidden tool.
  - Bring a tool back to the main menu.

**Comment by Arlodotexe** [comment]
Two more possible options:
- A "Frequents" or "Recents" list, like the Windows Community Toolkit sample app has
- Allow the user to "Pin" or "Favourite" tools in-app for easy access later.

**Comment by Arlodotexe** [comment]
Might be a good idea to investigate doing the full-page view mentioned in #88 to get tool organization down

**Comment by veler** [comment]
Great idea for the "Frequents" or "Recent" list !

**Comment by veler** [comment]
Hum, thinking more about this: of course, it would be nice that the pinned, recent list, list of hidden tools...etc were persisted and roamed so every machine of the users would have the same configuration. However, roaming settings are deprecated and we're trying to avoid the `internet` capability as much as possible.
Therefore, in term of priority, we should probably figure out this issue first: #81
