### ISSUE TITLE
Option to prettify the content in Text Diff

### ISSUE THREAD

**Issue by Vijay-Kumar-intelliflo** [veler/DevToys#752]
### What's the Problem?

While comparing JSON file (Unformatted), it's difficult to spot the differences. So, I have to first format the data using JSON formatter and then, use Text Diff to compare them. 

### Solution/Idea

Providing Formatter option on Text Diff also, which will prettify the content into the required format.

### Alternatives

Providing "JSON Diff" feature

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish ,comparing unformatted JSON text| Must |

**Comment by veler** [comment]
Related to #737
