### ISSUE TITLE
Addons / Extensions

### ISSUE THREAD

**Issue by cloudfy** [veler/DevToys#756]
### What's the Problem?

As a developer I would like to contribute but not change the whole application. I would like to built plugins/extensions/addons as a community.

### Solution/Idea

Build a MEF alike integration plugin architecture where I can add my own plugin. Example I would like to make JSON > C# converter, as an add-on.

### Alternatives

Add too many features to the product.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Hi,
Thanks for sharing. This is duplicated with #146
