### ISSUE TITLE
World Clock + Time Zones + Time Converter

### ISSUE THREAD

**Issue by shahmitan** [veler/DevToys#760]
### Solution/Idea

World Clock + Time Zones + Time Converter

### Alternatives

World Clock + Time Zones + Time Converter

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
This can be done online easily, and I don't feel like there's a privacy risk at doing it online. Therefore it feels invalid for DevToys. 
Also, I think the Clock app pre-installed with Windows can do this.
