### ISSUE TITLE
It is hard to know what the Text Escape/Unescape tools is used for

### ISSUE THREAD

**Issue by esp0** [veler/DevToys#762]
### What's the Problem?

When opening the app, it is hard to know what the escape-tool should be used for. What characters are escaped? Is it for pasting/parsing code that goes in a HTML-comment? In Json? In C#? In yaml? A Uri?

### Solution/Idea

Allow the user to select what kind of language/escaping they want the text to be escaped for.

### Alternatives

Describe what language/area the escape tool is used for at the moment.

**Comment by yatlor** [comment]
I completely agree.  There is no description on the screen.  And the description on the home screen is cut off "Escapes or unescapes a string, removing characters that could..."     Could what?

**Comment by meblum** [comment]
So, what does it actually do?
