### ISSUE TITLE
Minifier tools

### ISSUE THREAD

**Issue by kyrollos-saad** [veler/DevToys#766]
### What's the Problem?

lack there of

### Solution/Idea

minifier for everything.
obviously JS and popular languages. but also rule-based minifiers for any text (trim extra spaces, remove \n and \r\n, etc...)

### Alternatives

vscode's regex find and replace

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by veler** [comment]
Duplicate with #556
