### ISSUE TITLE
Image to text converter (OCR)

### ISSUE THREAD

**Issue by bvtvusn** [veler/DevToys#784]
### What feature or new tool do you think should be added to DevToys?

I suggest a tool that can analyze a picture and print out the text it contains.

### Why do you think this is needed?

Optical character recognition is useful because not every text inside a computer is possible to select and copy.
For example error messages in a text box is usually not possible to copy.

### Solution/Idea

The GUI becomes as simple as it gets.
A feature like snipping tool for retrieving the picture would be extra useful!

**Comment by veler** [comment]
Note that PowerToys already has such a tool. Let's avoid duplicating their work. :)

**Comment by pmestrum** [comment]
I have a mac, so I dont have powertoys, and I would find this feature very handy.
