### ISSUE TITLE
socket client

### ISSUE THREAD

**Issue by qzwzqty** [veler/DevToys#793]
### What feature or new tool do you think should be added to DevToys?

- tcp client
- udp client
- mqtt client
- websocket client

### Why do you think this is needed?

Integration of socket client is useful for developing socket services.

**Comment by veler** [comment]
Hi,
Thanks for the suggestion. If I'm not wrong, this would require an internet connection, which DevToys tries to avoid relying on. If that's the case, then it isn't a great fit for this app.
