### ISSUE TITLE
Upgrade to Chocolatey package v1.0.11 failing

### ISSUE THREAD

**Issue by brogers5** [veler/DevToys#794]
### Current behavior

devtoys package v1.0.11, as currently published on the Chocolatey Community Repository, currently points to v1.0.9.0 of DevToys.

This causes a package upgrade from v1.0.10.0 to fail, because a newer version of DevToys is currently installed.

### How to reproduce it (as minimally and precisely as possible)

1. `choco install devtoys --version=1.0.10.0 --source="'https://community.chocolatey.org/api/v2'"`
2. `choco upgrade devtoys --source="'https://community.chocolatey.org/api/v2'"`

### Expected behavior

devtoys package v1.0.11 should consume version 1.0.11.0 of DevToys instead of v1.0.9.0.

A [package fix version](https://docs.chocolatey.org/en-us/create/create-packages#package-fix-version-notation) will need to be published to correct the issue.

I would also recommend unlisting the current v1.0.11 package to help avoid future failures.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.10.0

### Relevant Assets/Logs

[chocolatey.log](https://github.com/veler/DevToys/files/11191338/chocolatey.log)

**Comment by veler** [comment]
Hi,
Good catch! Thank you very much for reporting this issue and sorry for the inconvenience. 
I indeed made a mistake...

I pushed a new version `1.0.11.20230410`. It should be available within a few hours.

![image](https://user-images.githubusercontent.com/3747805/230931338-d90ca6e3-620b-4131-bdf8-5f890f90f113.png)
