### ISSUE TITLE
Markdown Preview - Add a "Copy as formatted text" button

### ISSUE THREAD

**Issue by o-l-a-v** [veler/DevToys#795]
### What improvement do you think would an existing feature or tool in DevToys?

The "Markdown Preview" feature is great. I write all my notes in markdown, then I use DevToys for documentation systems that does not support raw paste of markdown, like PerfectWiki for instance.

Currently the "Copy" button copies the text as HTML. While selecting the text manually and then copying it gives me a formatted text that can be pasted straight into PerfectWiki (for instance).

![image](https://user-images.githubusercontent.com/6450056/231436004-829c8a08-6dab-42a7-894b-5ee3d289825c.png)

### Solution/Idea

1. Add a button "Copy as formatted text" which gives the same as selecting the preview text manually.
2. Consider renaming the existing "Copy" button to "Copy as HTML".
  * Or maybe add a dropdown? "Copy as ⮟", with a list of options.

**Comment by michael-hawker** [comment]
Related to #177 as well about converting between formats, like copying HTML version of Markdown.
