### ISSUE TITLE
Go back to list of tools on "Back" mouse button click

### ISSUE THREAD

**Issue by Kenya-West** [veler/DevToys#797]
### What improvement do you think would an existing feature or tool in DevToys?

I want to go back to the list of tools when I just open the tool and did not do anything in there.

### Solution/Idea

By pressing the "mouse 4" button (that usually on left side for right-handed people) you will go back to the list of tools, if you just opened a tool and did not do anything in it.

**Comment by veler** [comment]
Done in DevToys 2.0
