### ISSUE TITLE
program is unresponsive and crashes

### ISSUE THREAD

**Issue by msglog** [veler/DevToys#799]
### Current behavior

故障存储段 1388079232669899527，类型 5
事件名称: POFContextAppCrash
响应: 不可用
Cab ID: 0

问题签名:
P1: 64360VelerSoftware.DevToys_1.0.11.0_x64__j80j2txgjg9dj
P2: praid:App
P3: 1.0.11.0
P4: 0x80070005
P5: 184640e968c9d20c070ae4c312b44028

### How to reproduce it (as minimally and precisely as possible)

Use base64text before  base64images
![debug](https://user-images.githubusercontent.com/34530046/232126569-451b5fd3-1aac-4444-a2be-21f56f9db045.gif)

### Expected behavior

Switch function, the program can not crash

### Screenshots

![debug](https://user-images.githubusercontent.com/34530046/232126618-c99bf878-f95f-4c1f-9b51-3deb113af5e8.gif)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.11.0

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/11236019/logs.txt)

**Comment by veler** [comment]
Duplicate with #755
