### ISSUE TITLE
Program Crash when trying to use Base64 Text Encoder/Decoder

### ISSUE THREAD

**Issue by shad-1** [veler/DevToys#802]
### Current behavior

Windows 11. 
I open a fresh instance of the program and navigate to Encoders/Decoders. I can select every page except "Base64 Text". Whenever I choose that page, it loads and closes the window after about 1s. 

### How to reproduce it (as minimally and precisely as possible)

1. Go to Encoders/Decoders
2. Choose "Base64 Text"
3. Window closes

### Expected behavior

The window should not close.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.11.0 | X64 | RELEASE | 2b57a920 | 2b57a920

**Comment by veler** [comment]
Duplicate with #692
