### ISSUE TITLE
let user define newline character in text escape (also bugged?)

### ISSUE THREAD

**Issue by Disservin** [veler/DevToys#807]
### What improvement do you think would an existing feature or tool in DevToys?

When having a text with linebreaks like this
```
Hello
World
```

the escaped text will be
```
Hello\rWorld\r
```

now that I look at it again it's not even correct windows linebreaks (my platform), for windows it should be `\r\n`.

It would be great to have a toggle button to toggle between unix and windows line breaks.

### Solution/Idea

A toggle button to switch between unix and windows linebreaks.

**Comment by JaiganeshKumaran** [comment]
> now that I look at it again it's not even correct windows linebreaks (my platform), for windows it should be \r\n.
The reason for this is Windows text boxes use only carriage return even though carriage return + line feed is used for text files.

**Comment by veler** [comment]
Duplicate with #468

**Comment by Disservin** [comment]
Oh sorry somehow missed that there’s already one issue…
