### ISSUE TITLE
Roaming settings are deprecated

### ISSUE THREAD

**Issue by veler** [veler/DevToys#81]
**Describe the bug**
As mentioned here: https://docs.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data

![image](https://user-images.githubusercontent.com/3747805/143691032-764b09f4-53af-4a60-9cd4-491b36cb9f0c.png)

**Solution proposal**

As a reminder, we're trying to avoid using the "internet" capability of the app, so users can "trust" this app for not sending anything over internet by default.

1. Don't use Roaming settings
    - Pros:
        - No need of the "internet" capability in the app.
        - Cheap to fix.
    - Cons:
        - Less convenient for users
        
2. Make a custom prompt asking the user whether he wants to use internet features or not. Then use OneDrive integration or Azure App Service to synchronize settings.
    - Pros:
        - Not too complicated to implement
    - Cons:
        - Requires some new nuget package, increasing the size of the app package
        - Internet capability is required even if user doesn't use internet features.
        
3. Use an app add-on
    - Pros:
        - (to verify) The basic DevToys app won't need the internet capability.
        - User can optionally install an add-on that brings internet features, like roaming settings or tools that need internet.
    - Cons:
        - This will likely increase the complexity of the app.
        - We will probably need to "advertise" these add-on into the app, and users may be frustrated by what looks like a jerky app displaying ads.

4. Add an Export/Import button like in the app Files https://www.microsoft.com/store/productId/9NGHP3DX8HDX
    - Pros:
        - User can export the settings and import them on another machine.
        - No need of `internet` capability.
    - Cons:
        - User must do it manually.

**Comment by xeonmc** [comment]
I think for a "lightweight offline app" like these, generally the user would expect a predictable initial state in any fresh installations. I think that is the main motivation behind MS removing roaming profiles for UWP as well, because typically people expect "a simple UWP utility" not to have any statefulness between machines. Therefore it is a standard expectation that configuration states are self-contained and manually transferred.

**Comment by jwfxpr** [comment]
> Therefore it is a standard expectation that configuration states are self-contained and manually transferred

I agree, for a tool aimed at developers who are used to configuring a development environment to suit a purpose, I would expect to manually transfer configuration — and I would expect an easily readable and editable file, to customise config before importing if necessary.

**Comment by veler** [comment]
Super low priority and no good option at the moment. Closing for now.
