### ISSUE TITLE
the program crash when navigating the side menu.

### ISSUE THREAD

**Issue by BlueGreenWorld** [veler/DevToys#823]
### Current behavior

the program crash when navigating the side menu.

### Expected behavior

please don't crash

### Screenshots

https://github.com/veler/DevToys/assets/3757617/2e4c9dd7-9280-4b62-882d-c3fde404c8c0

### Workaround

https://github.com/veler/DevToys/assets/3757617/3ac5f89d-cb60-499b-a981-c0efc7ecd39c

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.12.0 | X64 | RELEASE | 94bb8213 | 94bb8213

**Comment by veler** [comment]
Duplicated with #757
