### ISSUE TITLE
Human-readable description of cron expression

### ISSUE THREAD

**Issue by micahmo** [veler/DevToys#829]
### What improvement do you think would an existing feature or tool in DevToys?

I really love the cron parser tool, thanks @DotNetInAction and @veler!

I was wondering if the output could contain a human-friendly description of the expression.

Here are some examples from [crontab.guru](https://crontab.guru/).
* `5 0 * 8 *`: "At 00:05 in August."
* `15 14 1 * *`: "At 14:15 on day-of-month 1."
* `0 22 * * 1-5`: "At 22:00 on every day-of-week from Monday through Friday."

### Solution/Idea

I find that having a human-readable description of the cron expression helps me to understand what it means, more than the "next" occurrence (although that's equally useful!).

### Comments

Possible help from the [cron-expression-descriptor](https://github.com/bradymholt/cron-expression-descriptor) library.

**Comment by micahmo** [comment]
I am currently working on this using [cron-expression-descriptor](https://github.com/bradymholt/cron-expression-descriptor). It's working well, but I hit a snag with their library which I'm trying to fix over there: bradymholt/cron-expression-descriptor#164

Here's a sneak preview:

| ![JINvjlBVrM](https://github.com/veler/DevToys/assets/7417301/d851bebb-a830-4d66-bddb-732c0354673b) |
| - |

**Comment by DotNetInAction** [comment]
Oh wow this looks cool! So glad to see people are actually using it!

**Comment by micahmo** [comment]
#839
