### ISSUE TITLE
Feature Request: Visualize tabular JSON data

### ISSUE THREAD

**Issue by stamminator** [veler/DevToys#832]
### What feature or new tool do you think should be added to DevToys?

I frequently use http://json2table.com/ to quickly visualize JSON data in a table view.

![Fl5kzZ9z0U](https://github.com/veler/DevToys/assets/10633170/4f41af59-7081-4332-acf4-48088c72f8d8)

Unfortunately, between the site having no SSL certificate in place (`http://` only) and it not being obvious whether or not the operation is happening completely client-side, there's always the possibility of sensitive data being exposed. Also, as simple as the UI is, it can be a little clunky and buggy.

I think this would be a great fit for DevToys. If people find this useful, XML support might also be considered.

### Why do you think this is needed?

Visualizing structured JSON data can be very handy during rapid prototyping and in general.

**Comment by veler** [comment]
Duplicate with #200 and done in #1003
