### ISSUE TITLE
Unix-Windows Path Converter

### ISSUE THREAD

**Issue by jonashoelzel** [veler/DevToys#838]
### What feature or new tool do you think should be added to DevToys?

Convert Unix slashes to backslashes for Windows and vice versa. And add a button to escape the backslashes.

### Why do you think this is needed?

When editing configuration files.

**Comment by Regenhardt** [comment]
Unix doesn't use a letter as root (e.g. C;), so the tool could also convert the windows root to `/mnt/c`, unless there's a use case where unix casing needs the windows root?

**Comment by jonashoelzel** [comment]
I think /mnt/c would be more useful especially for WLS.

**Comment by veler** [comment]
Duplicate with #682
