### ISSUE TITLE
Better multilingual support

### ISSUE THREAD

**Issue by kitswas** [veler/DevToys#852]
### What improvement do you think would an existing feature or tool in DevToys?

There are no Bengali (বাংলা) translations.

### Solution/Idea

Add Bengali to the list of languages on CrowdIn. This will allow translators to work on it.

### Comments

![image](https://github.com/veler/DevToys/assets/90329875/3cd1690b-2393-4d3e-a89c-9bb7a5fb428a)

**Comment by veler** [comment]
Hi,
Thanks for this. I added the language.
