### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by diftechservices** [veler/DevToys#866]
### What feature or new tool do you think should be added to DevToys?

I use both PC and Mac in my development efforts. I bring my Mac when I travel so I can't use DevToys. I'd love to see a Mac version. Any chance one is coming soon?

### Why do you think this is needed?

It's a great tool and I'd love to see a Mac version.

**Comment by veler** [comment]
Mac version is actually a work in progress 😁
Duplicate with #156

**Comment by veler** [comment]
We're hoping for a beta in Fall 2023
