### ISSUE TITLE
Certificate Encoder/Decoder should be able to open certificates with .crt extension

### ISSUE THREAD

**Issue by omasseau** [veler/DevToys#874]
### What improvement do you think would an existing feature or tool in DevToys?

Many certificates have the .crt extension (which is a valid extension for certificate - Windows recognize it)  instead of the .cer extension.
DevToys refuses to open .crt files.
To be able to open them the .crt extension has to be manually renamed to .cer.

### Solution/Idea

DevToys should accept to open .crt files.

**Comment by veler** [comment]
Hi,
Very good point on this, thank you for sharing this feedback. This will be addressed :)
