### ISSUE TITLE
BlazorWebView shows a white line when having a Margin of 2px

### ISSUE THREAD

**Issue by veler** [veler/DevToys#878]
### Current behavior

![image](https://github.com/veler/DevToys/assets/3747805/3dca78cd-0b2e-44b4-bae6-8690862efcf6)

![image](https://github.com/veler/DevToys/assets/3747805/30c275f3-8169-4704-93d3-d19c230b00da)

### Expected behavior

No white line.

### Workaround

Set a margin of `20px`, `200px` or `0px` (for example).

![image](https://github.com/veler/DevToys/assets/3747805/ef11f6ae-2555-4f5f-b57d-32dd79eb40c8)

![image](https://github.com/veler/DevToys/assets/3747805/be5994c3-e660-4b8b-90cd-3d1bf83e8a56)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0

**Comment by niyari** [comment]
@veler 
We are currently testing the usability of the app from a user's perspective.
Even in the current build, if the margins are restored, will this white line be displayed?

**Comment by veler** [comment]
> @veler 
> 
> We are currently testing the usability of the app from a user's perspective.
> 
> Even in the current build, if the margins are restored, will this white line be displayed?

I believe, yes.

**Comment by niyari** [comment]
@veler It happened again in the https://github.com/DevToys-app/DevToys/commit/ee85fda03c33192988d2be49c16aa5760508f000 build.


https://github.com/user-attachments/assets/a3784395-534b-45aa-9761-ab97518d48ba
