### ISSUE TITLE
Restructure the main menu into a hierarchical presentation

### ISSUE THREAD

**Issue by veler** [veler/DevToys#88]
**Is your feature request related to a problem? Please describe.**
The following is quite redundant:
![image](https://user-images.githubusercontent.com/3747805/144130702-68b8a860-7d8f-442e-9399-8058277bfed5.png)

**Describe the solution you'd like**
Perhaps we should make a hierarchical menu. For example
- Encoder / Decoder
| - Base 64
| - HTML
| - URL
...etc

**Comment by Arlodotexe** [comment]
To keep room for future tools and possibly specialized ones, I'm thinking something like:
```
Cryptography
- Encode / Decode
   - Base 64
   - HTML
   - URL
- JWT Decoder
- Hash generator

Data
- UUID Generator
- Json <> Yaml

Text
- Formatters
   - JSON Formatter
- Regex Tester
- Markdown preview
- String Utilities (Possibly rename?)
- Text Diff

Media
- Image compressor
```

**Comment by veler** [comment]
Thank you very much @Arlodotexe for this suggestion. I like that a lot, along with the idea of a full page view.

**Comment by sylveon** [comment]
Encoding has nothing to do with cryptography. It will be hard for most users to find these if they are nested under cryptography.

**Comment by veler** [comment]
What about this:

```
Converters
 - JSON to Class (upcoming tool)
 - JSON <> YAML
 - Number Base
 - SVG to XAML (upcoming tool)

Encoder / Decoders
 - HTML
 - URL
 - Base64
 - JWT Decoder

Formatters
 - JSON
 - XML (upcoming tool)

Generators
 - Hash
 - UUID
 - Lorem Ipsum (upcoming tool)

Text
 - String Utilities (to be renamed)
 - Regex Tester
 - Text Diff
 - Duplicated Code Checker (upcoming tool)
 - Markdown Preview

Graphic
 - PNG / JPEG Compressor
 - Color Picker (upcoming tool)
 - Color contrast checker (upcoming tool)
```

**Comment by Arlodotexe** [comment]
@veler Looks good to me!
