### ISSUE TITLE
Regex Tester: Not matching correctly, Sql Select

### ISSUE THREAD

**Issue by horvaro** [veler/DevToys#885]
### Current behavior

Using the Regex Tester to find a simple regex for a SQL select statement.
I settled for `^(SELECT|select)\s.*\s(FROM|from)\s.*\s(WHERE|where)(\s.*\s=\s.*\s)*$` with the follwoing test data:
```
SELECT * FROM system:objects WHERE tag = 5
select city from system:objects WHERE name = 'name'
select city from system:objects WHERE name = 'name' and tag = 0
select name from table where
select name from table where 
```

The first three lines match. The two last ones dont.

### How to reproduce it (as minimally and precisely as possible)

Open the Regex Tester.
Paste above mentioned regex.
Paste above mentioned test data.
First three lines match.

### Expected behavior

None of the lines should match. I ran my code with that regex, and everything failed.
I cross-checked the Regex with regex101.com and found out that the regex tested in DevToys should not work.
The correct regex is: `^(SELECT|select)\s.*\s(FROM|from)\s.*\s(WHERE|where)\s(.*=\s.*)+$`

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.12.0 | X64 | RELEASE | 94bb8213 | 94bb8213

**Comment by veler** [comment]
Hello,

From my understanding (please correct me if I'm wrong), when checking "Global" in Regex101, we get the same result than in DevToys, and DevToys behaves like if this Global option was checked.

When this Global option is unchecked, Regex101 only matches the first line. Do you know if you had this option checked on regex101.com?

![image](https://github.com/veler/DevToys/assets/3747805/4d86a78a-1b70-4ba4-bb1c-3b1412dc6100)

I admit that in DevToys, it is not clear what behavior is expected. I'm planning to add this option in DevToys 2.0 (I'm currently working on it).

Thanks

**Comment by horvaro** [comment]
Yes, I ran it with global and multiline enabled. I also enabled multiline in DevToys.
The issue is with the first Regex, which I thought would work, because of the feedback from DevToys:

`^(SELECT|select)\s.*\s(FROM|from)\s.*\s(WHERE|where)(\s.*\s=\s.*\s)*$`
![image](https://github.com/veler/DevToys/assets/25514272/d3b5e6e2-0c1b-47b2-a9ec-d6b7f1a000bd)

The same Regex (`*$` at the end) gives truly another result on regex101:
![image](https://github.com/veler/DevToys/assets/25514272/85c6efa6-a171-4aaa-995d-19edc35865ce)


After I corrected the Regex on regex101 (`+$` at the end) the output is the same:
![image](https://github.com/veler/DevToys/assets/25514272/aae790b1-40d2-4cad-844e-7e4f8327e96b)

![image](https://github.com/veler/DevToys/assets/25514272/ad7dfb19-4da2-4c39-929e-ed921f54b10d)

**Comment by veler** [comment]
That is quite interesting! Thanks for sharing!

**Comment by veler** [comment]
So, here is some good news 😁
I'm currently porting the RegEx Tester tool to DevToys 2.0, and I think I'm doing it better. 

First, the regex that was producing some odd highlighting compared to Regex101.com now behaves as on Regex101:

![image](https://github.com/veler/DevToys/assets/3747805/ca53df9a-8f72-43be-830c-aa31a8570e58)

Second, I added some colors to make the matches easier to group.

![image](https://github.com/veler/DevToys/assets/3747805/7b5cfdad-6f9f-429d-a90d-e70a64746b3e)

Does that look better?

**_Please note that this is a work in progress though. It's not done._**

**Comment by horvaro** [comment]
Thank you very much for sharing!
Yes, that looks indeed promissing 👍
I am looking forward to the release 2.0
