### ISSUE TITLE
Font Size / Ctrl + mouse Scroll

### ISSUE THREAD

**Issue by Bahaa-Sobhy** [veler/DevToys#891]
### What improvement do you think would an existing feature or tool in DevToys?

Some users - including me - like to user QHD and 4K screens, while setting the Display Scale at 100% or 125%, in such scenario the text of the GUI is too small.

### Solution/Idea

I see in the Application settings that you have the option to change the font-family, it would be further flexible to add the option to change the text size, even better to add also `CTRL` + `Scroll` to zoom in/out as web browsers.

these two options became basics nowadays in modern applications.

**Comment by veler** [comment]
Done in DevToys 2.0. We can now zoom in every multi-line text editor using F1 key.
