### ISSUE TITLE
Text separated by comma or other "Separator"

### ISSUE THREAD

**Issue by estibent10** [veler/DevToys#892]
### What feature or new tool do you think should be added to DevToys?

**1. Allow to user do following:**

_**input:**_
id,CompanyName,CreatedDateTime,DisplayName,EmployeeId,JobTitle,LastPasswordChangeDateTime

_**output:**_
id
CompanyName
CreatedDateTime
DisplayName
EmployeeId
JobTitle
LastPasswordChangeDateTime

**2. Allow to user:**

**Specify a separator by default**

### Why do you think this is needed?

Use it to get clear view of the URL parameters in APIs and others scenarios in texts that use separators.

### Solution/Idea

Use String Split.

**Comment by veler** [comment]
Hi,
I think it's also possible to use Excel to do that 🤔
