### ISSUE TITLE
Password generator similar characters

### ISSUE THREAD

**Issue by simondforrester** [veler/DevToys#905]
### What improvement do you think would an existing feature or tool in DevToys?

Great password generator, but it could use an option to remove identical-looking characters.

### Solution/Idea

To expand: a switch to avoid upper-case O, zeroes, ones, lower-case L, upper-case I, pipes, etc.

Because: OIl0 is very different to 0lIO.

**Comment by notcooler** [comment]
I think i can add that, you mean charcters to exclude from the password generation right?

**Comment by simondforrester** [comment]
Absolutely - to avoid outputting those characters altogether, for the avoidance of confusion. It's rare anyone has to type a password from sight, but it happens occasionally, and the even the best of us get caught out by similar-looking characters.
