### ISSUE TITLE
Suggestions for string utility functions

### ISSUE THREAD

**Issue by kristinmartin3702526** [veler/DevToys#909]
### What feature or new tool do you think should be added to DevToys?

The string utility tool has added functions such as clearing spaces, line breaks, symbols, and the use of conversion functions such as converting spaces to underscores and humps to underscores

### Why do you think this is needed?

Some scenarios have this requirement

**Comment by veler** [comment]
Hi,
Can't this be done with a simple NotePad or VS Code or similar by using the Replace feature (Ctrl+H) ?
