### ISSUE TITLE
Add a notebook

### ISSUE THREAD

**Issue by glennwiz** [veler/DevToys#918]
### What improvement do you think would an existing feature or tool in DevToys?

A place to put notes and code blocks, strings and stuff for later use and lookup

### Solution/Idea

Adde a way to store text, maybe in json. Just a .json file located at app install folder, and a frontend menu you can add and retrive such notes.

**Comment by veler** [comment]
Hi @glennwiz ,

Thanks for this idea. I'm trying to understand your need around Regex Tester. What kind of things do you Google usually? Are you ultimately looking for a cheat sheet that would explain the various syntax to create a RegEx?

**Comment by glennwiz** [comment]
Hi @veler , yes, that was exsacly what i was googling the cheat sheet for regex.

**Comment by veler** [comment]
Awesome, then it's already in our backlog and planned for DevToys 2.0 :-)
See #736
