### ISSUE TITLE
Sort lines of text logical

### ISSUE THREAD

**Issue by pengweiqhca** [veler/DevToys#921]
### What feature or new tool do you think should be added to DevToys?

Sort lines of text logical

### Why do you think this is needed?

Sort lines of text logical

### Solution/Idea

https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcmplogicalw

**Comment by veler** [comment]
Hi,
You can already do this in DevToys 1.0.13.0 :-)

![image](https://github.com/veler/DevToys/assets/3747805/55a12d0f-5d35-4c5e-8371-aabb3d5f3d14)

**Comment by pengweiqhca** [comment]
Not Alphabetize.
```
20string
2string
3string
st20ring
st2ring
st3ring
string2
string20
string3
```
Logical sort is:
```
2string
3string
20string
st2ring
st3ring
st20ring
string2
string3
string20
```
