### ISSUE TITLE
The new feature helps to convert XML ↔️ JSON

### ISSUE THREAD

**Issue by tienduoc** [veler/DevToys#933]
### What feature or new tool do you think should be added to DevToys?

Convert XML to JSON and back

### Why do you think this is needed?

Nowadays XML and JSON are popular in development, XML is often used in the backend and JSON is often used in the frontend. And the convert feature is very useful for developers, especially those who work in full-stack

**Comment by Regenhardt** [comment]
What to do with xml attributes, i.e. how to convert something like this to json?  
Do we need a warning or something that json doesn't have comments?  
How to handle mixed content?

```xml
<!-- Example XML -->
<tag usage="Convert this to json">
  <innerTag>
    Some content in here
  </innerTag>
  Also some mixed content in this outer tag, does the json get a "content" property?
  <content>
    Then what happens to this text?
  </content>
</tag>
```

**Comment by veler** [comment]
Agreed with @Regenhardt , it doesn't seem quite compatible.
