### ISSUE TITLE
Make this a VSCode extension

### ISSUE THREAD

**Issue by mikenelson-io** [veler/DevToys#935]
### What feature or new tool do you think should be added to DevToys?

Nothing new, just an alternate way to use the code.

### Why do you think this is needed?

Integrate it with one of the most popular IDE's for scripters and coders alike - VSCode. Easy to port and would provide good added functionality.

### Solution/Idea

Offer the app as an installable extension to VSCode.

**Comment by veler** [comment]
Hi,
That's something we're considering but isn't a goal for the next 1-2 years.
