### ISSUE TITLE
Publish MSI files in release

### ISSUE THREAD

**Issue by MiniMarker** [veler/DevToys#939]
### What feature or new tool do you think should be added to DevToys?

As of today, the only built file published in releases are a .msixbundle file, would it be possible to publish a pure MSI file?

### Why do you think this is needed?

Not all systems (Citrix) is compatible with Windows store applications. The possibility to have a pure MSI file would help us install the application is such systems.

**Comment by veler** [comment]
Hi,

This isn't possible at the moment due to the tight between Microsoft Store and UWP publishing. However it will be done in DevToys 2.0, which won't be a UWP app.

Duplicate with #286

**Comment by vartaxe** [comment]
yup we need msi or exe installer version :)
