### ISSUE TITLE
Add support for HTML Preview

### ISSUE THREAD

**Issue by CozminDev** [veler/DevToys#941]
### What feature or new tool do you think should be added to DevToys?

HTML Preview

### Why do you think this is needed?

To preview HTML code

### Solution/Idea

In the same way we have Markdown Preview, I think it would be awesome to have a HTML Preview

**Comment by Regenhardt** [comment]
I feel like if I want an HTML preview, I'll either just open the file in a browser or use a vscode extension, as that would be where I'd write HTML. What's your use case for having this in DevToys?

**Comment by CozminDev** [comment]
Yeah, there are many solutions for this I agree. I just think it would be very helpful to have it in DevToys too as it is the go to tool for everyday tasks. A use case for this that I had recently was some email templates that I wanted to preview and had to use another app/tool to do this

**Comment by CozminDev** [comment]
I will have a look inside the codebase when I have some time these days, to see the best way we can implement this.

**Comment by veler** [comment]
Agreed with @Regenhardt here. HTML can be previewed in any web browser. It is commonly known that CSS, in particular, variates a bit per web-browser. By including an HTML previewer in DevToys, the preview would be limited to a web engine we chose and likely won't be able to offer to preview it using whatever engine the customer would want.
At this point, it's probably more straightforward to let the customer install the web browser he wants to test the web page on. Pretty sure web developers are used to this approach.
