### ISSUE TITLE
The log file missing when installed failed

### ISSUE THREAD

**Issue by chucklu** [veler/DevToys#942]
### Current behavior

The log file under  you mentioned is missing when installed package 64360VelerSoftware.DevToys_1.0.13.0_neutral_._j80j2txgjg9dj.msixbundle failed?
When I try to install the package, it told me "App Installer failed to install package dependencies. Ask the developer for  package. "

### How to reproduce it (as minimally and precisely as possible)

Install the release package failed

### Expected behavior

when failed, it should told me the exact dependency installed failed, then I can try to install dependency myself

### Screenshots

![image](https://github.com/veler/DevToys/assets/3004057/62db1e71-3525-40f8-817b-799ec28da6b9)

### Workaround

win 10 version 22H2, OS build 19045.3086

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

1.0.13

### Relevant Assets/Logs

no log file generated under the path you mentioned

**Comment by veler** [comment]
Hi @chucklu , are you able to install the app from the Microsoft Store?

**Comment by chucklu** [comment]
@veler  No, our company block the Microsoft Store

**Comment by chucklu** [comment]
My laptop is controlled by the domain policy which blocked us installing software through the Microsoft Store.
I just wonder if you can provide installer with .msi extension  as  https://github.com/PowerShell/PowerShell/releases did
or provide installer with .exe extension as https://github.com/microsoft/PowerToys/releases did

**Comment by chucklu** [comment]
Hi @veler ,
   Any update on this? or maybe you can provide portable zip file of this software?

**Comment by chucklu** [comment]
execute the following powershell command in Powershell 5.0 works

> Add-AppxPackage -Path .\64360VelerSoftware.DevToys_1.0.13.0_neutral_._j80j2txgjg9dj.msixbundle


don't try the above command in ps 7.0, otherwise you will get 

> Add-Appxpackage: The 'Add-Appxpackage' command was found in the module 'Appx', but the module could not be loaded due to the following error: [Operation is not supported on this platform. (0x80131539)]
> For more information, run 'Import-Module Appx'.
