### ISSUE TITLE
allow encoding generated passwords as base64

### ISSUE THREAD

**Issue by butonic** [veler/DevToys#952]
### What improvement do you think would an existing feature or tool in DevToys?

When generating secrets for kubernetes I have to base64 encode them. It would save me some clicking around and copy pasting the generated password into the base64 encoder if I could just toggle base64 encoding.

### Solution/Idea

In the Password Generator configuration add a new 'Encode as base64' toggle (disabled by default)

**Comment by veler** [comment]
This will be possible in DevToys 2.0 through Smart Detection 😁
