### ISSUE TITLE
Image to Data URI conversion

### ISSUE THREAD

**Issue by 274188A** [veler/DevToys#954]
### What feature or new tool do you think should be added to DevToys?

Image to Data URI conversion

### Why do you think this is needed?

Data URI is a method for embedding small images directly in your HTML or CSS code using base64 encoding without the need for additional image files. It's useful when you want to improve performance by reducing the number of HTTP requests needed to load a webpage or when you want to distribute a script/HTML page with some icons or other small images but prefer to keep it in a single file, or include images in email signatures.

They can be used both in HTML, where the image data is placed inside the src attribute or in a CSS file as a background image. This tool lets you select one of both ways or just a raw data URI string without the additional code.

All major browsers currently support data URI in a CSS background property.
Data URI in a HTML image src property is not supported by Internet Explorer.

### Solution/Idea

Implement similar to here: 
https://ezgif.com/image-to-datauri

**Comment by veler** [comment]
Hi,

The Base64 Image Encoder / Decoder tool does exactly this 😁

**Comment by ppo** [comment]
> The Base64 Image Encoder / Decoder tool does exactly this 😁

Actually the decoder doesn't show an image.  
I'm expecting something like this [data URI to image](https://onlinetools.com/image/convert-data-uri-to-image).

This could be add in Image Converter › Image Format › Data URI?

**Test example:**
```
data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7
```

**Comment by veler** [comment]
> data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7

Hi,

It works for me. Are you sure you used the Base64 Image tool and not the Base64 Text tool?

![image](https://github.com/veler/DevToys/assets/3747805/b5b34d1c-d86d-487d-a997-799511425dac)

**Comment by ppo** [comment]
Sorry, wrong repository 🫤  
I'm actually on macOS, so [DevToysMac](https://github.com/ObuchiYuki/DevToysMac)
