### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Oliver-SBI** [veler/DevToys#955]
### What feature or new tool do you think should be added to DevToys?

Add a list sorting section with options for capitalization and CamelCase conversion.
Sort - Alphabetically (Ascending, Descending)

### Why do you think this is needed?

For me its missing, since im then doing a google search and using a online tool.

**Comment by veler** [comment]
Hi,

The text Case Converter and Inspector tool in DevToys does exactly this 😁

**Comment by Issung** [comment]
I had to come to GitHub to suggest this feature only to find this issue which says it's already implemented. Which is great! 
But would be nice if this tool appeared when I searched in DevToys for "sort", "alphabetise" and "order".
