### ISSUE TITLE
add support for more hash algorithms such as SHA3

### ISSUE THREAD

**Issue by uheee** [veler/DevToys#959]
### What feature or new tool do you think should be added to DevToys?

More hash algorithms, such as `SHA3-*`, and dividing `SHA1-3` into different groups.

### Why do you think this is needed?

I use `SHA3-512` at work, this algorithm is not supported by **DevToys**, hope it can be supported.

**Comment by veler** [comment]
Hi,
If I understand well the suggestion, this is already done in DevToys 2.0 and will be released hopefully in the next few months. We merged the Hash generator and Checksum generator into 1 unique tool supporting multiple hash algorithms.
![image](https://github.com/veler/DevToys/assets/3747805/dcc73ee3-d946-4595-b5d7-6b4b618045f1)

**Comment by uheee** [comment]
> Hi, If I understand well the suggestion, this is already done in DevToys 2.0 and will be released hopefully in the next few months. We merged the Hash generator and Checksum generator into 1 unique tool supporting multiple hash algorithms. ![image](https://user-images.githubusercontent.com/3747805/280592702-dcc73ee3-d946-4595-b5d7-6b4b618045f1.png)

Thank you for your reply. Is this `SHA2-512`? It is 2 different algorithms from `SHA3-512`. Is there any plan to add `SHA3` in the future?
