### ISSUE TITLE
Generators / Hash unable to calculate Hash correctly due to inconsistent newline characters on Windows

### ISSUE THREAD

**Issue by doggy8088** [veler/DevToys#960]
### Current behavior

I have a inline script have to put it into a web page and configure CSP header for this. The inline script content below:

```txt
window.dataLayer = window.dataLayer || [];
function gtag() {
dataLayer.push(arguments);
}
gtag('js', new Date());
gtag('config', 'G-XXXXXXXXXX');
```

I have to calculate the `sha256-base64EncodedHash` value of the content for my CSP header. The DevToys produce the wrong hash result and it very possibly caused by the "NEWLINE" character!

### How to reproduce it (as minimally and precisely as possible)

1. Prepare the text for hash
    
    ```txt
    window.dataLayer = window.dataLayer || [];
    function gtag() {
    dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'G-XXXXXXXXXX');
    ```

2. I tried [this website](https://csplite.com/csp/sha/), the Hash result is correct. Just paste the above JS into `Inline scripts/styles' field and hit `Calculate hash` button to get the result. Like below:

    ```txt
    sha256-XIt1SuJNEQJb+jl5/gpNU2NFCVeB9VsTTS6rVIPECB8=
    ```

    The `XIt1SuJNEQJb+jl5/gpNU2NFCVeB9VsTTS6rVIPECB8=` is the base64EncodedHash (SHA256).

3. Use DevToys to calculate the hash, I got this result below, which is different than above one:

    ```txt
    F6Li77u3rHsErlN19VrO5I8SC/xleMs17TCQA8aLX9Y=
    ```

    ![image](https://github.com/veler/DevToys/assets/88981/eeddbd95-f9bc-4526-a6a1-74e23abbb3ed)

### Expected behavior

I expected the result should be the same and it's important to treat newline characters correctly.

### Screenshots

![image](https://github.com/veler/DevToys/assets/88981/eeddbd95-f9bc-4526-a6a1-74e23abbb3ed)

### Workaround

None.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

### Relevant Assets/Logs

I think it's related to this issue: https://github.com/veler/DevToys/issues/758#issuecomment-1460057543 and https://github.com/microsoft/microsoft-ui-xaml/issues/1826

**Comment by veler** [comment]
Hi,
Same thing than in #961. This will be fixed in DevToys 2.0 upon release. We merged the Hash generator and Checksum generator into 1 unique tool, and DevToys 2.0 will support both \r and \n\r.

**Comment by doggy8088** [comment]
May I ask when will 2.0 release?

**Comment by veler** [comment]
We're hoping early next year.
