### ISSUE TITLE
Checksum Generator provide Output Type option

### ISSUE THREAD

**Issue by doggy8088** [veler/DevToys#961]
### What improvement do you think would an existing feature or tool in DevToys?

When I upload a text file to the `Checksum Generator`, I might need to get the Base64 encoded text from the hash value. 

It because the limitation of the "TextBox" treat newline as `\r` by default which is hard to Hash the right way using `Hash Generator`. So I have to save the text to a file and use `Checksum Generator` to do the hash.

Related issue here: https://github.com/veler/DevToys/issues/960

### Solution/Idea

The `Hash Generator` have a **Output Type** to switch between `Hex` and the `Base64`. I think `Checksum Generator` should do the same thing.

**Comment by veler** [comment]
Hi,
This should be fixed in DevToys 2.0. We merged the Hash generator and Checksum generator into 1 unique tool, and DevToys 2.0 will support both `\r` and `\n\r`.
