### ISSUE TITLE
Suggestions for XPath/JSONPath Tester

### ISSUE THREAD

**Issue by VivionLin** [veler/DevToys#962]
### What feature or new tool do you think should be added to DevToys?

Tester for XPath and JSONPath

### Why do you think this is needed?

I'm a developer who always using XML and JSON for API request & response content format.
And I'm a big fan of DevToys.
If DevToys has supports on XPath and JSONPath, then I don't need to install a IDE extension or browser extension ...

### Solution/Idea

* User can find 'XPath Tester' / 'JSONPath Tester' feature in group 'Text'
* Entering the feature, there are 3 main areas:
    1. a long text input field at the top for XPath / JSONPath expression
    2. a multiline text input field on the left for XML / JSON string
    3. match results will be shown on the right

**Comment by veler** [comment]
Duplicate with #165
