### ISSUE TITLE
Ability to launch from system tray (similar to PowerToys)

### ISSUE THREAD

**Issue by AlexChadwickP** [veler/DevToys#966]
### What feature or new tool do you think should be added to DevToys?

It would be handy to be able to have this in the system tray in a similar way to how PowerToys does it

### Why do you think this is needed?

People might already be used to going to the System Tray to use PowerToys instead of keeping the window open. It also reduces clutter on the taskbar while still being able to access the toys.

**Comment by veler** [comment]
Duplicate with #190
