### ISSUE TITLE
Click 'Base64 text' menu, application it closed itself

### ISSUE THREAD

**Issue by GreanInw** [veler/DevToys#968]
### Current behavior

I click 'Base64 text' menu, application it closed itself. From my test, If I change it to 'dark mode', application it closed itself.
![2023-11-03_16-39-22](https://github.com/veler/DevToys/assets/12597286/86b49a52-5868-465e-bd57-e3a65111cba1)

### Expected behavior

I'm not sure what caused this. I just clicked the application and it closed itself.

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/13248682/logs.txt)

**Comment by veler** [comment]
Duplicate with #757
