### ISSUE TITLE
Images In Markdown

### ISSUE THREAD

**Issue by heribertolugo** [veler/DevToys#972]
### Current behavior

Images do not display in markdown preview

### How to reproduce it (as minimally and precisely as possible)

1. Go to text-> Markdown Preview
2. Paste or type in markdown for an image "\!\[image]\(https://github.com/heribertolugo/DevToys/assets/26213368/c20122b5-2609-482a-9337-c9123f7b090f)"

### Expected behavior

image should be displayed

### Screenshots

![image](https://github.com/veler/DevToys/assets/26213368/cd85398b-361b-4b2f-bacb-891bd5063eea)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by veler** [comment]
This will be fixed in DevToys 2.0 thank to its design.

**Comment by veler** [comment]
Coming soon in DevToys 2.0 😁

![image](https://github.com/veler/DevToys/assets/3747805/c89582b8-3382-4358-b940-5f358b787609)
