### ISSUE TITLE
Workload error when building from source

### ISSUE THREAD

**Issue by Randle-Lanre** [veler/DevToys#976]
### Current behavior

when following step 3 of the [contributing.md guide ](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md#how-to-build-and-run-devtoys-from-source)  i get an error stating no matching workload for typescript SDK 4.4 

### Expected behavior

components of  vsconfig2022  should be installed.

### Screenshots

![image](https://github.com/veler/DevToys/assets/19264390/9aa15762-6e38-4904-bd5b-5222cad99b5a)

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

v1.0.13.0 | x64 windows 11 23H2

**Comment by veler** [comment]
Hello,

Thanks for sharing this. I assume the vsconfig should be updated. As a workaround for now, I think you can simply go in the `Individual Components` tab and select these 2 items:

![image](https://github.com/veler/DevToys/assets/3747805/345b91c8-7605-486f-b512-4aac976393c3)
