### ISSUE TITLE
add a screen ruler

### ISSUE THREAD

**Issue by motionz-von** [veler/DevToys#978]
### What feature or new tool do you think should be added to DevToys?

a screen ruler like the one in Microsoft PowerToys, i.e. "Measure Tool" in their source code.
the basic idea is:
1. take a screenshot of the whole screen
2. as the mouse cursor moves, auto detect edges from the cursor to left/right/top/bottom, and give the spacing between the edges (left to right, top to bottom)
3. the spacing can be in pixels or pt(on mac) would be ideal

### Why do you think this is needed?

If you do UI development, chances are:
1. your designer will tell you that there is 1px/pt missing between the 2 UI views
2. in development, you want to double check if the spacing is right. say in Swift UI sometimes, a Spacer() refuse to shrink to zero

a screen ruler comes very handy 

### Solution/Idea

"Measure Tool" in Microsoft PowerToys project is a good reference

**Comment by veler** [comment]
Hi,
PowerToys has such a tool, please consider using it: https://learn.microsoft.com/en-us/windows/powertoys/install
