### ISSUE TITLE
Collapsible sidebar

### ISSUE THREAD

**Issue by Arlodotexe** [veler/DevToys#99]
**Is your feature request related to a problem? Please describe.**
Sidebar always being present draws focus away from contents and impedes productivity using individual tools.

**Describe the solution you'd like**
Allow the sidebar to be collapsed, or the "Open in new window" option to have a hidden sidebar.

**Describe alternatives you've considered**
Making the app smaller I guess, not a great solution.

**Comment by veler** [comment]
Thanks for your suggestion.

It's actually what DevToys was doing in a first few versions, but I got feedback that it wasn't following the "guideline" of Windows 11. 

In the current experience, the side bar only is collapsible only when the window width is under a certain value. See gif below

![devtoys-sidebar](https://user-images.githubusercontent.com/3747805/144689784-66ef5333-2bb2-4488-8215-55cef8875548.gif)


At the same time, here is how it is in Windows 11:
- Settings app has the same behavior than DevToys
- Clock app has the same behavior too.
- Microsoft To Do has the same behavior.
- Mail & Calendar, however, are always collapsible.
- Windows Defender too

At the end of the day, I'm not sure which model I should follow. What do you think about it?

**Comment by Arlodotexe** [comment]
Thanks for the reply @veler. The apps you mentioned are all ones where the user has a lot of content to navigate around in (like DevToys), and may do so pretty frequently (unlike DevToys). 

As a developer tool, I would draw some inspiration from other developer tools that enhance our workflow, such as Visual Studio, Visual Studio code, XAML Studio, etc.

For a tool where you could spend a good amount of time focusing on one tool, it's definitely not necessary to keep navigation visible at all times.

**Comment by veler** [comment]
That's a fair point too :) Thanks for sharing your point of view. @btiteux what do you think? I'm fine with always displaying the hamburger menu (except in compact overlay view).
