### ISSUE TITLE
Click "Base64 Text" Tab crashing

### ISSUE THREAD

**Issue by ToMakeSense** [veler/DevToys#990]
### Current behavior

After changing the App theme to "dark", clicking on the "Base64 Text" tab, the App crashed

### Expected behavior

Changing the app theme should not affect the functionality and stability of the App

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.13.0 | X64 | RELEASE | 2706c6c | 2706c6c

**Comment by veler** [comment]
Duplicate with #755
