### ISSUE TITLE
Enable longuer fields in Text Diff

### ISSUE THREAD

**Issue by tgi-climact** [veler/DevToys#993]
### What improvement do you think would an existing feature or tool in DevToys?

When openning long files, the fields are quite small (especially on large screen).

<img width="2560" alt="image" src="https://github.com/veler/DevToys/assets/139848565/e98cf3db-d1aa-42b2-bdf0-ade89740fac0">

### Solution/Idea

It would be nice to resize based on windows size. An option could be to have a manual cursor. 

Illustration : 

<img width="875" alt="Screenshot 2023-12-08 at 12 03 34" src="https://github.com/veler/DevToys/assets/139848565/8446125c-3689-4b00-8ba9-9889ca4480b5">

### Comments

Version 0.0.10
MacOS Monterey 12.6.8

**Comment by veler** [comment]
Hello,

DevToys does not exist on Mac. What you are using is another app that reuses the DevToys name, called `DevToysMac`. The repository is here: https://github.com/ObuchiYuki/DevToysMac
This repository seems to be unmaintained. 

On my side, I do work at porting DevToys to Mac, but it's not available yet. That being said, the text diff is already implemented on our dev branch, and I can confirm that the new DevToys for Mac will not have this bug.

Thanks

**Comment by tgi-climact** [comment]
Hello @veler,

That's all great news ! And sorry for the confusion on my side...

All the best
